### ISSUE TITLE
[Meta] Replace https://mdn.mozillademos.org references

### ISSUE THREAD

**Issue by caugner** [mdn/translated-content#10400]
## Background

Originally, images in pages on MDN were served from https://mdn.mozillademos.org/files/, and this has since been **deprecated** in favor of putting those images next to the page content.

## Problem

While all occurrences in mdn/content have already been replaced by local images (mostly in [these PRs](https://github.com/mdn/content/pulls?q=is%3Apr+is%3Aclosed+%22mdn.mozillademos.org%22+merged%3A%3C2021-06-30), e.g. [this one](https://github.com/mdn/content/pull/6084/files)), mdn/translated-content still has 2941 occurrences in 941 files referencing that domain.

As we plan to decommission the domain as part of an upcoming move from AWS to GCP, these usages will need to be updated.

### 1. Replace images that exist in content

- https://github.com/mdn/translated-content/pull/10474
- https://github.com/mdn/translated-content/pull/10475
- https://github.com/mdn/translated-content/pull/10476
- https://github.com/mdn/translated-content/pull/10477
- https://github.com/mdn/translated-content/pull/10478
- https://github.com/mdn/translated-content/pull/10479, #10508

### 2. Import missing images

- https://github.com/mdn/translated-content/pull/10480
- https://github.com/mdn/translated-content/pull/10481
- https://github.com/mdn/translated-content/pull/10482
- https://github.com/mdn/translated-content/pull/10483
- https://github.com/mdn/translated-content/pull/10484
- https://github.com/mdn/translated-content/pull/10485

### 3. Other manual tasks

- https://github.com/mdn/translated-content/pull/10404

## Scope

This affects the following locales (according to `rg mdn.mozillademos.org/files/`):

- [x] es (181 pages)
- [x] fr (0 pages)
- [x] ja (48 pages)
- [x] ko (167 pages)
- [x] pt-br (160 pages)
- [ ] ru (267 pages)
- [x] zh-cn (99 pages)
- [x] zh-tw (11 pages)

**Comment by caugner** [comment]
FWIW https://github.com/mdn/translated-content/pull/10402 reduces the number of occurrences from 2941 to 2112 (-829).

**Comment by yin1999** [comment]
@SphinxKnight just wrote a [script](https://gist.github.com/SphinxKnight/60d766b8d6cd970b42eaf967b8dac3ff) before to check duplicated assets before. I'm not sure would it be helpful.

And I've a little question about mdn/yari#5652. When I tried to replace those usages in #6366. I just found more usages which are in `LiveSample`. So I've to wait in favour of the blocking issue. Is there any idea to resolve this, after we move to GCP?

A slightly off topic concern:

> As a developer from mainland China, I'm a bit concern about the network connectivity of GCP to China. Does there have any test on it?

**Comment by caugner** [comment]
> @SphinxKnight just wrote a [script](https://gist.github.com/SphinxKnight/60d766b8d6cd970b42eaf967b8dac3ff) before to check duplicated assets before. I'm not sure would it be helpful.

Thank you for pointing that out. I ran it on https://github.com/mdn/translated-content/pull/10402, but it didn't find any duplicates. Possibly due to the fact that the script compares the sha256 hashes, and our image compression library might not be deterministic, at least not over time. If the script compared the images visually, that would probably spot some more duplicates.

**Comment by caugner** [comment]
> As a developer from mainland China, I'm a bit concern about the network connectivity of GCP to China. Does there have any test on it?

@yin1999 If you can access https://bugzilla.mozilla.org/home (which already moved to GCP), you should also be able to access MDN in the future. 🤞

**Comment by yin1999** [comment]
> > As a developer from mainland China, I'm a bit concern about the network connectivity of GCP to China. Does there have any test on it?
> 
> @yin1999 If you can access https://bugzilla.mozilla.org/home (which already moved to GCP), you should also be able to access MDN in the future. 🤞

Oh, I've made a [test](https://boce.aliyun.com/detect/http/55e54f5ca50540908c8541f108948f69) on it. All **green** on the map!

![image](https://user-images.githubusercontent.com/15844309/207301304-1de103ea-b35e-40d8-b15d-c904c9f6f382.png)

**Comment by yin1999** [comment]
Hey @caugner. I can still find some image references (e.g. [`files/es/learn/forms/how_to_build_custom_form_controls/index.md`](https://github.com/mdn/translated-content/blob/db4ed37005d459ca3f1c71d0f3916fb069c7fa82/files/es/learn/forms/how_to_build_custom_form_controls/index.md?plain=1#L20)), can you go ahead and replace them?
