### ISSUE TITLE
[Meta] Replace @api/deki references

### ISSUE THREAD

**Issue by caugner** [mdn/translated-content#10487]
## Background

A legacy way of referencing images is to use the magic `/@api/deki` prefix, which is essentially a shortcut for `https://mdn.mozillademos.org`, and this has been **deprecated** similar to using the mozillademos domain itself (https://github.com/mdn/translated-content/issues/10400).

## Problem

There are still 750 occurrences on 606 page of `@api/deki` in mdn/translated-content that need to be replaced.

## Scope

- [x] es (139 pages) #11385
- [x] fr (4 pages) - https://github.com/mdn/translated-content/pull/10727
- [x] ja (16 pages) - https://github.com/mdn/translated-content/pull/10682
- [x] ko (67 pages) https://github.com/mdn/translated-content/pull/10507
- [x] pt-BR (69 pages) #16510
- [x] ru (79 pages) #17260
- [x] zh-CN (171 pages) #10854 #10875 #10907 #10936 #10952 #10953
- [x] zh-TW (61 pages) #10854 #10875

**Comment by SphinxKnight** [comment]
@caugner I'm getting 1 page with 4 occurrences in `fr`. I think the content might have changed/deleted since the creation of this. If you have a couple of spare minutes, I'd appreciate a check for the counts :) (PR incoming for `fr` though : ))

**Comment by yin1999** [comment]
Done for l10n-zh

**Comment by hochan222** [comment]
Done for `l10n-ko`.

**Comment by Graywolf9** [comment]
Done for `es`, Thank you

**Comment by leon-win** [comment]
Done for `ru`
