### ISSUE TITLE
zh-cn: complete translation for mdn guidelines

### ISSUE THREAD

**Issue by yin1999** [mdn/translated-content#11063]
We have 3 sections that need to be done:

- [Community](https://developer.mozilla.org/zh-CN/docs/MDN/Community)
  What we could do for the community and what we have.

  - [x] [overview](https://developer.mozilla.org/en-US/docs/MDN/Community) #11348
  - [x] [Contributing to MDN](https://developer.mozilla.org/en-US/docs/MDN/Community/Contributing)
    - [x] [MDN Web Docs Repositories](https://developer.mozilla.org/en-US/docs/MDN/Community/Contributing/Our_repositories) #15724
    - [x] [Getting started with MDN Web Docs](https://developer.mozilla.org/en-US/docs/MDN/Community/Contributing/Getting_started) #15795
    - [x] [Security vulnerability response steps](https://developer.mozilla.org/en-US/docs/MDN/Community/Contributing/Security_vulnerability_response) #16151
    - [x] [MDN Web Docs Localization](https://developer.mozilla.org/en-US/docs/MDN/Community/Contributing/Translated_content) #15732
  - [x] [Open source etiquette](https://developer.mozilla.org/en-US/docs/MDN/Community/Open_source_etiquette)
  - [x] [Communication channels](https://developer.mozilla.org/en-US/docs/MDN/Community/Communication_channels) #13511
  - [x] [Community discussions](https://developer.mozilla.org/en-US/docs/MDN/Community/Discussions) #13815
  - [x] [Learn forum](https://developer.mozilla.org/en-US/docs/MDN/Community/Learn_forum)
  - [x] [Issues](https://developer.mozilla.org/en-US/docs/MDN/Community/Issues) #15706
  - [x] [PR](https://developer.mozilla.org/en-US/docs/MDN/Community/Pull_requests) #13953
  - [x] [MDN content](https://developer.mozilla.org/en-US/docs/MDN/Community/Mdn_content) #15049
  - [x] [Role and teams](https://developer.mozilla.org/en-US/docs/MDN/Community/Roles_teams) #15400

- [Writing guidelines](https://developer.mozilla.org/en-US/docs/MDN/Writing_guidelines)
  How to do contributions

  - [x] [Experimental, deprecated, and obsolete](https://developer.mozilla.org/en-US/docs/MDN/Writing_guidelines/Experimental_deprecated_obsolete) #13406
  - [x] [overview](https://developer.mozilla.org/en-US/docs/MDN/Writing_guidelines) #11064
  - [x] [What we write](https://developer.mozilla.org/en-US/docs/MDN/Writing_guidelines/What_we_write) #12043
    - [x] [Criteria for inclusion](https://developer.mozilla.org/en-US/docs/MDN/Writing_guidelines/What_we_write/Criteria_for_inclusion) #16456

  - [x] [Writing style](https://developer.mozilla.org/en-US/docs/MDN/Writing_guidelines/Writing_style_guide) #13289
    - [x] [Code style guide](https://developer.mozilla.org/en-US/docs/MDN/Writing_guidelines/Writing_style_guide/Code_style_guide) #16990
    - [x] [HTML guideline](https://developer.mozilla.org/en-US/docs/MDN/Writing_guidelines/Writing_style_guide/Code_style_guide/HTML) #17021
    - [x] [CSS guideline](https://developer.mozilla.org/en-US/docs/MDN/Writing_guidelines/Writing_style_guide/Code_style_guide/CSS) #17413
    - [x] [JavaScript guideline](https://developer.mozilla.org/en-US/docs/MDN/Writing_guidelines/Writing_style_guide/Code_style_guide/JavaScript) #17007
    - [x] [Shell prompt guideline](https://developer.mozilla.org/en-US/docs/MDN/Writing_guidelines/Writing_style_guide/Code_style_guide/Shell) #17048

  - [x] [How to](https://developer.mozilla.org/en-US/docs/MDN/Writing_guidelines/Howto) (many sub pages left here) #12296

    - [x] [How to write an API reference](https://developer.mozilla.org/en-US/docs/MDN/Writing_guidelines/Howto/Write_an_api_reference) #12864
      - [x] [API reference sidebars](https://developer.mozilla.org/en-US/docs/MDN/Writing_guidelines/Howto/Write_an_API_reference/Sidebars) #16512
      - [x] [Information contained in a WebIDL file](https://developer.mozilla.org/en-US/docs/MDN/Writing_guidelines/Howto/Write_an_API_reference/Information_contained_in_a_WebIDL_file) #17654
    - [x] [How to create, move, delete, and edit pages](https://developer.mozilla.org/en-US/docs/MDN/Writing_guidelines/Howto/Creating_moving_deleting) #13065
    - [x] [How to write in Markdown](https://developer.mozilla.org/en-US/docs/MDN/Writing_guidelines/Howto/Markdown_in_MDN) #15064
    - [x] [How to add images and media](https://developer.mozilla.org/en-US/docs/MDN/Writing_guidelines/Howto/Images_media) #17559
    - [x] [How to document a CSS property](https://developer.mozilla.org/en-US/docs/MDN/Writing_guidelines/Howto/Document_a_CSS_property) #15585
    - [x] [How to document an HTTP header](https://developer.mozilla.org/en-US/docs/MDN/Writing_guidelines/Howto/Document_an_HTTP_header) #15392
    - [x] [How to document web errors](https://developer.mozilla.org/en-US/docs/MDN/Writing_guidelines/Howto/Document_web_errors) #15616
    - [x] [How to research a technology](https://developer.mozilla.org/en-US/docs/MDN/Writing_guidelines/Howto/Research_technology) #15780 by @yarusome
    - [x] [How to use structured data](https://developer.mozilla.org/en-US/docs/MDN/Writing_guidelines/Howto/JSON_Structured_data) #16506
    - [x] [How to write an entry in the glossary](https://developer.mozilla.org/en-US/docs/MDN/Writing_guidelines/Howto/Write_a_new_entry_in_the_glossary) #10973

  - [x] [Page struct](https://developer.mozilla.org/en-US/docs/MDN/Writing_guidelines/Page_structures) (many sub pages left here)
    - [x] [Banners and notices](https://developer.mozilla.org/en-US/docs/MDN/Writing_guidelines/Page_structures/Banners_and_notices) #13048
    - [x] [Code example](https://developer.mozilla.org/en-US/docs/MDN/Writing_guidelines/Page_structures/Code_examples) (already done)
    - [x] [BCD guide](https://developer.mozilla.org/en-US/docs/MDN/Writing_guidelines/Page_structures/Compatibility_tables) #13584
    - [x] [Live sample](https://developer.mozilla.org/en-US/docs/MDN/Writing_guidelines/Page_structures/Live_samples) (already done)
    - [x] [Page types](https://developer.mozilla.org/en-US/docs/MDN/Writing_guidelines/Page_structures/Page_types) #13876 #15395
    - [x] [Quicklinks](https://developer.mozilla.org/en-US/docs/MDN/Writing_guidelines/Page_structures/Quicklinks) #13655
    - [x] [Specification tables](https://developer.mozilla.org/en-US/docs/MDN/Writing_guidelines/Page_structures/Specification_tables) #13245
    - [x] [Syntax sections](https://developer.mozilla.org/en-US/docs/MDN/Writing_guidelines/Page_structures/Syntax_sections) #15857
    - [x] [Using macros](https://developer.mozilla.org/en-US/docs/MDN/Writing_guidelines/Page_structures/Macros) #13584
      - [x] [Commonly-used macros](https://developer.mozilla.org/en-US/docs/MDN/Writing_guidelines/Page_structures/Macros/Commonly_used_macros) #15338
      - [x] [Other macros](https://developer.mozilla.org/en-US/docs/MDN/Writing_guidelines/Page_structures/Macros/Other) (already done)
    - [ ] [Feature status](https://developer.mozilla.org/en-US/docs/MDN/Writing_guidelines/Page_structures/Feature_status) #19492
  - [x] [copyright](https://developer.mozilla.org/en-US/docs/MDN/Writing_guidelines/Attrib_copyright_license) (small effort) #13575

- [x] [sidebar translation](https://github.com/mdn/yari/blob/main/kumascript/macros/MDNSidebar.ejs)
mdn/yari#9129
- [ ] [changelog](https://developer.mozilla.org/en-US/docs/MDN/Changelog)

**Comment by jasonren0403** [comment]
The 
* [contributing](https://developer.mozilla.org/zh-CN/docs/MDN/Community/Contributing)
* [open source etiquette](https://developer.mozilla.org/zh-CN/docs/MDN/Community/Open_source_etiquette)
* [Learn forum](https://developer.mozilla.org/zh-CN/docs/MDN/Community/Learn_forum)

pages are well done now, we may focus on other pages.

**Comment by awxiaoxian2020** [comment]
I will work on `what we write`

**Comment by yarusome** [comment]
我申请翻译 [How to research a technology](https://developer.mozilla.org/en-US/docs/MDN/Writing_guidelines/Howto/Research_technology)。

**Comment by jasonren0403** [comment]
I will work on [Syntax sections](https://developer.mozilla.org/en-US/docs/MDN/Writing_guidelines/Page_structures/Syntax_sections).

**Comment by yin1999** [comment]
> 我申请翻译 [How to research a technology](https://developer.mozilla.org/en-US/docs/MDN/Writing_guidelines/Howto/Research_technology)。

当然可以，感谢！

**Comment by JasonLamv-t** [comment]
我会更新 [JavaScript guideline](https://developer.mozilla.org/en-US/docs/MDN/Writing_guidelines/Writing_style_guide/Code_style_guide/JavaScript) 部分。

**Comment by jasonren0403** [comment]
我来翻译 [Shell prompt guideline](https://developer.mozilla.org/en-US/docs/MDN/Writing_guidelines/Writing_style_guide/Code_style_guide/Shell) 🙋

**Comment by yin1999** [comment]
I'll translate the "Information contained in a WebIDL file" document

**Comment by jasonren0403** [comment]
Document about feature statuses was added in Febuary 23rd, let's reopen this issue getting this translated 😄
