### ISSUE TITLE
Chore: remove `ARIARole` macro

### ISSUE THREAD

**Issue by SphinxKnight** [mdn/translated-content#11185]
Per https://github.com/orgs/mdn/discussions/263#discussioncomment-4738283

- [x]  `es`/ @mdn/yari-content-es with 5 files #11215
- [x]  `fr` / @mdn/yari-content-fr with 10 files #11339
- [x]  `ja` / @mdn/yari-content-ja with 39 files #11340
- [x]  `ko` / @mdn/yari-content-ko with 29 files https://github.com/mdn/translated-content/pull/11195
- [x]  `pt-BR` / @mdn/yari-content-pt-br with 3 files #11341
- [ ]  `ru` / @mdn/yari-content-ru with 20 files #11342
- [x]  `zh` / @mdn/yari-content-zh with 4 files for `zh-TW` and 21 files for `zh-CN`  #11191

**Comment by yin1999** [comment]
I think we can use regexp to replace those: `\{\{\s*ARIARole\s*\(\s*['"](\S*)['"]\s*\)\s*\}\}`, replaced with `<a href="/<locale>/docs/Web/Accessibility/ARIA/Roles/$1_role"><code>$1</code></a>` (note to replace `<locale>` as the specified one)

Just note some usage in pure markdown (most of them are in html `<table>`).
