### ISSUE TITLE
Chore: remove `fx_minversion_note`

### ISSUE THREAD

**Issue by SphinxKnight** [mdn/translated-content#11187]
This macro has been deprecated (cf. https://github.com/mdn/yari/commit/5c0825da3c3afc8636a874786ea7632982792b96#diff-76628de5a1feb6d6ab23c105f6cae6261049b26275183b1d7ccc583faecb6fce)

- [x]  `es`/ @mdn/yari-content-es with 2 files https://github.com/mdn/translated-content/pull/11214
- [x]  `fr` / @mdn/yari-content-fr with 3 files #11302
- [x]  `ja` / @mdn/yari-content-ja with 2 files #11296
- [x]  `ko` / @mdn/yari-content-ko with 1 file https://github.com/mdn/translated-content/pull/11194
- [x]  `pt-BR` / @mdn/yari-content-pt-br with 2 files #11763
- [x]  `ru` / @mdn/yari-content-ru with 1 file #11763
- [x]  `zh` / @mdn/yari-content-zh with 2 files for `zh-TW` and 5 files for `zh-CN` #11232

**Comment by yin1999** [comment]
Hi @SphinxKnight, it seems that we still have two left in en-US. I'm not really sure how should we deal with this macro

**Comment by SphinxKnight** [comment]
Well, we removed `Spec2` and `SpecName` while there is one left in `en-US` ^^. To me we should dispose of any deprecated macro, regardless their presence in mdn/content (in other words, it doesn't hurt to be in advance for this). Of course, discussion is opened and this issue is merely a tracking issue, each locale may proceed as they see fit and may wait for the removal on the English side first.

**Comment by yin1999** [comment]
poke @mdn/yari-content-web-api for there is two left in content.

- The [`Element.getClientRects()`](https://developer.mozilla.org/en-US/docs/Web/API/Element/getClientRects) seems out-of-date for the current [specification](https://w3c.github.io/csswg-drafts/cssom-view/#dom-element-getclientrects) only mention four members of [DOMRect](https://drafts.fxtf.org/geometry-1/#domrect): `x`, `y`, `width` and `height`.
- The [`Document.createExpression()`](https://developer.mozilla.org/en-US/docs/Web/API/Document/createExpression). We may need to modify this note and move this part to the first paragraph (or a new description section)?

**Comment by Graywolf9** [comment]
Done for `es` thx to @rwxdan !

**Comment by wbamberg** [comment]
> poke @mdn/yari-content-web-api for there is two left in content.
> 
>     * The [`Element.getClientRects()`](https://developer.mozilla.org/en-US/docs/Web/API/Element/getClientRects) seems out-of-date for the current [specification](https://w3c.github.io/csswg-drafts/cssom-view/#dom-element-getclientrects) only mention four members of [DOMRect](https://drafts.fxtf.org/geometry-1/#domrect): `x`, `y`, `width` and `height`.
> 
>     * The [`Document.createExpression()`](https://developer.mozilla.org/en-US/docs/Web/API/Document/createExpression). We may need to modify this note and move this part to the first paragraph (or a new description section)?

@yin1999 , thanks for letting me know. I filed https://github.com/mdn/content/pull/23854 and https://github.com/mdn/content/pull/23855 for these.
