### ISSUE TITLE
[ko] l10n-ko locale RoadMap, 2023

### ISSUE THREAD

**Issue by hochan222** [mdn/translated-content#11314]
ko locale의 점진적인 발전을 위해, 앞으로의 계획들을 같이 생각해보기 위해서 해당 이슈를 생성했습니다.

아래 사항외에도 수정되거나 추가해야할 사항이 있으면 알려주세요. (많은 아이디어를 주세요!) :)

[[ko] l10n-ko locale RoadMap, 2021](https://github.com/mdn/translated-content/issues/2476)의 목표들이 대부분 완료되어 새로운 목표를 설정합니다. 2022년에는 모든 html 파일들이 markdown으로 변환이 완료되었습니다.

## 한국 가이드 문서 개정 v3

가이드가 길어짐에 따라 페이지를 주제별로 분리했습니다.  또한, 지정된 단어를 조금 더 쉽게 습득하고, 혼동이 될 만한 단어/안내사항들을 가이드로 지정하고자 합니다. 가이드에 없지만 혼동이 될 만한 단어나 추가할 사항들은 댓글로 알려주시거나 PR 주세요 :)

- [x] 가이드 페이지 분리: https://github.com/mdn/translated-content/pull/10974
- [ ] https://github.com/mdn/translated-content/issues/3139
- [ ] 사이드바 번역 가이드 추가

## 운영

지속적인 운영을 위해, yari-content-ko 팀을 유지하기 위한 방안을 생각해야합니다.

- [ ] https://github.com/mdn/translated-content/issues/11301
- [ ] MDN translated-content 관련 소식 전달 매체 찾기
