### ISSUE TITLE
Resolve MacroLiveSampleErrors in translated-content

### ISSUE THREAD

**Issue by caugner** [mdn/translated-content#12578]
While testing out https://github.com/mdn/yari/pull/8571, Sentry collected the following `MacroLiveSampleError`s.

The error is: `MacroLiveSampleError within ... (unable to find any live code samples for ...)`

## ja

- [ ] /ja/web/svg/attribute/onclick/index.md, line 25 column 7 ("topexample" within /ja/docs/Web/SVG/Attribute/onclick)
- [ ] /ja/web/svg/attribute/points/index.md, line 25 column 7 ("topexample" within /ja/docs/Web/SVG/Attribute/points)
- [ ] /ja/web/svg/attribute/r/index.md, line 33 column 7 ("topexample" within /ja/docs/Web/SVG/Attribute/r)
- [ ] /ja/web/svg/attribute/marker-mid/index.md, line 26 column 7 ("topexample" within /ja/docs/Web/SVG/Attribute/marker-mid)
- [ ] /ja/web/svg/attribute/fill/index.md, line 39 column 7 ("topexample" within /ja/docs/Web/SVG/Attribute/fill)
- [ ] /ja/web/svg/attribute/cy/index.md, line 21 column 7 ("topexample" within /ja/docs/Web/SVG/Attribute/cy)
- [ ] /ja/web/svg/attribute/d/index.md, line 20 column 7 ("example" within /ja/docs/Web/SVG/Attribute/d)
- [ ] /ja/web/svg/attribute/fill-opacity/index.md, line 30 column 7 ("topexample" within /ja/docs/Web/SVG/Attribute/fill-opacity)
- [ ] /ja/web/svg/attribute/href/index.md, line 19 column 7 ("topexample" within /ja/docs/Web/SVG/Attribute/href)
- [ ] /ja/web/svg/attribute/id/index.md, line 21 column 7 ("topexample" within /ja/docs/Web/SVG/Attribute/id)
- [ ] /ja/web/svg/attribute/cx/index.md, line 21 column 7 ("topexample" within /ja/docs/Web/SVG/Attribute/cx)
- [ ] /ja/web/css/width/index.md, line 98 column 7 ("percentage" within /ja/docs/Web/CSS/width)
- [ ] /ja/web/css/width/index.md, line 109 column 7 ("max-content" within /ja/docs/Web/CSS/width)
- [ ] /ja/web/css/width/index.md, line 119 column 7 ("min-content" within /ja/docs/Web/CSS/width)
- [ ] /ja/web/css/text-transform/index.md, line 90 column 20 ("none" within /ja/docs/Web/CSS/text-transform)
- [ ] /ja/web/css/text-transform/index.md, line 253 column 7 ("full-size-kana" within /ja/docs/Web/CSS/text-transform)
- [ ] /ja/web/css/text-combine-upright/index.md, line 66 column 12 ("all" within /ja/docs/Web/CSS/text-combine-upright)

## ko

- [x] /ko/web/css/animation/index.md, line 187 column 7 ("animation" within /ko/docs/Web/CSS/animation) #14017

## pt-BR

- [x] /pt-br/web/css/width/index.md, line 124 column 7 ("max-content" within /pt-BR/docs/Web/CSS/width) #13309
- [x] /pt-br/web/css/width/index.md, line 133 column 7 ("min-content" within /pt-BR/docs/Web/CSS/width) #13309
- [x] /pt-br/web/css/text-transform/index.md, line 75 column 49 ("none" within /pt-BR/docs/Web/CSS/text-transform) #13309
- [x] /pt-br/web/css/text-align/index.md, line 113 column 19 ("justify" within /pt-BR/docs/Web/CSS/text-align) #13309
- [x] /pt-br/web/css/flex/index.md, line 91 column 7 ("flex" within /pt-BR/docs/Web/CSS/flex) #13309
- [x] /pt-br/web/css/background-size/index.md, line 81 column 7 ("background-size" within /pt-BR/docs/Web/CSS/background-size) #13309
- [x] /pt-br/web/css/animation/index.md, line 188 column 7 ("animation" within /pt-BR/docs/Web/CSS/animation) (#13444)

## ru

- [x] /ru/web/svg/attribute/fill-rule/index.md, line 28 column 7 ("topexample" within /ru/docs/Web/SVG/Attribute/fill-rule) #16926
- [x] /ru/web/svg/attribute/r/index.md, line 33 column 7 ("topexample" within /ru/docs/Web/SVG/Attribute/r) #16968
- [x] /ru/web/svg/attribute/id/index.md, line 23 column 7 ("topexample" within /ru/docs/Web/SVG/Attribute/id) #16968
- [x] /ru/web/svg/attribute/dur/index.md, line 27 column 7 ("topexample" within /ru/docs/Web/SVG/Attribute/dur) #16968
- [x] /ru/web/svg/attribute/d/index.md, line 21 column 7 ("example" within /ru/docs/Web/SVG/Attribute/d) #16968
- [x] /ru/web/svg/attribute/attributename/index.md, line 24 column 7 ("topexample" within /ru/docs/Web/SVG/Attribute/attributeName) #16968
- [x] /ru/web/css/css_backgrounds_and_borders/border-radius_generator/index.md, line 1580 column 7 ("border-radius-generator" withi... #16959
- [x] /ru/web/css/vertical-align/index.md, line 96 column 7 ("vertical-align-table" within /ru/docs/Web/CSS/vertical-align) #16934
- [x] /ru/web/css/vertical-align/index.md, line 68 column 7 ("vertical-align-inline" within /ru/docs/Web/CSS/vertical-align) #16934
- [x] /ru/web/css/mix-blend-mode/index.md, line 549 column 7 ("mix-blend-mode" within /ru/docs/Web/CSS/mix-blend-mode) #16968
- [x] /ru/web/css/mix-blend-mode/index.md, line 549 column 7 ("mix-blend-mode" within /ru/docs/Web/CSS/mix-blend-mode) #16968
- [x] /ru/web/css/clip-path/index.md, line 459 column 7 ("clip-path" within /ru/docs/Web/CSS/clip-path) #16931
- [x] /ru/web/css/accent-color/index.html, line 95 column 1 ("setting_a_custom_accent_color" within /ru/docs/Web/CSS/accent-color) #16985

## zh-CN

- [x] /zh-cn/web/svg/element/marker/index.md, line 51 column 16 ("example" within /zh-CN/docs/Web/SVG/Element/marker) #12600
- [x] /zh-cn/web/svg/element/radialgradient/index.md, line 60 column 12 ("示例" within /zh-CN/docs/Web/SVG/Element/radialGradient) #12680
- [x] /zh-cn/web/css/text-transform/index.md, line 73 column 49 ("none" within /zh-CN/docs/Web/CSS/text-transform) #12603
- [x] /zh-cn/web/css/column-span/index.md, line 47 column 12 ("示例" within /zh-CN/docs/Web/CSS/column-span) #12839

## zh-TW

- [x] /zh-tw/web/css/transform/index.md, line 83 column 12 ("平移、旋轉元素" within /zh-TW/docs/Web/CSS/transform) #12830

**Comment by yin1999** [comment]
Done for `l10n-zh`, thanks @fwqaaq, @jasonren0403, and @yarusome :)

**Comment by YujiSoftware** [comment]
Related: https://github.com/mdn/yari/issues/4971

**Comment by leon-win** [comment]
Hi all! :hand:

I've made several PR's that fix the problem for `ru` locale: #16926, #16931, #16934, #16959, #16964, #16968.

They fix the problems described in this issue. In addition, I found several more pages where `MacroLiveSampleError` is currently present.

#16968 is the largest (in terms of the number of changed files), but all these changes are trivial, that is, they can be understood without knowledge of the Russian language. If anyone can help with its review and merge, that would be very cool! :pray: :relaxed: :handshake:

**Comment by leon-win** [comment]
And one more PR (#16985), it fixes last item in `ru` list: `/ru/web/css/accent-color/index.html, line 95 column 1 ("setting_a_custom_accent_color" within /ru/docs/Web/CSS/accent-color)` :)

**Comment by sashasushko** [comment]
Done for RU. Thanks a lot @leon-win ❤️
