### ISSUE TITLE
[zh-cn] The proofreading and update plan of Javascript.Array 

### ISSUE THREAD

**Issue by JasonLamv-t** [mdn/translated-content#12761]
I intend to proofread and update(add) the translations for the `Javascript.Array `section, and have already started doing so. Contributions from anyone are welcome. If you open a PR for the `Array` section in zh-cn, please mention me so that I can add it to the following progress list:

- [x] array in #12763
- [x] @@iterator in #12769
- [x] @@species in #12790
- [x] @@unscopables in #12793
- [x] array(constructor) in #12801
- [x] at
- [x] concat
- [x] copywithin
- [x] entries in #12762
- [x] every in #12764
- [x] fill
- [x] filter in #12765
- [x] find
- [x] findindex in #12766
- [x] findlast in #12804, thanks to @robert-jx
- [x] findlastindex in #12853, thanks to @robert-jx.
- [x] flat
- [x] flatmap in #12768
- [x] foreach in #12822
- [x] from
- [x] fromasync
- [x] group
- [x] grouptomap
- [x] includes in #12854, thanks to@robert-jx.
- [x] indexof in #12857, thanks to @robert-jx.
- [x] isarray in #12861, thanks to @robert-jx.
- [x] join in #12873
- [x] keys in #12862, thanks to @robert-jx.
- [x] lastindexof in #12873
- [x] length in #12880
- [x] map in #12951
- [x] of
- [x] pop in #12922, thanks to @qibing147147.
- [x] push in #12977, thanks to @robert-jx.
- [ ] reduce in #13024
- [ ] reduceright in #13024
- [x] reverse in #12926, thanks to @robert-jx.
- [x] shift in #12929, thanks to @robert-jx.
- [x] slice in #13064, thanks to @yangmeijuan.
- [x] some in #13072
- [x] sort in #13079, thanks to @CheNgie3.
- [x] splice in #13077,  thanks to @robert-jx.
- [x] tolocalestring in #12995, thanks to @robert-jx.
- [x] toreversed in #12835, thanks to @coolzjy.
- [x] in #12927
- [x] tospliced in #12956, thanks to @robert-jx.
- [x] tostring in #12968, thanks to @robert-jx.
- [x] unshift #12970, thanks to @robert-jx.
- [x] values in #13105
- [x] with in #12811, thanks to @coolzjy.

**Comment by yin1999** [comment]
Thanks @JasonLamv-t, I've assigned you to do this job :)

**Comment by JasonLamv-t** [comment]
🚀 The progress of the task is over half!

**Comment by JasonLamv-t** [comment]
Currently, all tasks have undergone one round of proofreading and updates (although some PRs have not been merged). To avoid any errors or omissions that may have arisen from source updates during this month, quick proofreading of the content will be conducted this week.

**Comment by JasonLamv-t** [comment]
Hello there! I'm pleased to announce that the proofreading and updating of the `Array` section of `JavaScript` is almost complete. This achievement would not have been possible without the exceptional efforts of @robert-jx, @qibing147147, @yangmeijuan, @CheNgie3, and @coolxxy. I would also like to express my gratitude to @yin1999 and other community partners for their valuable feedback and review. Thank you all for your contributions and dedication to improving the experience of MDN.

**Comment by yin1999** [comment]
Thanks for your help @JasonLamv-t :+1:
