### ISSUE TITLE
zh-cn: Proofreading and update plan about `Object` section of JavaScript

### ISSUE THREAD

**Issue by JasonLamv-t** [mdn/translated-content#13211]
I plan to proofread and update the translation of the `Javascript.Object` section. Anyone is welcome to contribute. If you find any issues with the Simplified Chinese Object section or have already submitted a PR, please mention me so that I can add your work to the progress list below:

- [x] Object: in #13225.
- [x] \_\_definegetter\_\_: in #13541.
- [x] \_\_definesetter\_\_: in #13551.
- [x] \_\_lookupgetter\_\_: in #13579.
- [x] \_\_lookupsetter\_\_: in #13583.
- [x] assign: in #13256.
- [x] constructor: #13278.
- [x] create: in #13301.
- [x] defineproperties: in #13358.
- [x] defineproperty: in #13333.
- [x] entries: in #13370, thanks to @robert-jx.
- [x] freeze: in #13394.
- [x] fromentries: in #13415, thanks to @robert-jx.
- [x] getownpropertydescriptor: in #13587.
- [x] getownpropertydescriptors: in #13586.
- [x] getownpropertynames: in #13595.
- [x] getownpropertysymbols: in #13535.
- [x] getprototypeof: in #13536.
- [x] hasown: the main content is basically the same.
- [x] hasownproperty: in #13361, thanks to @robert-jx.
- [x] is: in #13283, thanks to @robert-jx.
- [x] isextensible: in #13493.
- [x] isfrozen: in #13395.
- [x] isprototypeof: in #13381, thanks to @Irene200825.
- [x] issealed: in #13537.
- [x] keys: in #13212, thanks to @robert-jx.
- [x] object: in #13223, thanks to @robert-jx.
- [x] preventextensions: in #13471.
- [x] propertyisenumerable: in #13596.
- [x] proto: in #13509.
- [x] seal: in #13475, thanks to @robert-jx.
- [x] setprototypeof: in #13526.
- [x] tolocalestring: in #13356, thanks to @robert-jx.
- [x] tostring: the main content is basically the same.
- [x] valueof: in #13588, thanks to @robert-jx.
- [x] values: in #13314, thanks to @robert-jx.

**Comment by robert-jx** [comment]
I plan to translate the `Object.keys()`,see #13212

**Comment by robert-jx** [comment]
I plan to translate the `Object()`,see #13223

**Comment by Irene200825** [comment]
I plan to translate the isprototypeof,see [#13381](https://github.com/mdn/translated-content/pull/13358)

**Comment by Irene200825** [comment]
I plan to translate the isprototypeof,see [13381](https://github.com/mdn/translated-content/pull/13381)

**Comment by JasonLamv-t** [comment]
All documents have been proofread and updated. This week, I will conduct another quick proofreading and update to ensure consistency across related sections in different documents and fix any errors that may have been missed in the first round.

**Comment by JasonLamv-t** [comment]
Hello there! I'm pleased to announce that the proofreading and updating of the Object section of JavaScript are all done. This achievement would not have been possible without the exceptional efforts of @robert-jx and @Irene200825. I would also like to express my gratitude to @yin1999 and other community partners for their valuable feedback and review. Thank you all for your contributions and dedication to improving the experience of MDN.
