### ISSUE TITLE
Content suggestion: l10n-zh(cn) of JavaScript Regular expressions part

### ISSUE THREAD

**Issue by jasonren0403** [mdn/translated-content#13254]
## What is the new suggestion?

Currently, MDN has just landed Regex reference on mdn/content#22210, and it's worth it to have it translated to Chinese.

## Why is it important or useful?

Localizing such pages may help Chinese readers understand more about regex in JavaScript.

## Other supporting information

N/A

## Task

**Note:** You may change the Chinese title below to more fitting one during localization.

- [ ] [概述页](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Regular_expressions)
- [ ] [反向引用](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Regular_expressions/Backreference)
- [ ] [捕获组](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Regular_expressions/Capturing_group)
- [ ] [字符类转义](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Regular_expressions/Character_class_escape)
- [ ] [字符类](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Regular_expressions/Character_class)
- [ ] [字符转义](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Regular_expressions/Character_escape)
- [ ] [析取符](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Regular_expressions/Disjunction)
- [ ] [输入边界断言](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Regular_expressions/Input_boundary_assertion)
- [ ] [字面量字符](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Regular_expressions/Literal_character)
- [ ] [前向断言](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Regular_expressions/Lookahead_assertion)
- [ ] [后向断言](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Regular_expressions/Lookbehind_assertion)
- [ ] [命名反向引用](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Regular_expressions/Named_backreference)
- [ ] [命名捕获组](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Regular_expressions/Named_capturing_group)
- [ ] [非捕获组](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Regular_expressions/Non-capturing_group)
- [ ] [量词](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Regular_expressions/Quantifier)
- [ ] [Unicode 字符类转义](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Regular_expressions/Unicode_character_class_escape)
- [ ] [通配符](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Regular_expressions/Wildcard)
- [ ] [单词边界断言](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Regular_expressions/Word_boundary_assertion)

**Comment by yarusome** [comment]
1. “命名”（= naming） → “具名”（named）。
  2. literal 虽然作名词时译为“字面量”，但在 literal character 词组中作形容词，故可按本意译为“字面”。

**Comment by Josh-Cena** [comment]
可以等到 https://github.com/mdn/content/pull/26944 之后再一起翻译。

另外 "disjunction" 翻译成「析取符」有点奇怪（因为我不大见到「析取」这个词），感觉翻译成「选择表达式」更容易理解？这样 "alternative" 可以翻译成「选项」。

**Comment by jasonren0403** [comment]
> 可以等到 [mdn/content#26944](https://github.com/mdn/content/pull/26944) 之后再一起翻译。
> 
> 另外 "disjunction" 翻译成「析取符」有点奇怪（因为我不大见到「析取」这个词），感觉翻译成「选择表达式」更容易理解？这样 "alternative" 可以翻译成「选项」。

“析取”就是“逻辑或”，只不过是逻辑学所用的术语。这里确实“选择表达式”更易于理解些
