### ISSUE TITLE
Resolve macro render errors in translated-content

### ISSUE THREAD

**Issue by caugner** [mdn/translated-content#13499]
We have begun collecting build errors during our nightly builds (see also: https://github.com/mdn/translated-content/issues/12578), and with https://github.com/mdn/yari/pull/8953 we now also see where other macros fail to render:

## es

- [x] The compat macro on /es/docs/Web/API/Fetch_API/Using_Fetch failed to render. Error: /home/runner/...
- [x] The compat macro on /es/docs/conflicting/Web/API/CustomElementRegistry/define failed to render. E...
- [x] The compat macro on /es/docs/conflicting/Web/API/Geolocation/getCurrentPosition failed to render....
- [x] The compat macro on /es/docs/conflicting/Web/CSS/outline failed to render. Error: /home/runner/wo...
- [x] The compat macro on /es/docs/conflicting/Web/HTML/Element/audio failed to render. Error: /home/ru...
- [x] The compat macro on /es/docs/conflicting/Web/HTML/Element/slot failed to render. Error: /home/run...
- [x] The compat macro on /es/docs/orphaned/Web/API/HTMLShadowElement failed to render. Error: /home/ru...
- [x] The compat macro on /es/docs/orphaned/Web/API/HTMLShadowElement/getDistributedNodes failed to ren...
- [x] The compat macro on /es/docs/orphaned/Web/API/NavigatorLanguage failed to render. Error: /home/ru...
- [x] The compat macro on /es/docs/orphaned/Web/API/NavigatorLanguage/language failed to render. Error:...
- [x] The compat macro on /es/docs/orphaned/Web/API/NavigatorOnLine failed to render. Error: /home/runn...
- [x] The compat macro on /es/docs/orphaned/Web/API/NavigatorOnLine/onLine failed to render. Error: /ho...
- [x] The specifications macro on /es/docs/Web/API/Fetch_API/Using_Fetch failed to render. Error: /home...
- [x] The specifications macro on /es/docs/Web/CSS/CSS_box_model/Introduction_to_the_CSS_box_model fail...
- [x] The specifications macro on /es/docs/Web/CSS/CSS_box_model/Mastering_margin_collapsing failed to ...
- [x] The specifications macro on /es/docs/Web/JavaScript/Data_structures failed to render. Error: /hom...
- [x] The specifications macro on /es/docs/conflicting/Web/API/CanvasRenderingContext2D failed to rende...
- [x] The specifications macro on /es/docs/conflicting/Web/API/CustomElementRegistry/define failed to r...
- [x] The specifications macro on /es/docs/conflicting/Web/API/Geolocation/getCurrentPosition failed to...
- [x] The specifications macro on /es/docs/conflicting/Web/HTML/Element/audio failed to render. Error: ...
- [x] The specifications macro on /es/docs/orphaned/Web/API/NavigatorLanguage failed to render. Error: ...
- [x] The specifications macro on /es/docs/orphaned/Web/API/NavigatorLanguage/language failed to render...
- [x] The specifications macro on /es/docs/orphaned/Web/API/NavigatorOnLine failed to render. Error: /h...
- [x] The specifications macro on /es/docs/orphaned/Web/API/NavigatorOnLine/onLine failed to render. Er...

## fr

- [x] The compat macro on /fr/docs/Learn/CSS/First_steps/What_is_CSS failed to render. Error: /home/run...
- [x] The compat macro on /fr/docs/Web/API/Fetch_API/Using_Fetch failed to render. Error: /home/runner/...
- [x] The compat macro on /fr/docs/Web/CSS/@media/aural failed to render. Error: /home/runner/work/yari...
- [x] The compat macro on /fr/docs/Web/CSS/At-rule failed to render. Error: /home/runner/work/yari/yari...
- [x] The compat macro on /fr/docs/Web/CSS/CSS_animations failed to render. Error: /home/runner/work/ya...  #29676
- [x] The compat macro on /fr/docs/Web/CSS/CSS_colors failed to render. Error: /home/runner/work/yari/y... #29677
- [x] The compat macro on /fr/docs/Web/CSS/CSS_compositing_and_blending failed to render. Error: /home/... #29678
- [x] The compat macro on /fr/docs/Web/CSS/CSS_filter_effects failed to render. Error: /home/runner/wor... #29679
- [x] The compat macro on /fr/docs/Web/CSS/Using_CSS_custom_properties failed to render. Error: /home/r... #31591
- [x] The compat macro on /fr/docs/Web/CSS/custom-ident failed to render. Error: /home/runner/work/yari...
- [x] The compat macro on /fr/docs/Web/CSS/mask-border-mode failed to render. Error: /home/runner/work/... #31591
- [x] The compat macro on /fr/docs/Web/CSS/resolved_value failed to render. Error: /home/runner/work/ya... #31591
- [x] The compat macro on /fr/docs/Web/CSS/used_value failed to render. Error: /home/runner/work/yari/y... #31591
- [x] The compat macro on /fr/docs/Web/EXSLT/exsl failed to render. Error: /home/runner/work/yari/yari/... #31591
- [x] The compat macro on /fr/docs/Web/EXSLT/math failed to render. Error: /home/runner/work/yari/yari/... #31591
- [x] The compat macro on /fr/docs/Web/EXSLT/set failed to render. Error: /home/runner/work/yari/yari/k... #31591
- [x] The compat macro on /fr/docs/Web/EXSLT/str failed to render. Error: /home/runner/work/yari/yari/k... #31591
- [x] The compat macro on /fr/docs/Web/HTML/Attributes/elementtiming failed to render. Error: /home/run... #29664
- [x] The compat macro on /fr/docs/Web/HTML/Element/menuitem failed to render. Error: /home/runner/work...
- [x] The compat macro on /fr/docs/Web/HTTP/Basics_of_HTTP/Identifying_resources_on_the_Web failed to r...
- [x] The compat macro on /fr/docs/Web/HTTP/Headers/Accept-Charset failed to render. Error: /home/runne...
- [x] The compat macro on /fr/docs/Web/HTTP/Headers/Allow failed to render. Error: /home/runner/work/ya...
- [x] The compat macro on /fr/docs/Web/HTTP/Methods/PATCH failed to render. Error: /home/runner/work/ya... #30021
- [x] The compat macro on /fr/docs/Web/HTTP/Status/101 failed to render. Error: /home/runner/work/yari/... #31591
- [x] The compat macro on /fr/docs/Web/Security/Certificate_Transparency failed to render. Error: /home... #29675
- [x] The specifications macro on /fr/docs/Web/API/Fetch_API/Using_Fetch failed to render. Error: /home...
- [x] The specifications macro on /fr/docs/Web/CSS/CSS_box_model/Mastering_margin_collapsing failed to ... #29665
- [x] The specifications macro on /fr/docs/Web/CSS/CSS_transitions/Using_CSS_transitions failed to rend... mdn/content#27113
- [x] The specifications macro on /fr/docs/Web/HTML/Attributes/elementtiming failed to render. Error: /... #29664
- [x] The specifications macro on /fr/docs/Web/HTML/Element/menuitem failed to render. Error: /home/run...
- [x] The specifications macro on /fr/docs/Web/HTTP/Headers/Accept-Charset failed to render. Error: /ho...
- [x] The specifications macro on /fr/docs/Web/JavaScript/Event_loop failed to render. Error: /home/run...
- [x] The specifications macro on /fr/docs/Web/Security/Certificate_Transparency failed to render. Erro... #29675

## ja

- [x] The compat macro on /ja/docs/MDN/Writing_guidelines/Howto/Document_an_HTTP_header failed to rende...
- [x] The compat macro on /ja/docs/Web/API/Fetch_API/Using_Fetch failed to render. Error: /home/runner/... #16834
- [x] The compat macro on /ja/docs/Web/API/Performance_API/Navigation_timing failed to render. Error: /...
- [x] #24234
- [x] #24235
- [x] The compat macro on /ja/docs/Web/HTML/Element/menuitem failed to render. Error: /home/runner/work... #13912
- [x] The compat macro on /ja/docs/conflicting/Web/API/CloseEvent failed to render. Error: /home/runner...
- [ ] The compat macro on /ja/docs/conflicting/Web/API/Document failed to render. Error: /home/runner/w...
- [ ] The compat macro on /ja/docs/conflicting/Web/API/HTMLInputElement failed to render. Error: /home/...
- [ ] The compat macro on /ja/docs/conflicting/Web/API/Text failed to render. Error: /home/runner/work/...
- [ ] The compat macro on /ja/docs/conflicting/Web/CSS/print-color-adjust failed to render. Error: /hom...
- [x] The specifications macro on /ja/docs/Web/API/Fetch_API/Using_Fetch failed to render. Error: /home...
- [x] The specifications macro on /ja/docs/Web/CSS/CSS_Functions failed to render. Error: /home/runner/...
- [x] The specifications macro on /ja/docs/Web/CSS/CSS_box_model/Introduction_to_the_CSS_box_model fail...
- [x] The specifications macro on /ja/docs/Web/CSS/CSS_box_model/Mastering_margin_collapsing failed to ...
- [x] The specifications macro on /ja/docs/Web/CSS/CSS_transitions/Using_CSS_transitions failed to rend... mdn/content#27113
- [ ] The specifications macro on /ja/docs/conflicting/Web/CSS/print-color-adjust failed to render. Err...

## ko

Done in #15097 

- [x] The compat macro on /ko/docs/Learn/CSS/Building_blocks/Debugging_CSS failed to render. Error: /ho...
- [x] The compat macro on /ko/docs/Learn/CSS/First_steps/What_is_CSS failed to render. Error: /home/run...
- [x] The compat macro on /ko/docs/Web/API/AudioWorkletProcessor/process failed to render. Error: /home...
- [x] The compat macro on /ko/docs/Web/API/Fetch_API/Using_Fetch failed to render. Error: /home/runner/...
- [x] The compat macro on /ko/docs/Web/API/Performance_API/Navigation_timing failed to render. Error: /...
- [x] The compat macro on /ko/docs/Web/CSS/CSS_animations failed to render. Error: /home/runner/work/ya...
- [x] The compat macro on /ko/docs/Web/CSS/CSS_colors failed to render. Error: /home/runner/work/yari/y...
- [x] The compat macro on /ko/docs/Web/CSS/CSS_compositing_and_blending failed to render. Error: /home/...
- [x] The compat macro on /ko/docs/Web/CSS/CSS_filter_effects failed to render. Error: /home/runner/wor...
- [x] The compat macro on /ko/docs/Web/CSS/Pseudo-elements failed to render. Error: /home/runner/work/y...
- [x] The compat macro on /ko/docs/Web/CSS/Using_CSS_custom_properties failed to render. Error: /home/r...
- [x] The compat macro on /ko/docs/Web/HTTP/Headers/X-Forwarded-For failed to render. Error: /home/runn...
- [x] The compat macro on /ko/docs/Web/HTTP/Headers/X-Forwarded-Host failed to render. Error: /home/run...
- [x] The compat macro on /ko/docs/Web/Media/Formats/Containers failed to render. Error: /home/runner/w...
- [x] The compat macro on /ko/docs/orphaned/Web/HTML/Element/applet failed to render. Error: /home/runn...
- [x] The compat macro on /ko/docs/orphaned/Web/SVG/Element/altGlyph failed to render. Error: /home/run...
- [x] The specifications macro on /ko/docs/Glossary/Origin failed to render. Error: /home/runner/work/y...
- [x] The specifications macro on /ko/docs/Glossary/Truthy failed to render. Error: /home/runner/work/y...
- [x] The specifications macro on /ko/docs/Web/API/Fetch_API/Using_Fetch failed to render. Error: /home...
- [x] The specifications macro on /ko/docs/Web/API/File_API/Using_files_from_web_applications failed to...
- [x] The specifications macro on /ko/docs/Web/API/Proximity_Events failed to render. Error: /home/runn...
- [x] The specifications macro on /ko/docs/Web/API/Service_Worker_API/Using_Service_Workers failed to r...
- [x] The specifications macro on /ko/docs/Web/CSS/CSS_box_model/Introduction_to_the_CSS_box_model fail...
- [x] The specifications macro on /ko/docs/Web/CSS/CSS_box_model/Mastering_margin_collapsing failed to ...
- [x] The specifications macro on /ko/docs/Web/CSS/CSS_transitions/Using_CSS_transitions failed to rend... mdn/content#27113
- [x] The specifications macro on /ko/docs/Web/CSS/Comments failed to render. Error: /home/runner/work/...
- [x] The specifications macro on /ko/docs/Web/JavaScript/Guide/Regular_expressions/Assertions failed t...
- [x] The specifications macro on /ko/docs/Web/JavaScript/Guide/Typed_arrays failed to render. Error: /...
- [x] The specifications macro on /ko/docs/Web/Media/Formats/Containers failed to render. Error: /home/...
- [x] The specifications macro on /ko/docs/orphaned/Web/SVG/Element/altGlyph failed to render. Error: /...

## pt-br

- [ ] The compat macro on /pt-BR/docs/orphaned/Web/API/NavigatorID failed to render. Error: /home/runne...
- [ ] The compat macro on /pt-BR/docs/orphaned/Web/API/NavigatorLanguage failed to render. Error: /home...
- [ ] The compat macro on /pt-BR/docs/orphaned/Web/API/NavigatorOnLine failed to render. Error: /home/r...
- [ ] The page macro on /pt-BR/docs/Web/API/BatteryManager/charging failed to render. KumascriptError: ...
- [ ] The page macro on /pt-BR/docs/Web/API/BatteryManager/chargingTime failed to render. KumascriptErr...
- [ ] The page macro on /pt-BR/docs/Web/API/BatteryManager/chargingchange_event failed to render. Kumas...
- [ ] The page macro on /pt-BR/docs/Web/API/BatteryManager/chargingtimechange_event failed to render. K...
- [ ] The page macro on /pt-BR/docs/Web/API/BatteryManager/dischargingTime failed to render. Kumascript...
- [ ] The page macro on /pt-BR/docs/Web/API/BatteryManager/dischargingtimechange_event failed to render...
- [ ] The page macro on /pt-BR/docs/Web/API/BatteryManager/level failed to render. KumascriptError: /ho...
- [ ] The page macro on /pt-BR/docs/Web/API/BatteryManager/levelchange_event failed to render. Kumascri...
- [ ] The page macro on /pt-BR/docs/Web/API/Battery_Status_API failed to render. KumascriptError: /home...
- [ ] The page macro on /pt-BR/docs/Web/API/BiquadFilterNode failed to render. Error: /home/runner/work...
- [ ] The page macro on /pt-BR/docs/Web/API/Document failed to render. Error: /home/runner/work/yari/ya...
- [ ] The page macro on /pt-BR/docs/Web/API/File failed to render. KumascriptError: /home/runner/work/y...
- [ ] The page macro on /pt-BR/docs/Web/JavaScript/Reference failed to render. KumascriptError: /home/r...
- [ ] The specifications macro on /pt-BR/docs/conflicting/Web/API/Window failed to render. Error: /home...
- [ ] The specifications macro on /pt-BR/docs/orphaned/Web/API/NavigatorID failed to render. Error: /ho...

## ru

- [x] The compat macro on /ru/docs/Web/API/Performance_API/Navigation_timing failed to render. Error: /...
- [x] The compat macro on /ru/docs/Web/HTTP/Status/402 failed to render. Error: /home/runner/work/yari/...
- [x] The compat macro on /ru/docs/conflicting/Web/API/CanvasRenderingContext2D failed to render. Error... #16995
- [x] The compat macro on /ru/docs/conflicting/Web/API/Node failed to render. Error: /home/runner/work/...
- [x] The compat macro on /ru/docs/conflicting/Web/CSS failed to render. Error: /home/runner/work/yari/...
- [x] The compat macro on /ru/docs/conflicting/Web/CSS/CSS_Fonts failed to render. Error: /home/runner/...
- [x] The compat macro on /ru/docs/conflicting/Web/CSS/CSS_Fonts_25d4b407d3e5044aeffb97faa9669a95 faile...
- [x] The compat macro on /ru/docs/conflicting/Web/Manifest failed to render. Error: /home/runner/work/...
- [x] The compat macro on /ru/docs/conflicting/Web/Manifest_7ec32c6987e59d5f1cb08f8c9d900a4c failed to ...
- [x] The compat macro on /ru/docs/conflicting/Web/Manifest_e8c4835b067e177a000dc29c18483205 failed to ...
- [x] The compat macro on /ru/docs/orphaned/Web/API/GlobalEventHandlers failed to render. Error: /home/...
- [x] The compat macro on /ru/docs/orphaned/Web/API/WindowEventHandlers failed to render. Error: /home/...
- [x] The page macro on /ru/docs/Web/API/BatteryManager failed to render. Error: /home/runner/work/yari...
- [x] The page macro on /ru/docs/Web/API/Document failed to render. Error: /home/runner/work/yari/yari/...
- [x] The page macro on /ru/docs/Web/API/Element/animationend_event failed to render. KumascriptError: ...
- [x] The page macro on /ru/docs/Web/API/File failed to render. KumascriptError: /home/runner/work/yari...
- [x] The page macro on /ru/docs/Web/API/Geolocation_API failed to render. Error: /home/runner/work/yar...
- [x] The page macro on /ru/docs/Web/API/HTMLElement/error_event failed to render. KumascriptError: /ho...
- [x] The page macro on /ru/docs/Web/API/HTMLFormElement/length failed to render. KumascriptError: /hom...
- [x] The page macro on /ru/docs/Web/API/MediaElementAudioSourceNode failed to render. Error: /home/run...
- [x] The page macro on /ru/docs/Web/API/Navigator/getUserMedia failed to render. KumascriptError: /hom...
- [x] The page macro on /ru/docs/Web/API/PannerNode failed to render. Error: /home/runner/work/yari/yar...
- [x] The page macro on /ru/docs/Web/API/RTCPeerConnection/RTCPeerConnection failed to render. Kumascri...
- [x] The page macro on /ru/docs/Web/API/RTCPeerConnection/connectionState failed to render. Kumascript...
- [x] The page macro on /ru/docs/Web/HTML/Element/track failed to render. Error: /home/runner/work/yari...
- [x] The page macro on /ru/docs/Web/HTTP/Basics_of_HTTP/MIME_types failed to render. Error: /home/runn...
- [x] The page macro on /ru/docs/Web/JavaScript/Guide/Typed_arrays failed to render. KumascriptError: /...
- [x] The page macro on /ru/docs/Web/JavaScript/Reference failed to render. KumascriptError: /home/runn...
- [x] The page macro on /ru/docs/Web/SVG/Attribute/class failed to render. KumascriptError: /home/runne...
- [x] The page macro on /ru/docs/Web/SVG/Attribute/cx failed to render. Error: /home/runner/work/yari/y...
- [x] The page macro on /ru/docs/Web/SVG/Attribute/letter-spacing failed to render. KumascriptError: /h...
- [x] The page macro on /ru/docs/web/javascript/reference/global_objects/typedarray failed to render. E...
- [x] The specifications macro on /ru/docs/conflicting/Web/API/CanvasRenderingContext2D failed to rende... #16995
- [x] The specifications macro on /ru/docs/conflicting/Web/API/Node failed to render. Error: /home/runn... #16996
- [x] The specifications macro on /ru/docs/conflicting/Web/CSS/CSS_Fonts failed to render. Error: /home... #16997
- [x] The specifications macro on /ru/docs/orphaned/Web/API/NavigatorID failed to render. Error: /home/...

## zh-cn

Done in #13623 

- [x] The compat macro on /zh-CN/docs/Web/API/Fetch_API/Using_Fetch failed to render. Error: /home/runn...
- [x] The compat macro on /zh-CN/docs/Web/API/Performance_API/Navigation_timing failed to render. Error...
- [x] The compat macro on /zh-CN/docs/Web/API/Web_Animations_API/Keyframe_Formats failed to render. Err...
- [x] The compat macro on /zh-CN/docs/Web/CSS/CSS_colors failed to render. Error: /home/runner/work/yar...
- [x] The compat macro on /zh-CN/docs/Web/CSS/CSS_generated_content failed to render. Error: /home/runn...
- [x] The compat macro on /zh-CN/docs/Web/CSS/CSS_media_queries failed to render. Error: /home/runner/w...
- [x] The compat macro on /zh-CN/docs/Web/CSS/Using_CSS_custom_properties failed to render. Error: /hom...
- [x] The compat macro on /zh-CN/docs/Web/CSS/mask-border-mode failed to render. Error: /home/runner/wo...
- [x] The compat macro on /zh-CN/docs/Web/EXSLT/regexp failed to render. Error: /home/runner/work/yari/...
- [x] The compat macro on /zh-CN/docs/Web/HTML/Element/menuitem failed to render. Error: /home/runner/w...
- [x] The compat macro on /zh-CN/docs/Web/HTTP/Headers/Accept-Charset failed to render. Error: /home/ru...
- [x] The compat macro on /zh-CN/docs/Web/HTTP/Headers/Accept-Patch failed to render. Error: /home/runn...
- [x] The compat macro on /zh-CN/docs/Web/HTTP/Status/402 failed to render. Error: /home/runner/work/ya...
- [x] The compat macro on /zh-CN/docs/Web/SVG/Attribute/max failed to render. Error: /home/runner/work/...
- [x] The specifications macro on /zh-CN/docs/Web/API/Fetch_API/Using_Fetch failed to render. Error: /h...
- [x] The specifications macro on /zh-CN/docs/Web/API/Web_Animations_API/Keyframe_Formats failed to ren...
- [x] The specifications macro on /zh-CN/docs/Web/CSS/CSS_Functions failed to render. Error: /home/runn...
- [x] The specifications macro on /zh-CN/docs/Web/CSS/CSS_box_model/Introduction_to_the_CSS_box_model f...
- [x] The specifications macro on /zh-CN/docs/Web/CSS/CSS_box_model/Mastering_margin_collapsing failed ...
- [x] The specifications macro on /zh-CN/docs/Web/CSS/CSS_transitions/Using_CSS_transitions failed to r... mdn/content#27113

## zh-tw

Done in #13550.

- [x] The compat macro on /zh-TW/docs/Learn/CSS/First_steps/What_is_CSS failed to render. Error: /home/...
- [x] The compat macro on /zh-TW/docs/Web/API/Fetch_API/Using_Fetch failed to render. Error: /home/runn...
- [x] The compat macro on /zh-TW/docs/Web/CSS/CSS_animations failed to render. Error: /home/runner/work...
- [x] The compat macro on /zh-TW/docs/Web/Events/Creating_and_triggering_events failed to render. Error...
- [x] The compat macro on /zh-TW/docs/Web/Events/Event_handlers failed to render. Error: /home/runner/w...
- [x] The compat macro on /zh-TW/docs/Web/HTTP/Headers/X-Forwarded-For failed to render. Error: /home/r...
- [x] The compat macro on /zh-TW/docs/Web/JavaScript/Guide/Typed_arrays failed to render. Error: /home/...
- [x] The specifications macro on /zh-TW/docs/Web/API/Fetch_API/Using_Fetch failed to render. Error: /h...
- [x] The specifications macro on /zh-TW/docs/Web/CSS/CSS_box_model/Mastering_margin_collapsing failed ...
- [x] The specifications macro on /zh-TW/docs/Web/Events/Event_handlers failed to render. Error: /home/...
- [x] The specifications macro on /zh-TW/docs/Web/JavaScript/Guide/Typed_arrays failed to render. Error...

**Comment by yin1999** [comment]
When resolving the macro render errors for zh-TW, I found that [this document in en-US](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_box_model/Mastering_margin_collapsing) also has a unrendered specifications macro. @caugner maybe we should waiting for upstream fixes on some files, could you report this in mdn/content with a full collection for en-US ;)

**Comment by jasonren0403** [comment]
All macro render errors have been resolved in l10n-zh.

**Comment by Graywolf9** [comment]
All macro render errors have been resolved for `es`

**Comment by leon-win** [comment]
Do I understand correctly that to solve the problem we must remove the `{{Compat}}` and `{{Specifications}}` macros on the specified pages?

**Comment by yin1999** [comment]
> Do I understand correctly that to solve the problem we must remove the `{{Compat}}` and `{{Specifications}}` macros on the specified pages?

Most of them could be resolved in this way (In fact, we only need to update these sections according to the content of the en-US documents).

**Comment by leon-win** [comment]
I created #16995,  #16996, #16997, #17020, #17022, #17026.
After they are merged the described errors must be corrected.
But it would be good to run the check again to see what errors there are at the moment :)

I ask for help with the review, if anyone has the opportunity :pray:

**Comment by yin1999** [comment]
> I created #16995, #16996, #16997, #17020, #17022, #17026. After they are merged the described errors must be corrected. But it would be good to run the check again to see what errors there are at the moment :)
> 
> I ask for help with the review, if anyone has the opportunity 🙏

It would be better to waiting for the review from the [`l10n-ru` team](https://github.com/mdn/translated-content/blob/main/PEERS_GUIDELINES.md#review-teams). But if you've waited too long, I'm willing to help review the PR for orphan document removal.

**Comment by leon-win** [comment]
> > I created #16995, #16996, #16997, #17020, #17022, #17026. After they are merged the described errors must be corrected. But it would be good to run the check again to see what errors there are at the moment :)
> > I ask for help with the review, if anyone has the opportunity 🙏
> 
> It would be better to waiting for the review from the [`l10n-ru` team](https://github.com/mdn/translated-content/blob/main/PEERS_GUIDELINES.md#review-teams). But if you've waited too long, I'm willing to help review the PR for orphan document removal.

Yes, I understand and agree that it is more logical for members of the [l10n-ru team](https://github.com/mdn/translated-content/blob/main/PEERS_GUIDELINES.md#review-teams) to review. But unfortunately, now many of them do not have enough time for this(((

Therefore, I try to make some PRs (if possible) suitable for review by the entire community))

@yin1999, I am very grateful to you for helping wherever possible! :hugs:

**Comment by leon-win** [comment]
Now it should be fixed for `ru`, but checking would not be superfluous

**Comment by hochan222** [comment]
All macro render errors have been resolved for `ko`.

**Comment by leon-win** [comment]
In the `ru` locale the errors are also fixed, I checked :ok_hand:

**Comment by caugner** [comment]
These appear to have been either all resolved, or they no longer surface in Rari.
