### ISSUE TITLE
zh-CN: Proofreading and update plan for the JavaScript `String` section

### ISSUE THREAD

**Issue by JasonLamv-t** [mdn/translated-content#13975]
I plan to proofread and update the translation of the Javascript.String section. Anyone is welcome to contribute. If you find any issues with the Simplified Chinese String section or have already submitted a PR, please mention me so that I can add your work to the progress list below:

- [x] overview, in #14019.
- [x] constructor, in #14040.
- [x] @@iterator, in #14045.
- [x] anchor, in #15273.
- [x] at, in #14051.
- [x] big, in #15274.
- [x] blink, in #15303.
- [x] bold, in #15304.
- [x] charat, in #14053.
- [x] charcodeat, in #14073.
- [x] codepointat, in #15046.
- [x] concat, in #14111.
- [x] endswith, in #14113.
- [x] fixed, in #15316.
- [x] fontcolor, in #15317.
- [x] fontsize, in #15318.
- [x] fromcharcode, in #15047.
- [x] fromcodepoint, in #15089.
- [x] includes, in #14142.
- [x] indexof, in #14155.
- [x] iswellformed, in #15173.
- [x] italics, in #15333.
- [x] lastindexof, in #14184.
- [x] length, in #14041.
- [x] link, in #15334.
- [x] localecompare, in #14351.
- [x] match, in #14425.
- [x] matchall, in #14468.
- [x] normalize, in #15208.
- [x] padend, in #14633.
- [x] padstart, in #14634.
- [x] raw, in #14779.
- [x] repeat, in #14780.
- [x] replace, in #14858.
- [x] replaceall, in #14902.
- [x] search, in #14964.
- [x] slice, in #15000.
- [x] small, in #15375.
- [x] split, already sync with upstream.
- [x] startswith, in #15020.
- [x] strike, in #15380.
- [x] sub, in #15252, thanks @YangFong 
- [x] substr, in #15284, thanks @YangFong 
- [x] substring, in #15091.
- [x] sup, in #15252, thanks @YangFong 
- [x] tolocalelowercase, in #15117.
- [x] tolocaleuppercase, in #15117.
- [x] tolowercase, in #15117.
- [x] tostring, in #15171.
- [x] touppercase, in #15117.
- [x] towellformed, in #15173.
- [x] trim, in #15119.
- [x] trimend, in #15119.
- [x] trimstart, in #15119.
- [x] valueof, in #15251, thanks @YangFong

**Comment by yarusome** [comment]
备注：mdn/content#26847 中的某些任务可能会进一步改动英文版内容。

**Comment by yin1999** [comment]
Thanks a lot @JasonLamv-t. I'm going to close this as all the docs have been updated :)
