### ISSUE TITLE
ko: update web/security

### ISSUE THREAD

**Issue by SnowMarble** [mdn/translated-content#15075]
#14965 의 web/security와 security 폴더의 전체 번역을 추적하기 위한 이슈입니다.

- [x] index.md (`sourceCommit` already exists)
- [x] certificate_transparency (`sourceCommit` already exists)
- [x] firefox_security_guidelines  #15361
- [x] iframe_credentialless #15373
- [x] insecure_passwords #15076
- [x] mixed_content (index.md) #15387
  - [x] how_to_fix_website_with_mixed_content #15389
- [x] referer_header_colon__privacy_and_security_concerns #15332
- [x] same-origin_policy #15087
- [x] secure_contexts (index.md) (`sourceCommit` already exists)
  - [x] features_restricted_to_secure_contexts #15078
- [x] securing_your_site (index.md)  #15172
  - [x] turning_off_form_autocompletion #15336
- [x] subdomain_takeovers #15306
- [x] subresource_integrity #15261
- [x] transport_layer_security #15094
- [x] types_of_attacks #15166
- [x] user_activation (`sourceCommit` already exists)
- [x] weak_signature_algorithm #15077
