### ISSUE TITLE
ko: update `web/glossary-c`

### ISSUE THREAD

**Issue by IMHOJEONG** [mdn/translated-content#15221]
```[tasklist]
### `web/glossary-c` 작업 리스트 정리
- [x] cache #15293
- [x] cacheable #15293
- [x] caldav #15648
- [x] call_stack #15293
- [x] callback_function #15293
- [x] canonical_order #15649
- [x] canvas #15680
- [x] card_sorting #15685
- [x] carddav #15688
- [x] caret #15693
- [x] cdn #15293
- [x] certificate_authority #15695
- [x] certified #15704
- [x] challenge #15735
- [x] character #15293
- [x] character_encoding #15293
- [x] character_set #15751
- [x] chrome #15752
- [x] cia #15758
- [x] cipher #15761
- [x] cipher_suite #15762
- [x] ciphertext #15767
- [x] class #15771
- [x] clickjacking #15774
- [x] closure #15820
- [x] cms #15828
- [x] code_point #15829
- [x] code_splitting #15293
- [x] code_unit #15831
- [x] codec #15832
- [x] color_wheel #15835
- [x] compile #15293
- [x] compile_time #15836
- [x] composite_operation #15838
- [x] computer_programming #15293
- [x] conditional #15849
- [x] constant #15850
- [x] constructor #15851
- [x] continuous_media #15852
- [x] control_flow #15854
- [x] cookie #15855
- [x] copyleft #15293
- [x] cors #15293
- [x] cors-safelisted_request_header #15791
- [x] cors-safelisted_response_header #15794
- [x] crawler #15293
- [x] crlf #15781
- [x] cross-site_scripting #15782
- [x] cross_axis #15293
- [x] crud #15784
- [x] cryptanalysis #15787
- [x] cryptographic_hash_function #15788
- [x] cryptography #15790
- [x] csp #15293
- [x] csrf #15785
- [x] css #15816
- [x] css_descriptor #15293
- [x] css_pixel #15817
- [x] css_preprocessor #15293
- [x] css_selector #15818
- [x] cssom #15819
```
