### ISSUE TITLE
ko: update `web/glossary-f`

### ISSUE THREAD

**Issue by IMHOJEONG** [mdn/translated-content#15231]
```[tasklist]
### Tasks
- [x] fallback_alignment #15961
- [x] falsy #15301
- [x] favicon #15962
- [x] fetch_directive #15964
- [x] fetch_metadata_request_header #15965
- [x] fingerprinting #15968
- [x] firefox_os #15969
- [x] firewall #15301
- [x] first-class_function #15301
- [x] first_contentful_paint #15971
- [x] first_cpu_idle #15972
- [x] first_input_delay #15975
- [x] first_interactive #15978
- [x] first_meaningful_paint #15984
- [x] first_paint #15986
- [x] flex #15987
- [x] flex_container #15301
- [x] flex_item #15301
- [x] flexbox #15301
- [x] forbidden_header_name #15301
- [x] forbidden_response_header_name #15301
- [x] fork #15301
- [x] fps #15988
- [x] fragmentainer #15992
- [x] ftp #15301
- [x] ftu #15993
- [x] function #15994
- [x] fuzzing #15995
```
