### ISSUE TITLE
ko: update `web/glossary-i`

### ISSUE THREAD

**Issue by IMHOJEONG** [mdn/translated-content#15234]
```[tasklist]
### Tasks
- [x] i18n #16077
- [x] iana #16078
- [x] icann #16079
- [x] ice #16080
- [x] ide #16081
- [x] idempotent #15311
- [x] identifier #15311
- [x] idl #16083
- [x] ietf #16086
- [x] iife #15311
- [x] imap #16087
- [x] immutable #15311
- [x] index.md #16088
- [x] indexeddb #15311
- [x] information_architecture #16103
- [x] inheritance #16104
- [x] ink_overflow #16102
- [x] inline-level_content #15311
- [x] input_method_editor #16101
- [x] instance #16100
- [x] internationalization_and_localization #16099
- [x] internet #16097
- [x] interpolation #16096
- [x] intrinsic_size #16091
- [x] ip_address #15311
- [x] ipv4 #15311
- [x] ipv6 #15311
- [x] irc #16095
- [x] iso #16094
- [x] isp #16093
- [x] itu #16092
```
