### ISSUE TITLE
ko: update `web/glossary-p`

### ISSUE THREAD

**Issue by IMHOJEONG** [mdn/translated-content#15243]
```[tasklist]
### Tasks
- [x] pac #16185
- [x] packet #16187
- [x] page_load_time #16188
- [x] page_prediction #16189
- [x] parameter #16190
- [x] parent_object #16192
- [x] parse #16193
- [x] parser #16194
- [x] payload_body #16195
- [x] payload_header #16198
- [x] pdf #15475
- [x] perceived_performance #16200
- [x] percent-encoding #15475
- [x] php #15475
- [x] pixel #15475
- [x] placeholder_names #16202
- [x] plaintext #16204
- [x] plugin #16206
- [x] png #15475
- [x] polyfill #15475
- [x] polymorphism #16207
- [x] pop #16212
- [x] port #16213
- [x] prefetch #16214
- [x] preflight_request #15475
- [x] prerender #16215
- [x] presto #16216
- [x] primitive #15475
- [x] privileged #16217
- [x] privileged_code #16218
- [x] progressive_enhancement #15475
- [x] progressive_web_apps #16219
- [x] promise #16223
- [x] property #15475
- [x] protocol #15475
- [x] prototype #15475
- [x] prototype-based_programming #15475
- [x] proxy_server #15475
- [x] pseudo-class #16220
- [x] pseudo-element #16221
- [x] pseudocode #15475
- [x] public-key_cryptography #16222
- [x] python #16224
```
