### ISSUE TITLE
ko: update `web/glossary-s`

### ISSUE THREAD

**Issue by IMHOJEONG** [mdn/translated-content#15264]
```[tasklist]
### Tasks
- [x] safe #15495
- [x] same-origin_policy #16268
- [x] scm #16270
- [x] scope #15495
- [x] screen_reader #16284
- [x] script-supporting_element #16285
- [x] scroll_container #16286
- [x] sctp #16290
- [x] sdk #16291
- [x] sdp #16292
- [x] search_engine #16294
- [x] second-level_domain #16295
- [x] secure_context #16296
- [x] self-executing_anonymous_function #15495
- [x] semantics #15495
- [x] seo #15495
- [x] serializable_object #16308
- [x] serialization #16309
- [x] server #15495
- [x] server_timing #16311
- [x] session_hijacking #16312
- [x] sgml #16313
- [x] shadow_tree #16314
- [x] shallow_copy #14940
- [x] shim #15495
- [x] signature #15495
- [x] simd #15495
- [x] simple_header #16315
- [x] simple_response_header #16316
- [x] sisd #16317
- [x] site #16318
- [x] site_map #16319
- [x] sld #16320
- [x] sloppy_mode #16321
- [x] slug #16322
- [x] smoke_test #16323
- [x] smpte #16324
- [x] smtp #15495
- [x] snap_positions #16325
- [x] soap #16326
- [x] spa #16327
- [x] specification #16329
- [x] speculative_parsing #16335
- [x] speed_index #16336
- [x] sql #15495
- [x] sql_injection #16337
- [x] sri #16339
- [x] ssl #15495
- [x] stacking_context #16340
- [x] state_machine #16341
- [x] statement #16348
- [x] static_method #16349
- [x] static_typing #16350
- [x] sticky_activation #16351
- [x] strict_mode #16355
- [x] string #15495
- [x] stringifier #16356
- [x] stun #16357
- [x] style_origin #15495
- [x] stylesheet #16358
- [x] submit_button #16359
- [x] svg #15495
- [x] svn #16360
- [x] symmetric-key_cryptography #16361
- [x] synchronous #15495
- [x] syntax #16362
- [x] syntax_error #16363
- [x] synthetic_monitoring #16365
```

**Comment by SnowMarble** [comment]
#14940 에서 shallow_copy 번역이 완료되었습니다.

**Comment by IMHOJEONG** [comment]
@SnowMarble 님 알려주셔서
감사합니다!
