### ISSUE TITLE
ko: update `web/glossary-r`

### ISSUE THREAD

**Issue by IMHOJEONG** [mdn/translated-content#15263]
```[tasklist]
### Tasks
- [x] rail #16225
- [x] raster_image #16228
- [x] rdf #16229
- [x] real_user_monitoring #16231
- [x] recursion #16235
- [x] reflow #15487
- [x] regular_expression #15487
- [x] render_blocking #16237
- [x] rendering_engine #16238
- [x] repaint #16239
- [x] replay_attack #16240
- [x] repo #16242
- [x] reporting_directive #16243
- [x] representation_header #16244
- [x] request_header #15487
- [x] resource_timing #16245
- [x] response_header #15487
- [x] responsive_web_design #16246
- [x] rest #15487
- [x] rgb #16254
- [x] ril #16255
- [x] rng #16257
- [x] robots.txt #16258
- [x] round_trip_time #16259
- [x] routers #15487
- [x] rss #15487
- [x] rsync #16260
- [x] rtcp #16261
- [x] rtf #16262
- [x] rtl #16263
- [x] rtp #16264
- [x] rtsp #16265
- [x] ruby #16266
```
