### ISSUE TITLE
ko: update `web/glossary-t`

### ISSUE THREAD

**Issue by IMHOJEONG** [mdn/translated-content#15265]
```[tasklist]
### Tasks
- [x] table_grid_box #16368
- [x] table_wrapper_box #16369
- [x] tag #15376
- [x] tcp #15376
- [x] tcp_handshake #16371
- [x] tcp_slow_start #16373
- [x] telnet #16374
- [x] texel #16375
- [x] thread #16383
- [x] three_js #16384
- [x] time_to_first_byte #16385
- [x] time_to_interactive #16386
- [x] tld #16387
- [x] tls #15376
- [x] tofu #16389
- [x] top_layer #16391
- [x] transient_activation #16396
- [x] tree_shaking #16110
- [x] trident #16401
- [x] truthy #15376
- [x] ttl #16402
- [x] turn #16403
- [x] type #16404
- [x] type_coercion #16405
- [x] type_conversion #15376
```

**Comment by IMHOJEONG** [comment]
@ykss 님 안녕하세요!
업데이트 목록에 추가하겠습니다~
