### ISSUE TITLE
ko: update `web/http/headers`

### ISSUE THREAD

**Issue by IMHOJEONG** [mdn/translated-content#15436]
### TodoList

`web/http/headers`을 추적하기 위한 이슈입니다.

```[tasklist]
### Tasks
- [ ] accept
- [ ] accept-ch
- [ ] accept-ch-lifetime
- [ ] accept-charset
- [ ] accept-encoding
- [ ] accept-language
- [ ] accept-patch
- [ ] accept-post
- [ ] accept-ranges
- [ ] access-control-allow-credentials
- [ ] access-control-allow-headers
- [ ] access-control-allow-methods
- [ ] access-control-allow-origin
- [ ] access-control-expose-headers
- [ ] access-control-max-age
- [ ] access-control-request-headers
- [ ] access-control-request-method
- [ ] age
- [ ] allow
- [ ] alt-svc
- [ ] alt-used
- [ ] authorization
- [ ] cache-control
- [ ] clear-site-data
- [ ] connection
- [ ] content-disposition
- [ ] content-dpr
- [ ] content-encoding
- [ ] content-language
- [ ] content-length
- [ ] content-location
- [ ] content-range
- [ ] content-security-policy
- [ ] content-security-policy-report-only
- [ ] content-type
- [ ] cookie
- [ ] critical-ch
- [ ] cross-origin-embedder-policy
- [ ] cross-origin-opener-policy
- [ ] cross-origin-resource-policy
- [ ] date
- [ ] device-memory
- [ ] digest
- [ ] dnt
- [ ] downlink
- [ ] dpr
- [ ] early-data
- [ ] ect
- [ ] etag
- [ ] expect
- [ ] expect-ct
- [ ] expires
- [ ] forwarded
- [ ] from
- [ ] host
- [ ] if-match
- [ ] if-modified-since
- [ ] if-none-match
- [ ] if-range
- [ ] if-unmodified-since
- [ ] index.md
- [ ] keep-alive
- [ ] large-allocation
- [ ] last-modified
- [ ] link
- [ ] location
- [ ] max-forwards
- [ ] nel
- [ ] origin
- [ ] permissions-policy
- [ ] pragma
- [ ] proxy-authenticate
- [ ] proxy-authorization
- [ ] range
- [ ] referer
- [ ] referrer-policy
- [ ] retry-after
- [ ] rtt
- [ ] save-data
- [ ] sec-ch-prefers-reduced-motion
- [ ] sec-ch-prefers-reduced-transparency
- [ ] sec-ch-ua
- [ ] sec-ch-ua-arch
- [ ] sec-ch-ua-bitness
- [ ] sec-ch-ua-full-version
- [ ] sec-ch-ua-full-version-list
- [ ] sec-ch-ua-mobile
- [ ] sec-ch-ua-model
- [ ] sec-ch-ua-platform
- [ ] sec-ch-ua-platform-version
- [ ] sec-fetch-dest
- [ ] sec-fetch-mode
- [ ] sec-fetch-site
- [ ] sec-fetch-user
- [ ] sec-gpc
- [ ] sec-purpose
- [ ] sec-websocket-accept
- [ ] server
- [ ] server-timing
- [ ] service-worker-navigation-preload
- [ ] set-cookie
- [ ] sourcemap
- [ ] strict-transport-security
- [ ] te
- [ ] timing-allow-origin
- [ ] tk
- [ ] trailer
- [ ] transfer-encoding
- [ ] upgrade
- [ ] upgrade-insecure-requests
- [ ] user-agent
- [ ] vary
- [ ] via
- [ ] viewport-width
- [ ] want-digest
- [ ] warning
- [ ] width
- [ ] www-authenticate
- [ ] x-content-type-options
- [ ] x-dns-prefetch-control
- [ ] x-forwarded-for
- [ ] x-forwarded-host
- [ ] x-forwarded-proto
- [ ] x-frame-options
- [ ] x-xss-protection
```

**Comment by SnowMarble** [comment]
`alt-svc` PR 입니다. #15586

**Comment by IMHOJEONG** [comment]
@SnowMarble 님 안녕하세요.
넵 최신화해두겠습니다. 감사합니다.

**Comment by tkddls23** [comment]
`If-Unmodified-Since` PR(open) 입니다 #16539 
`If-None-Match` PR(open) 입니다 #16532
