### ISSUE TITLE
ko: update `web/http/basic_of_http`

### ISSUE THREAD

**Issue by IMHOJEONG** [mdn/translated-content#15435]
### TodoList

`web/http/basic_of_http`을 추적하기 위한 이슈입니다.

```[tasklist]
### Tasks
- [x] choosing_between_www_and_non-www_urls #15595
- [x] data_urls #15596
- [x] evolution_of_http #15678
- [x] identifying_resources_on_the_web #15707
- [x] index.md #15708
- [x] mime_types #15726
- [x] resource_urls #15727
```
