### ISSUE TITLE
zh-cn: translation plan for the pwa CycleTracker tutorial

### ISSUE THREAD

**Issue by hanyujie2002** [mdn/translated-content#15548]
I plan to init the translation of the PWA CycleTracker tutorail section. Anyone is welcome to contribute. If you find any issues with the Simplified Chinese PWA CycleTracker tutorail section or have already submitted a PR, please mention me so that I can add your work to the progress list below:

 * [x]  overview, in https://github.com/mdn/translated-content/pull/15563
 * [x]  HTML_and_CSS, in https://github.com/mdn/translated-content/pull/15665
 * [x]  Secure_connection, in #15811 
 * [x]  JavaScript_functionality, in #15748
 * [x]  Manifest and iconography, in #15890
 * [x]  service worker, in #15936

This issue is copy from [this one](https://github.com/mdn/translated-content/issues/15403)

**Comment by yin1999** [comment]
All the tasks are done. Thank you @hanyujie2002

**Comment by hanyujie2002** [comment]
Thank you @BSPR0002
