### ISSUE TITLE
zh-CN: Proofreading and update plan for the JavaScript `Number` section

### ISSUE THREAD

**Issue by JasonLamv-t** [mdn/translated-content#15736]
I plan to proofread and update the translation of the Javascript.Number section. Anyone is welcome to contribute. If you find any issues with the Simplified Chinese Number section or have already submitted a PR, please mention me so that I can add your work to the progress list below:

- [x] overview, in #15808.
- [x] constructor, in #15860.
- [x] epsilon, in #15905.
- [x] isfinite, in #15985.
- [x] isinteger, in #16012.
- [x] isnan, in #16015.
- [x] issafeinteger, in #16040 .
- [x] max_safe_integer, in #15917.
- [x] max_value, in #15958.
- [x] min_safe_integer, #15941
- [x] min_value, in #15958.
- [x] nan, have in #15960.
- [x] negative_infinity, in #15983.
- [x] parsefloat, #16059.
- [x] parseint, #16059.
- [x] positive_infinity, in #15983.
- [x] toexponential, in #16090.
- [x] tofixed, in #16098.
- [x] tolocalestring, in #16149.
- [x] toprecision, in #16150.
- [x] tostring, in #16124.
- [x] valueof, in #16122.

**Comment by JasonLamv-t** [comment]
All related articles have been completed. Thank you very much for the help of community partners. I wish everyone a happy Mid-Autumn Festival.
