### ISSUE TITLE
zh-cn: translation plan for the web performance tutorial

### ISSUE THREAD

**Issue by hanyujie2002** [mdn/translated-content#16025]
I plan to init the translation of the rest part of web performance tutorial section. Anyone is welcome to contribute. If you find any issues with the Simplified Chinese web performance section or have already submitted a PR, please mention me so that I can add your work to the progress list below:

- [x] [Multimedia: Images](https://developer.mozilla.org/en-US/docs/Learn/Performance/Multimedia), in #16039 
- [x] [Multimedia: video](https://developer.mozilla.org/en-US/docs/Learn/Performance/video), in #16082 
- [x] [JavaScript performance optimization](https://developer.mozilla.org/en-US/docs/Learn/Performance/JavaScript), in #16517
- [x] [HTML performance optimization](https://developer.mozilla.org/en-US/docs/Learn/Performance/HTML), in #16548
- [x] [CSS performance optimization](https://developer.mozilla.org/en-US/docs/Learn/Performance/CSS), in #16650 
- [x] [Measuring performance](https://developer.mozilla.org/en-US/docs/Learn/Performance/Measuring_performance), in #16654
- [x] [The business case for web performance](https://developer.mozilla.org/en-US/docs/Learn/Performance/business_case_for_performance), in #16655

**Comment by hanyujie2002** [comment]
All tasks done. 🎉 Thank you very much, I can't do it without your help ❤ @jasonren0403 @yin1999
