### ISSUE TITLE
fr: Translate the CycleTracker tutorial

### ISSUE THREAD

**Issue by SphinxKnight** [mdn/translated-content#16137]
I'm opening this issue to track the work needed to translate https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps/Tutorials/CycleTracker in French. 

```[tasklist]
### Tasks
- [x] Translation of the landing page Web/Progressive_web_apps/Tutorials/CycleTracker #16158
- [x] Translation of Web/Progressive_web_apps/Tutorials/CycleTracker/HTML_and_CSS #16227
- [x] Translation of Web/Progressive_web_apps/Tutorials/CycleTracker/JavaScript_functionality #16727
- [x] Translation of Web/Progressive_web_apps/Tutorials/CycleTracker/Manifest_file #16766
- [x] Translation of Web/Progressive_web_apps/Tutorials/CycleTracker/Secure_connection #16773
- [x] Translation of Web/Progressive_web_apps/Tutorials/CycleTracker/Service_workers #16681
- [x] Translation of Web/Progressive_web_apps/Tutorials landing page #16346
- [x] Update Web/Progressive_web_apps/Tutorials #16447
```

**Comment by tristantheb** [comment]
**Note pour sphinx** Je me ferai un branche ce week-end pour la relecture de l'existant et je ferai une PR pour le dernier item de la liste dès que les pages sont revues ;)
