### ISSUE TITLE
fr: Translate the PushManager interface

### ISSUE THREAD

**Issue by tristantheb** [mdn/translated-content#16448]
Following the rewriting and updating of issue #16137, the PushManager API, mentioned in the translated pages, is completely absent from the French version.

If you'd like to help make this interface available in French, here are the pages to translate.

```[tasklist]
### Pages to localize
- [x] `/Web/API/PushManager` #16450
- [x] `/Web/API/PushManager/getSubscription` #16450
- [ ] `/Web/API/PushManager/hasPermission`
- [x] `/Web/API/PushManager/permissionState` #16450
- [ ] `/Web/API/PushManager/register`
- [ ] `/Web/API/PushManager/registrations`
- [x] `/Web/API/PushManager/subscribe` #16450
- [ ] `/Web/API/PushManager/unregister`
- [x] `/Web/API/PushManager/supportedContentEncodings` #16450
```

**Comment by SphinxKnight** [comment]
@tristantheb à voir si on garde ça ouvert vu que le reste est en deprecated. Pas sûr que ça soit motivant pour une good-first-issue :)

**Comment by tristantheb** [comment]
@SphinxKnight yep, c'est ce que je me dis aussi, vu que ça sera supprimé plus tard, on a moins le besoin de traduire ces pages ^^
