### ISSUE TITLE
ko: update `learn/html/howto`

### ISSUE THREAD

**Issue by IMHOJEONG** [mdn/translated-content#16559]
```[tasklist]
### Tasks
- [ ] add_a_hit_map_on_top_of_an_image
- [ ] author_fast-loading_html_pages
- [ ] define_terms_with_html
- [ ] index.md
- [ ] use_data_attributes
- [ ] use_javascript_within_a_webpage
```
