### ISSUE TITLE
zh-cn: translation plan for the MathML tutorial

### ISSUE THREAD

**Issue by hanyujie2002** [mdn/translated-content#16668]
I plan to init the translation of the MathML tutorial section. Anyone is welcome to contribute. If you find any issues with the Simplified Chinese MathML section or have already submitted a PR, please mention me so that I can add your work to the progress list below:

- [x] [MathML — Writing mathematics with MathML](https://developer.mozilla.org/en-US/docs/Learn/MathML), in #16669 
- [x] [MathML first steps overview](https://developer.mozilla.org/en-US/docs/Learn/MathML/First_steps), in #16670 
- [x] [Getting started with MathML](https://developer.mozilla.org/en-US/docs/Learn/MathML/First_steps/Getting_started), in #16671
- [x] [Three famous mathematical formulas](https://developer.mozilla.org/en-US/docs/Learn/MathML/First_steps/Three_famous_mathematical_formulas), #16684 
- [x] [Text containers](https://developer.mozilla.org/en-US/docs/Learn/MathML/First_steps/Text_containers), in #16756 
- [x] [Fractions and roots](https://developer.mozilla.org/en-US/docs/Learn/MathML/First_steps/Fractions_and_roots), in #16836 
- [x] [Scripts](https://developer.mozilla.org/en-US/docs/Learn/MathML/First_steps/Scripts), in #16887
- [x] [Tables](https://developer.mozilla.org/en-US/docs/Learn/MathML/First_steps/Tables), in #16963

**Comment by yin1999** [comment]
All the documents have been updated/added. Thank you @hanyujie2002 :tada:
