### ISSUE TITLE
zh-cn: init the translation of svelte learning tutorial section

### ISSUE THREAD

**Issue by hanyujie2002** [mdn/translated-content#16965]
I plan to init the translation of the svelte tutorial section. Anyone is welcome to contribute. If you find any issues with the Simplified Chinese svelte section or have already submitted a PR, please mention me so that I can add your work to the progress list below:

- [x] [Getting started with Svelte](https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Client-side_JavaScript_frameworks/Svelte_getting_started), in #17078 
- [x] [Starting our Svelte to-do list app](https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Client-side_JavaScript_frameworks/Svelte_Todo_list_beginning), in #17107 
- [x] [Dynamic behavior in Svelte: working with variables and props](https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Client-side_JavaScript_frameworks/Svelte_variables_props), in #17363 
- [x] [Componentizing our Svelte app](https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Client-side_JavaScript_frameworks/Svelte_components), in #17501 
- [x] [Advanced Svelte: Reactivity, lifecycle, accessibility](https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Client-side_JavaScript_frameworks/Svelte_reactivity_lifecycle_accessibility), in #17745 
- [x] [Working with Svelte stores](https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Client-side_JavaScript_frameworks/Svelte_stores) in #17974 
- [x] [TypeScript support in Svelte](https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Client-side_JavaScript_frameworks/Svelte_TypeScript) in #18276 
- [x] [Deployment and next steps](https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Client-side_JavaScript_frameworks/Svelte_deployment_next) in #18302

**Comment by yin1999** [comment]
All the tasks are finished. Thanks for the contribution @hanyujie2002 :+1:
