### ISSUE TITLE
[zh-cn]: init translation for Badging API

### ISSUE THREAD

**Issue by skyclouds2001** [mdn/translated-content#17837]
```[tasklist]
### Tasks
- [x] [Badging API](https://developer.mozilla.org/en-US/docs/Web/API/Badging_API) in #18075
- [x] [Navigator.clearAppBadge()](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/clearAppBadge) in #18088
- [x] [Navigator.setAppBadge()](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/setAppBadge) in #18087
- [x] [WorkerNavigator.clearAppBadge()](https://developer.mozilla.org/en-US/docs/Web/API/WorkerNavigator/clearAppBadge) in #18097
- [x] [WorkerNavigator.setAppBadge()](https://developer.mozilla.org/en-US/docs/Web/API/WorkerNavigator/setAppBadge) in #18097
```
