### ISSUE TITLE
[zh-cn]: sync & add translation for Notification API

### ISSUE THREAD

**Issue by skyclouds2001** [mdn/translated-content#18099]
### What information was incorrect, unhelpful, or incomplete?

```[tasklist]
### Notifications API Translation Tasks
- [x] [Notifications API](https://developer.mozilla.org/en-US/docs/Web/API/Notifications_API) summary, in #18180
- [x] [Using the Notifications API](https://developer.mozilla.org/en-US/docs/Web/API/Notifications_API/Using_the_Notifications_API) guide, in #18180
- [x] [Notification](https://developer.mozilla.org/en-US/docs/Web/API/Notification) interface, in #18121
- [x] [Notification()](https://developer.mozilla.org/en-US/docs/Web/API/Notification/Notification) constructor, in #18123 , #18210
- [x] [Notification](https://developer.mozilla.org/en-US/docs/Web/API/Notification) members [a-c], in #18138
- [x] [Notification](https://developer.mozilla.org/en-US/docs/Web/API/Notification) members [d-i], in #18139
- [x] [Notification](https://developer.mozilla.org/en-US/docs/Web/API/Notification) members [l-r], in #18147
- [x] [Notification](https://developer.mozilla.org/en-US/docs/Web/API/Notification) members [s-z], in #18148
- [x] [NotificationEvent](https://developer.mozilla.org/en-US/docs/Web/API/NotificationEvent) interface, in #18151
- [x] [NotificationEvent()](https://developer.mozilla.org/en-US/docs/Web/API/NotificationEvent/NotificationEvent) constructor, in #18174
- [x] [NotificationEvent.notification](https://developer.mozilla.org/en-US/docs/Web/API/NotificationEvent/notification) property, in #18162
- [x] [NotificationEvent.action](https://developer.mozilla.org/en-US/docs/Web/API/NotificationEvent/action) property, in #18163
- [x] [ServiceWorkerRegistration.showNotification()](https://developer.mozilla.org/en-US/docs/Web/API/ServiceWorkerRegistration/showNotification) method, in #18189
- [x] [ServiceWorkerRegistration.getNotifications()](https://developer.mozilla.org/en-US/docs/Web/API/ServiceWorkerRegistration/getNotifications) method, in #18188
- [x] [ServiceWorkerGlobalScope: notificationclose](https://developer.mozilla.org/en-US/docs/Web/API/ServiceWorkerGlobalScope/notificationclose_event) event, in #18186
- [x] [ServiceWorkerGlobalScope: notificationclick](https://developer.mozilla.org/en-US/docs/Web/API/ServiceWorkerGlobalScope/notificationclick_event) event, in #18187
```
