### ISSUE TITLE
zh-cn: proofreading and update html Multimedia and embedding section 

### ISSUE THREAD

**Issue by hanyujie2002** [mdn/translated-content#18313]
I plan to proofread and update the translation of [Multimedia and embedding](https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding) section
```[tasklist]
### Tasks
- [x] Multimedia and embedding #18314
- [x] Images in HTML in #18812
- [x] Video and audio content in #19210
- [x] From object to iframe — other embedding technologies in #19569
- [x] Adding vector graphics to the web in #19617
- [x] Responsive images in #19746
- [x] Mozilla splash page in #19919
```

**Comment by hanyujie2002** [comment]
All tasks done. Thank you very much ❤ @yin1999 @jasonren0403
