### ISSUE TITLE
fr: remove the {{DOMAttributeMethods}} macros

### ISSUE THREAD

**Issue by quentin-rey** [mdn/translated-content#19044]
**Related issues/discussions:**

Related to: 
- https://github.com/orgs/mdn/discussions/638
> **Additions:**
> "See also" sections listing complementary methods
> 
> **Removals:**
> {{DOMAttributeMethods}} table

- #19009 
> The [{{DOMAttributeMethods}} macro has been deprecated](https://github.com/mdn/yari/blob/a21d7024f3e28922a43336af52bd289903c7a6d6/kumascript/macros/DOMAttributeMethods.ejs#L3) and should be removed from this repo

```[tasklist]
### Tasks
- [x] files/fr/web/api/element/hasattribute/index.md
- [x] files/fr/web/api/element/setattributens/index.md
- [x] files/fr/web/api/element/setattributenode/index.md
- [x] files/fr/web/api/element/getattributenode/index.md
- [x] files/fr/web/api/element/hasattributens/index.md
- [x] files/fr/web/api/element/getattributens/index.md
- [x] files/fr/web/api/element/removeattributenode/index.md
- [x] files/fr/web/api/element/setattributenodens/index.md
- [x] files/fr/web/api/element/getattributenodens/index.md
- [x] files/fr/web/api/element/removeattributens/index.md
- [x] files/fr/web/api/element/removeattribute/index.md
- [x] files/fr/web/api/element/setattribute/index.md
```

**Comment by quentin-rey** [comment]
**Note:** Most pages require an in-depth update.
