### ISSUE TITLE
[zh-cn]: add & sync translation for Network Information API

### ISSUE THREAD

**Issue by skyclouds2001** [mdn/translated-content#19080]
```[tasklist]
### Network Information API translation plans
- [x] [Network Information API](https://developer.mozilla.org/en-US/docs/Web/API/Network_Information_API), in #19169
- [x] [Navigator.connection](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/connection), in #19100
- [x] [WorkerNavigator.connection](https://developer.mozilla.org/en-US/docs/Web/API/WorkerNavigator/connection), in #19100
- [x] [NetworkInformation](https://developer.mozilla.org/en-US/docs/Web/API/NetworkInformation), in #19101
- [x] [NetworkInformation.downlink](https://developer.mozilla.org/zh-CN/docs/Web/API/NetworkInformation/downlink), in #19188
- [x] [NetworkInformation.downlinkMax](https://developer.mozilla.org/en-US/docs/Web/API/NetworkInformation/downlinkMax), in #19189
- [x] [NetworkInformation.effectiveType](https://developer.mozilla.org/en-US/docs/Web/API/NetworkInformation/effectiveType), in #19190
- [x] [NetworkInformation.rtt](https://developer.mozilla.org/zh-CN/docs/Web/API/NetworkInformation/rtt), in #19191
- [x] [NetworkInformation.saveData](https://developer.mozilla.org/zh-CN/docs/Web/API/NetworkInformation/saveData), in #19192
- [x] [NetworkInformation.type](https://developer.mozilla.org/en-US/docs/Web/API/NetworkInformation/type), in #19193
- [x] [NetworkInformation.change](https://developer.mozilla.org/en-US/docs/Web/API/NetworkInformation/change_event), in #19170
```
