### ISSUE TITLE
l10n-zh: remove https://mdn.mozillademos.org references

### ISSUE THREAD

**Issue by yin1999** [mdn/translated-content#19088]
Related issues: #10400. The references to `https://mdn.mozillademos.org` (in the current context: path starts with `\/files\/\d+`) are broken now, we need to remove all of those.

regex pattern to search the reference: `\/files\/\d+`

```[tasklist]
### zh-CN
- [ ] #20135
- [ ] #20071
- [ ] #19648
- [ ] #20118
- [x] files/zh-cn/web/css/padding-bottom/index.md #19886
- [x] files/zh-cn/web/css/padding-top/index.md #19886
- [ ] #19626
- [ ] #19342
- [ ] #19186
- [ ] #19114
- [ ] #19089
```

```[tasklist]
### zh-TW
- [x] files/zh-tw/web/api/canvas_api/tutorial/applying_styles_and_colors/index.md #19120
- [x] files/zh-tw/web/api/canvas_api/tutorial/basic_animations/index.md #19120
- [x] files/zh-tw/web/api/setinterval/index.md #19120
- [x] files/zh-tw/web/css/_colon_target/index.md #19120
- [x] files/zh-tw/web/css/css_flexible_box_layout/basic_concepts_of_flexbox/index.md #19120
- [x] files/zh-tw/web/css/shorthand_properties/index.md #19120
- [x] files/zh-tw/web/security/mixed_content/index.md #19120
```

**Comment by jasonren0403** [comment]
Keep open until #20135 is merged
