### ISSUE TITLE
[zh-cn]: add translation for User-Agent Client Hints API

### ISSUE THREAD

**Issue by skyclouds2001** [mdn/translated-content#19168]
User-Agent Client Hints API - 用户代理客户端提示 API

```[tasklist]
### User-Agent Client Hints API translation plans
- [x] [User-Agent Client Hints API](https://developer.mozilla.org/en-US/docs/Web/API/User-Agent_Client_Hints_API), in #19245
- [x] [Navigator.userAgentData](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/userAgentData), in #19198
- [x] [WorkerNavigator.userAgentData](https://developer.mozilla.org/en-US/docs/Web/API/WorkerNavigator/userAgentData), in #19198
- [x] [NavigatorUAData](https://developer.mozilla.org/en-US/docs/Web/API/NavigatorUAData), in #19402
- [x] [NavigatorUAData.brands](https://developer.mozilla.org/en-US/docs/Web/API/NavigatorUAData/brands), in #19447
- [x] [NavigatorUAData.mobile](https://developer.mozilla.org/en-US/docs/Web/API/NavigatorUAData/mobile), in #19448
- [x] [NavigatorUAData.platform](https://developer.mozilla.org/en-US/docs/Web/API/NavigatorUAData/platform), in #19452
- [x] [NavigatorUAData.getHighEntropyValues()](https://developer.mozilla.org/en-US/docs/Web/API/NavigatorUAData/getHighEntropyValues), in #19511
- [x] [NavigatorUAData.toJSON()](https://developer.mozilla.org/en-US/docs/Web/API/NavigatorUAData/toJSON), in #19484
```
