### ISSUE TITLE
[zh-cn]: add & update translation for Web Share API & Vibrate API

### ISSUE THREAD

**Issue by skyclouds2001** [mdn/translated-content#19537]
- Web Share API | Web 分享 API
- Vibration API | 振动 API

```[tasklist]
### Tasks
- [x] [Web Share API](https://developer.mozilla.org/en-US/docs/Web/API/Web_Share_API), in #19628
- [x] [Navigator.canShare()](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/canShare), in #19609
- [x] [Navigator.share()](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/share), in #19610
- [x] [Vibration API](https://developer.mozilla.org/en-US/docs/Web/API/Vibration_API), in #19629
- [x] [Navigator.vibrate()](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/vibrate), in #19574
```
