### ISSUE TITLE
[zh-cn]: proofread and update `web/mathml`

### ISSUE THREAD

**Issue by tianyeeT** [mdn/translated-content#20746]
### MDN URL

https://developer.mozilla.org/zh-CN/docs/Web/MathML

### What information was incorrect, unhelpful, or incomplete?

Things need to be updated: the **task** below

### What did you expect to see?

Update the existing and add the missing.

```[tasklist]
### Tasks
- [ ] https://github.com/mdn/translated-content/pull/20823
- [ ] https://github.com/mdn/translated-content/pull/20825
- [x] element/maction
- [ ] https://github.com/mdn/translated-content/pull/20841
- [ ] https://github.com/mdn/translated-content/pull/20842
- [ ] https://github.com/mdn/translated-content/pull/20843
- [ ] https://github.com/mdn/translated-content/pull/20844
- [ ] https://github.com/mdn/translated-content/pull/20845
- [ ] https://github.com/mdn/translated-content/pull/20846
- [ ] https://github.com/mdn/translated-content/pull/20847
- [ ] https://github.com/mdn/translated-content/pull/20848
- [ ] https://github.com/mdn/translated-content/pull/20850
- [ ] https://github.com/mdn/translated-content/pull/20851
- [ ] https://github.com/mdn/translated-content/pull/20852
- [ ] https://github.com/mdn/translated-content/pull/20853
- [ ] https://github.com/mdn/translated-content/pull/20854
- [ ] https://github.com/mdn/translated-content/pull/20855
- [ ] https://github.com/mdn/translated-content/pull/20856
- [x] element/mspace
- [ ] https://github.com/mdn/translated-content/pull/20857
- [ ] https://github.com/mdn/translated-content/pull/20858
- [ ] https://github.com/mdn/translated-content/pull/20859
- [ ] https://github.com/mdn/translated-content/pull/20860
- [ ] https://github.com/mdn/translated-content/pull/20861
- [ ] https://github.com/mdn/translated-content/pull/20862
- [ ] https://github.com/mdn/translated-content/pull/20863
- [ ] https://github.com/mdn/translated-content/pull/20864
- [ ] https://github.com/mdn/translated-content/pull/20865
- [ ] https://github.com/mdn/translated-content/pull/20866
- [ ] https://github.com/mdn/translated-content/pull/20867
- [ ] https://github.com/mdn/translated-content/pull/20868
- [ ] https://github.com/mdn/translated-content/pull/20870
- [ ] https://github.com/mdn/translated-content/pull/20871
- [ ] https://github.com/mdn/translated-content/pull/20872
- [ ] https://github.com/mdn/translated-content/pull/20873
- [ ] https://github.com/mdn/translated-content/pull/20839
- [ ] https://github.com/mdn/translated-content/pull/20875
- [ ] https://github.com/mdn/translated-content/pull/20876
- [ ] https://github.com/mdn/translated-content/pull/20877
- [ ] https://github.com/mdn/translated-content/pull/20878
- [ ] https://github.com/mdn/translated-content/pull/20879
- [ ] https://github.com/mdn/translated-content/pull/20880
- [ ] https://github.com/mdn/translated-content/pull/20881
- [ ] https://github.com/mdn/translated-content/pull/20874
- [ ] https://github.com/mdn/translated-content/pull/20840
- [ ] https://github.com/mdn/translated-content/pull/20882
```
