### ISSUE TITLE
[zh-cn]: create and update the translation of articles under "WebExtensions/API/cookies"

### ISSUE THREAD

**Issue by tianyeeT** [mdn/translated-content#20967]
### MDN URL

https://developer.mozilla.org/zh-CN/docs/Mozilla/Add-ons/WebExtensions/API/cookies

### What information was incorrect, unhelpful, or incomplete?

Let's synchronize the content for 'WebExtensions/API/cookies'.

### What did you expect to see?

Keep pace with upstream.

```[tasklist]
### Tasks
- [ ] https://github.com/mdn/translated-content/pull/20982
- [ ] https://github.com/mdn/translated-content/pull/20988
- [ ] https://github.com/mdn/translated-content/pull/20989
- [ ] https://github.com/mdn/translated-content/pull/21047
- [ ] https://github.com/mdn/translated-content/pull/21048
- [ ] https://github.com/mdn/translated-content/pull/21049
- [ ] https://github.com/mdn/translated-content/pull/21051
- [ ] https://github.com/mdn/translated-content/pull/21060
- [ ] https://github.com/mdn/translated-content/pull/21061
- [ ] https://github.com/mdn/translated-content/pull/21062
- [ ] https://github.com/mdn/translated-content/pull/21063
```
