### ISSUE TITLE
[zh-cn]: create and update the translation of articles under "WebExtensions/API/tabs"

### ISSUE THREAD

**Issue by tianyeeT** [mdn/translated-content#21825]
### MDN URL

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs

### What information was incorrect, unhelpful, or incomplete?

Let's synchronize the content for "WebExtensions/API/tabs"

### What did you expect to see?

Keep pace with upstream.

```[tasklist]
### Tasks
- [ ] https://github.com/mdn/translated-content/pull/21777
- [ ] https://github.com/mdn/translated-content/pull/21778
- [ ] https://github.com/mdn/translated-content/pull/21779
- [ ] https://github.com/mdn/translated-content/pull/21780
- [ ] https://github.com/mdn/translated-content/pull/21781
- [ ] https://github.com/mdn/translated-content/pull/21782
- [ ] https://github.com/mdn/translated-content/pull/21783
- [ ] https://github.com/mdn/translated-content/pull/21784
- [ ] https://github.com/mdn/translated-content/pull/21785
- [ ] https://github.com/mdn/translated-content/pull/21786
- [ ] https://github.com/mdn/translated-content/pull/21787
- [ ] https://github.com/mdn/translated-content/pull/21788
- [ ] https://github.com/mdn/translated-content/pull/21789
- [ ] https://github.com/mdn/translated-content/pull/21790
- [ ] https://github.com/mdn/translated-content/pull/21791
- [ ] https://github.com/mdn/translated-content/pull/21792
- [ ] https://github.com/mdn/translated-content/pull/21793
- [ ] https://github.com/mdn/translated-content/pull/21794
- [ ] https://github.com/mdn/translated-content/pull/21795
- [ ] https://github.com/mdn/translated-content/pull/21796
- [ ] https://github.com/mdn/translated-content/pull/21797
- [ ] https://github.com/mdn/translated-content/pull/21801
- [ ] https://github.com/mdn/translated-content/pull/21802
- [ ] https://github.com/mdn/translated-content/pull/21803
- [ ] https://github.com/mdn/translated-content/pull/21804
- [ ] https://github.com/mdn/translated-content/pull/21805
- [ ] https://github.com/mdn/translated-content/pull/21806
- [ ] https://github.com/mdn/translated-content/pull/21807
- [ ] https://github.com/mdn/translated-content/pull/21808
- [ ] https://github.com/mdn/translated-content/pull/21815
- [ ] https://github.com/mdn/translated-content/pull/21816
- [ ] https://github.com/mdn/translated-content/pull/21817
- [ ] https://github.com/mdn/translated-content/pull/21822
- [ ] https://github.com/mdn/translated-content/pull/21823
- [ ] https://github.com/mdn/translated-content/pull/21824
- [ ] https://github.com/mdn/translated-content/pull/21827
- [ ] https://github.com/mdn/translated-content/pull/21828
- [ ] https://github.com/mdn/translated-content/pull/21829
- [ ] https://github.com/mdn/translated-content/pull/21830
- [ ] https://github.com/mdn/translated-content/pull/21831
- [ ] https://github.com/mdn/translated-content/pull/21846
- [ ] https://github.com/mdn/translated-content/pull/21847
- [ ] https://github.com/mdn/translated-content/pull/21857
- [ ] https://github.com/mdn/translated-content/pull/21858
- [ ] https://github.com/mdn/translated-content/pull/21859
- [ ] https://github.com/mdn/translated-content/pull/21861
- [ ] https://github.com/mdn/translated-content/pull/21864
- [ ] https://github.com/mdn/translated-content/pull/21865
- [ ] https://github.com/mdn/translated-content/pull/21866
- [ ] https://github.com/mdn/translated-content/pull/21868
- [ ] https://github.com/mdn/translated-content/pull/21869
- [ ] https://github.com/mdn/translated-content/pull/21886
- [ ] https://github.com/mdn/translated-content/pull/21887
- [ ] https://github.com/mdn/translated-content/pull/21888
- [ ] https://github.com/mdn/translated-content/pull/21889
- [ ] https://github.com/mdn/translated-content/pull/21890
- [ ] https://github.com/mdn/translated-content/pull/21891
- [ ] https://github.com/mdn/translated-content/pull/21892
- [ ] https://github.com/mdn/translated-content/pull/21893
```

**Comment by jasonren0403** [comment]
After checking, I think the issue has resolved.

Thanks for your work! 👍
