### ISSUE TITLE
[zh-cn]: create and update the translation of articles under "WebExtensions/API/themes" 

### ISSUE THREAD

**Issue by tianyeeT** [mdn/translated-content#21898]
### MDN URL

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/theme

### What information was incorrect, unhelpful, or incomplete?

Let's synchronize the content for "WebExtensions/API/themes" 

### What did you expect to see?

Keep pace with upstream.

```[tasklist]
### Tasks
- [ ] https://github.com/mdn/translated-content/pull/21899
- [ ] https://github.com/mdn/translated-content/pull/21900
- [ ] https://github.com/mdn/translated-content/pull/21901
- [ ] https://github.com/mdn/translated-content/pull/21902
- [ ] https://github.com/mdn/translated-content/pull/21903
- [ ] https://github.com/mdn/translated-content/pull/21904
```
