### ISSUE TITLE
[ko] l10n-ko locale RoadMap, 2021

### ISSUE THREAD

**Issue by hochan222** [mdn/translated-content#2476]
ko locale의 점진적인 발전을 위해, 앞으로의 계획들을 같이 생각해보기 위해서 해당 이슈를 생성했습니다. 

아래 사항외에도 수정되거나 추가해야할 사항이 있으면 알려주세요. (많은 아이디어를 주세요!) :)

## 한국 가이드 문서 개정 v2

지난 4개월간 [가이드라인](https://github.com/mdn/translated-content/blob/main/docs/ko/translation-guide.md)을 완성하면서, 단어의 일관성을 위해 단어집도 같이 제작되었습니다. 카테고리를 조금 더 세분화해서, 지정된 단어를 조금 더 쉽게 습득하고, 혼동이 될 만한 단어/안내사항들을 가이드로 지정하고자 합니다. 가이드에 없지만 혼동이 될 만한 단어나 추가할 사항들은 댓글로 알려주시거나 PR 주세요 :)

- [x] https://github.com/mdn/translated-content/issues/1631
- [x] 가이드라인 개정 https://github.com/mdn/translated-content/pull/2747
- [ ] https://github.com/mdn/translated-content/issues/3139 

### 번역

아직 ko locale에 번역되지 않은 문서들이 많으며, 번역된 문서들 조차 최신화가 이뤄지지 않은 문서들이 상당히 많습니다. 또한, 최근에 html에서 md로의 문서 변환이 이뤄지고 있습니다. 점진적인 문서 품질 개선을 위해 효율적인 번역이 이뤄질 수 있는 방법을 생각해보아야 합니다.

- **효율적인 번역 방안**
- **html to md**
  - [x] https://github.com/mdn/translated-content/issues/2894
- **문서 번역**
  - [x] [[ko] ⭐6월 해결 과제 ( learn/javascript 최신화 )⭐](https://github.com/mdn/translated-content/issues/1042)

### 현황판

무엇을 기여해야할지 모르겠다면 현황판으로 시작할 수 있습니다. Level 0, Level 1, Level 2 MDN의 이해도에 맞게 이슈를 처리해보세요!

- [x] [현황판](https://github.com/mdn/translated-content/projects/2)

<img src="https://user-images.githubusercontent.com/22424891/139229803-04e39b2b-46f2-4df6-8fec-a9de0cd621c9.png" height="300px" />

## 운영

지속적인 운영을 위해, yari-content-ko 팀을 유지하기 위한 방안을 생각해야합니다. 우선은, 이후 미래의 yari-content-ko 팀을 위한 가이드 작성 및 과거 yari-content-ko 팀을 위한 hall of fame을 만들 예정입니다. 또한, MDN translated-content 관련 소식을 전달할 방법을 생각해보아야합니다.

- [x] **yari-content-ko 리뷰어 전용 가이드 작성하기** https://github.com/mdn/translated-content/pull/2525
- [x] **hall of fame** https://github.com/mdn/translated-content/pull/2525
- [ ] **MDN translated-content 관련 소식 전달**
