### ISSUE TITLE
[ko] Markdown convertion for ko RoadMap

### ISSUE THREAD

**Issue by hochan222** [mdn/translated-content#2894]
## 목적

markdown으로 변환하기 위한 사항들을 정리하기 위한 이슈입니다. 해당 이슈는 [Converting an MDN section to Markdown - Localizer's guide](https://github.com/mdn/translated-content/discussions/2474)의 ko-locale 을 위한 이슈입니다.

  - Markdown으로 변환
  - 문서를 HTML에서 Markdown으로 변환하는 PR에서는 다음 두 커밋 포함한다. 
    - (1) 파일 이름 바꾸기
    - (2) 실제로 파일 변환

## 변환 방법

> 2022.08 기준 html을 markdown으로 변환하는 script가 [yari](https://github.com/mdn/yari)에서 분리되었습니다. ([markdown script repo](https://github.com/mdn/markdown) 링크)

공식 가이드: https://hacks.mozilla.org/2022/09/the-100-percent-markdown-expedition/

- 참고
  - https://github.com/mdn/markdown/blob/main/conversion-guide.md
  - https://github.com/mdn/translated-content/discussions/2474
  - https://egas.tistory.com/52?category=482046

### 확장자 일괄 변환

```
find -L . -type f -name "*.html" -print0 | while IFS= read -r -d '' FNAME; do
    mv -- "$FNAME" "${FNAME%.html}.md"
done
```

## 진행 목록

`web/javascript` 폴더를 시작으로 점진적으로 변환해 나갈 예정입니다. 

- [x] conflicting https://github.com/mdn/translated-content/issues/7622
- [x] games https://github.com/mdn/translated-content/issues/7623
- [x] glossary https://github.com/mdn/translated-content/issues/7624
- [x] learn https://github.com/mdn/translated-content/issues/7625
- [x] mdn https://github.com/mdn/translated-content/pull/7579
- [x] mozilla https://github.com/mdn/translated-content/issues/7626
- [x] web https://github.com/mdn/translated-content/issues/7621
- [x] webassembly https://github.com/mdn/translated-content/pull/7581

## 변환전 체크 사항

> 2022.08 기준 코드에서 체크사항들을 모두 처리해주고 있어서 더 이상 아래 작업이 불필요합니다.

### web/javascript

- Remove "cruft" from the past: this is especially true for (sadly) unmaintained areas of some localized docs.
  - [x] #2898
  - [x] #2897
  - [x] #2896
- [x] Remove id attributes when they don't belong to a heading (`<h1>/<h2>` etc.)
  - Be careful with live samples (EmbedLiveSample macro calls) when converting
- [x] #2899
- [x] #2895
- [x] Remove inline style attributes which won't be converted

### [기울임꼴](https://github.com/mdn/translated-content/blob/main/docs/ko/translation-guide.md#%EA%B8%B0%EC%9A%B8%EC%9E%84%EA%BC%B4)

한글은 기울임꼴에 적합하지 않습니다. 한국 문서에서는 사용하고 있지 않아 `_기울임꼴_` 은 `기울임꼴` 이나 `**기울임꼴**`으로 변환합니다.

### 명세서 

앞으로 명세서는 아래 두가지 형식만 존재합니다.

- html
```
<h2 id="Specifications">명세서</h2>

{{Specifications}}
```

- markdown
```
## 명세서

{{Specifications}}
```

### 브라우저 호환성

- html
```
<h2 id="Browser_compatibility">브라우저 호환성</h2>

{{Compat}}
```

- markdown
```
## 명세서

{{Compat}}
```

**Comment by kraccoon-dev** [comment]
안녕하세요, 마지막 체크사항에대해 궁금한점이 있어 질문드립니다.
#2474 에서 언급된 바로는 변환되지 않을 인라인 스타일 속성을 제거해고 했는데, 여기서 _변환되지 않을 인라인 스타일_ 은 어떤걸 말하는 걸까요?
> Remove inline style attributes which won't be converted

**Comment by hochan222** [comment]
> 안녕하세요, 마지막 체크사항에대해 궁금한점이 있어 질문드립니다. https://github.com/mdn/translated-content/discussions/2474 에서 언급된 바로는 변환되지 않을 인라인 스타일 속성을 제거해고 했는데, 여기서 변환되지 않을 인라인 스타일 은 어떤걸 말하는 걸까요?

@kraccoon-dev 님, 안녕하세요. yari의 html파일을 md 파일로 변환하는 명령어로 변환이 안되는 태그들이 있습니다. 예를 들면 [span](https://github.com/mdn/translated-content/pull/2570/commits/b732592c13587951a36d7b1f183b0bb64d496483)이 있습니다. 

현재 어떤 태그들이 대상인지는 저도 잘 모르겠지만, 우선은 https://github.com/mdn/translated-content/pull/2307 를 참고해 보셔도 좋을 듯 합니다 :)

**Comment by kraccoon-dev** [comment]
@hochan222 확인해주셔서 감사합니다! 자료를 조금 더 찾아보고 정리가 된다면 진행해보도록 하겠습니다.

**Comment by queengooborg** [comment]
Hey all -- FYI, I've written a new conversion guide at https://github.com/mdn/markdown/blob/main/conversion-guide.md with updated instructions, as many of the special cases that had to be taken care of before conversion are now automatically handled!  Hope this helps with your locale's conversion!

**Comment by hochan222** [comment]
@queengooborg I was going to read it thoroughly today. Oh, Everything is already taken care of! Thanks for letting me know before work :)

**Comment by hochan222** [comment]
모든 문서 변환 완료되었습니다! 모두 고생 많으셨습니다. 🎉🎉
 
좋은 하루 보내세요 :)
