### ISSUE TITLE
Meta - Tracking remaining work for Markdown conversion - French

### ISSUE THREAD

**Issue by SphinxKnight** [mdn/translated-content#3012]
This issue is intended to track the remaining work for Markdown conversion:

Out of scope:
 - Orphaned
 - Conflicting
 - Tools (as per English)

Sections:

Checks after conversion:
- [x] Check for remaining HTML file in converted section (which can happen when a file has been moved in mdn/content from a non migrated section to a migrated section) #3112 #3113
  - `/fr/web/index.html`
  - `/fr/web/api/node/baseuri/index.html`
  - `/fr/web/css/media_queries/using_media_queries/index.html`
  - `/fr/web/javascript/reference/global_objects/string/index.html`
  -  [x] PWA #3103 #3104
    - `/fr/web/progressive_web_apps/index.html`
    - `/fr/web/progressive_web_apps/add_to_home_screen/index.html`
    - `/fr/web/progressive_web_apps/app_structure/index.html`
    - `/fr/web/progressive_web_apps/installable_pwas/index.html`
    - `/fr/web/progressive_web_apps/introduction/index.html`
    - `/fr/web/progressive_web_apps/loading/index.html`
    - `/fr/web/progressive_web_apps/offline_service_workers/index.html`
    - `/fr/web/progressive_web_apps/re-engageable_notifications_push/index.html`
    - `/fr/web/progressive_web_apps/responsive/responsive_design_building_blocks/index.html`
- [x] Check for errors in EmbedLiveSample across all pages (as conversion may delete english ids used in the macro call)
  - #3115

Already completed:
- web/api (#2464 #2588)
- web/css (#2307 #2490)
- web/html (#2628 #2716)
- web/http (#2453 #2489)
- web/javascript (#1574 #1835)
- web/svg (#2570 #2934)
- [x] Plugins
  - [`files/fr/plugins`](https://github.com/mdn/translated-content/tree/main/files/fr/plugins)
  - [x] Preparation #3010
  - [x] Conversion #3055
- [x] Accessibility
  - [`files/fr/web/accessibility`](https://github.com/mdn/translated-content/tree/main/files/fr/web/accessibility)
  - [x] Preparation #2975
  - [x] Conversion #3056
- [x] Demos
  - [`files/fr/web/demos`](https://github.com/mdn/translated-content/tree/main/files/fr/web/demos)
  - [x] Preparation #3013
  - [x] Conversion #3057
- [x] Events
  - [`files/fr/web/events`](https://github.com/mdn/translated-content/tree/main/files/fr/web/events)
  - [x] Preparation #3014
  - [x] Conversion #3058
- [x] EXSLT
  - [`files/fr/web/exslt`](https://github.com/mdn/translated-content/tree/main/files/fr/web/exslt)
  - [x] Preparation #3016
  - [x] Conversion #3059
- [x] Guide
  - [`files/fr/web/guide`](https://github.com/mdn/translated-content/tree/main/files/fr/web/guide)
  - [x] Preparation #3018
  - [x] Conversion #3060
- [x] Manifest
  - [`files/fr/web/manifest`](https://github.com/mdn/translated-content/tree/main/files/fr/web/manifest)
  - [x] Preparation #3019
  - [x] Conversion #3061
- [x] MathML
  - [`files/fr/web/mathml`](https://github.com/mdn/translated-content/tree/main/files/fr/web/mathml)
  - [x] Preparation #3020
  - [x] Conversion #3062
- [x] Media
  - [`files/fr/web/media`](https://github.com/mdn/translated-content/tree/main/files/fr/web/media)
  - [x] Preparation #3021
  - [x] Conversion #3063
- [x] Performance
  - [`files/fr/web/performance`](https://github.com/mdn/translated-content/tree/main/files/fr/web/performance)
  - [x] Preparation #3022
  - [x] Conversion #3064
- [x] Privacy
  - [`files/fr/web/privacy`](https://github.com/mdn/translated-content/tree/main/files/fr/web/privacy)
  - [x] Preparation #3023
  - [x] Conversion #3065
- [x] Security
  - [`files/fr/web/security`](https://github.com/mdn/translated-content/tree/main/files/fr/web/security)
  - [x] Preparation #3024
  - [x] Conversion #3066
- [x] Tutorials
  - [`files/fr/web/tutorials`](https://github.com/mdn/translated-content/tree/main/files/fr/web/tutorials)
  - [x] Preparation: Nothing to do
  - [x] Conversion #3052
- [x] Web Components
  - [`files/fr/web/web_components`](https://github.com/mdn/translated-content/tree/main/files/fr/web/web_components)
  - [x] Preparation #3025
  - [x] Conversion #3067
- [x] XML
  - [`files/fr/web/xml`](https://github.com/mdn/translated-content/tree/main/files/fr/web/xml)
  - [x] Preparation #3026
  - [x] Conversion #3068
- [x] XPath
  - [`files/fr/web/xpath`](https://github.com/mdn/translated-content/tree/main/files/fr/web/xpath)
  - [x] Preparation #3027
  - [x] Conversion #3069
- [x] XSLT
  - [`files/fr/web/xslt`](https://github.com/mdn/translated-content/tree/main/files/fr/web/xslt)
  - [x] Preparation #3028
  - [x] Conversion #3070
- [x] WebAssembly
  - [`files/fr/web/assembly`](https://github.com/mdn/translated-content/tree/main/files/fr/webassembly)
  - [x] Preparation #2978
  - [x] Conversion #3053
- [x] Games
   - [`files/fr/games`](https://github.com/mdn/translated-content/tree/main/files/fr/games)
   - [x] Preparation #3006
   - [x] Conversion #3054
- [x] MDN
  - [`files/fr/mdn`](https://github.com/mdn/translated-content/tree/main/files/fr/mdn)
  - [x] Preparation #3008
  - [x] Conversion #3049
- [x] Learning Area
  - [`files/fr/learn`](https://github.com/mdn/translated-content/tree/main/files/fr/learn)
  - [x] Preparation #2738
  - [x] Conversion #3088
- [x] Glossary
   - [`files/fr/glossary`](https://github.com/mdn/translated-content/tree/main/files/fr/glossary)
   - [x] Preparation #2971
   - [x] Conversion #3101
- [x] Mozilla
  - [`files/fr/mozilla`](https://github.com/mdn/translated-content/tree/main/files/fr/mozilla)
  - [x] Preparation #2980
  - [x] Conversion #3102

**Comment by SphinxKnight** [comment]
![image](https://user-images.githubusercontent.com/2413436/141854980-79278ed4-4f59-4cde-b3ed-b9004fe83eb6.png)
as of tonight

**Comment by SphinxKnight** [comment]
![image](https://user-images.githubusercontent.com/2413436/141935157-10802f6d-7184-4470-b188-4afaf1a4076a.png)
