### ISSUE TITLE
"mdn.mozillademos.org/files" links on French pages

### ISSUE THREAD

**Issue by cw118** [mdn/translated-content#3566]
Not sure if this would be a priority, but there are still quite a few external image sources on French pages — there are 651 results of deprecated `mdn.mozillademos.org/files` URLs in 167 files so far. Seeing as these were removed from the en-US files, I feel it would make sense to do the same for the locales?

- [ ] 47 results in 22 files in "conflicting" (may be done later)
- [ ] 5 results in 4 files in "orphaned" (may be done later)
- [x] 5 results in 3 files in "learn" (dealt with in #3498)
- [x] 477 results in 83 files in "tools" (dealt with  in #4841)
- [x] 116 results in 54 files in "web"
  - [x] 7 results in 6 files in "web/javascript" (dealt with in #3570)
  - [x] 106 results in 46 files in "web/css" #3642
  - [x] 2 results in 1 file in "web/api" (dealt with in #3627)
  - [x] 1 result in 1 file in "web/web_components" (dealt with in #3627)

None were found in other French folders. N.B. Many of these URLs are found in `EmbedLiveSample`s, so image files may have to be added as well; for some of the pages, it may be easier to update/revise the entire file vs. en-US as noted in #3496 and #3497.

**Comment by SphinxKnight** [comment]
@cw118 thanks for this! 
As for conflicting and orphaned, I'd be enclined to leave them as is. (orphaned has pages where the English page has been (re)moved and the French page is then moved in this folder to await for proper deletion or treatment 
 conflicting is used when an English page is moved to another location (a planned task then move the localized page accordingly) but for some reason (mainly how the previous platform used to behave) the target destination already has a page.

In other words, conflicting and orphaned are a stack of pages which need "special" handling and which are not (to me) as important as the rest of the content.

If I were to sort those, I'd say:

1. Web
2. Learn
3. Tools (I'm putting this one as third since it mainly documents Firefox Tools and it was decided not to move this in Markdown)
4. "Maybe later": conflicting / orphaned

Having this categorization is super helpful as it allows to make a PR for each section which is clearly easier to review.

**Comment by SphinxKnight** [comment]
N.B. as of f360338, I'm only finding 116 results for 54 files under /web (using VS Code search for "mdn.mozillademos.org")

**Comment by cw118** [comment]
Thanks so much for looking into this! I'm also getting the same search result now and have updated the issue. I'd be happy to continue the work on this as well :)

**Comment by SphinxKnight** [comment]
@cw118 @tristantheb, since Tools has been removed, I think we can close this one.
The rest is (to me) another motivation to detail a plan about what to do for orphaned/conflicting.

**Comment by cw118** [comment]
Closing 👍
