### ISSUE TITLE
{{page}} macro removal for French pages - Web/JavaScript

### ISSUE THREAD

**Issue by SphinxKnight** [mdn/translated-content#3884]
Fragment of #3881 in order to remove `{{page}}` calls from pages.
There are 44 pages under Web/JavaScript:

- [x] `web/javascript/data_structures/index.md`(#4921)
- [x] `web/javascript/guide/indexed_collections/index.md` (#3570)
- [x] `web/javascript/reference/index.md` (#4922)
- [x] `web/javascript/reference/global_objects/arraybuffer/index.md` (#5048)
- [x] `web/javascript/reference/global_objects/asyncfunction/index.md` (#5049)
- [x] `web/javascript/reference/global_objects/bigint/index.md` (#5133)
- [x] `web/javascript/reference/global_objects/boolean/index.md` (#5202)
- [x] `web/javascript/reference/global_objects/dataview/index.md` (#5203)
- [x] `web/javascript/reference/global_objects/date/tolocaledatestring/index.md` (#4151)
- [x] `web/javascript/reference/global_objects/date/tolocalestring/index.md` (#4151)
- [x] `web/javascript/reference/global_objects/error/index.md` (#5234)
- [x] `web/javascript/reference/global_objects/evalerror/index.md`(#5254)
- [x] `web/javascript/reference/global_objects/function/index.md` (#5255)
- [x] `web/javascript/reference/global_objects/generatorfunction/index.md` (#5256)
- [x] `web/javascript/reference/global_objects/internalerror/index.md` (#5258)
- [x] `web/javascript/reference/global_objects/intl/collator/index.md` (#5260)
- [x] `web/javascript/reference/global_objects/intl/datetimeformat/index.md` (#5261)
- [x] `web/javascript/reference/global_objects/intl/datetimeformat/formatrange/index.md` (#5262)
- [x] `web/javascript/reference/global_objects/intl/listformat/index.md` (#5264)
- [x] `web/javascript/reference/global_objects/intl/numberformat/index.md` (#5266)
- [x] `web/javascript/reference/global_objects/intl/pluralrules/index.md` (#5267)
- [x] `web/javascript/reference/global_objects/intl/relativetimeformat/index.md` (#5268)
- [x] `web/javascript/reference/global_objects/map/index.md` (#5276)
- [x] `web/javascript/reference/global_objects/number/tolocalestring/index.md` (#5277)
- [x] `web/javascript/reference/global_objects/object/index.md` (#5279)
- [x] `web/javascript/reference/global_objects/promise/index.md` (done in #3570)
- [x] `web/javascript/reference/global_objects/proxy/index.md` (#5282)
- [x] `web/javascript/reference/global_objects/proxy/revocable/index.md` (#5284)
- [x] `web/javascript/reference/global_objects/referenceerror/index.md` (#5285)
- [x] `web/javascript/reference/global_objects/regexp/index.md` (#5286)
- [x] `web/javascript/reference/global_objects/set/index.md` (#5287)
- [x] `web/javascript/reference/global_objects/sharedarraybuffer/index.md` (#5288)
- [x] `web/javascript/reference/global_objects/string/localecompare/index.md` (#5291)
- [x] `web/javascript/reference/global_objects/symbol/index.md` (#5298)
- [x] `web/javascript/reference/global_objects/syntaxerror/index.md` (#5299)
- [x] `web/javascript/reference/global_objects/typedarray/index.md` (#5304)
- [x] `web/javascript/reference/global_objects/typedarray/tolocalestring/index.md` (#5305)
- [x] `web/javascript/reference/global_objects/typeerror/index.md` (#5306)
- [x] `web/javascript/reference/global_objects/urierror/index.md` (#4386)
- [x] `web/javascript/reference/global_objects/weakset/index.md` (#5308)
- [ ] `web/javascript/reference/global_objects/webassembly/global/index.md` (#5309)
- [x] `web/javascript/reference/global_objects/webassembly/instance/index.md` (#5310)
- [x] `web/javascript/reference/global_objects/webassembly/module/index.md` (#5311)
- [x] `web/javascript/typed_arrays/index.md` (#3570)
