### ISSUE TITLE
 {{page}} macro removal for French pages - Misc.

### ISSUE THREAD

**Issue by SphinxKnight** [mdn/translated-content#3886]
Fragment of #3881 in order to remove `{{page}}` calls from pages.
There are 10 pages (after tools removal) in various sections:

- [x] glossary/denial_of_service/index.md (dealt with #4058)
- [x] glossary/second-level_domain/index.md (dealt with #4058)
- [x] ~learn/server-side/django/generic_views/index.md~ false positive with Django template in the content
- [x] web/css/@media/index.md (#5238)
- [x] web/css/css_transforms/using_css_transforms/index.md (#5239)
- [x] web/css/max-block-size/index.md (#5240)
- [x] web/svg/attribute/accent-height/index.md (#5241)
- [x] web/svg/attribute/height/index.md (#5245)
- [x] web/svg/attribute/width/index.md (#5252)
- [x] web/svg/attribute/x/index.md (#5253)

**Comment by cw118** [comment]
Done after #5253 🎉
