### ISSUE TITLE
{{page}} macro calls on Spanish pages | 25 pages in Web/API: [es]

### ISSUE THREAD

**Issue by JuanVqz** [mdn/translated-content#3927]
@mdn/yari-content-es  podriamos asignar por página en lugar de que una persona haga todas (por que si esta pesado).

Hola, todo mundo es bienvenido para traducir una o más paginas, solo por favor,
1. comenta en este issue que página deseas traducir tomando como base la versión  en inglés y te la asignaremos,
2. una vez concluido abre un PR, y cuando se apruebe,
3. chequearemos la página como hecha. saludos!

- [x] 1. [/es/docs/web/api/battery_status_api](https://developer.mozilla.org/es/docs/web/api/battery_status_api) - [[en-US](https://developer.mozilla.org/en-US/docs/web/api/battery_status_api)] @Vallejoanderson
- [x] 2. [/es/docs/web/api/batterymanager](https://developer.mozilla.org/es/docs/web/api/batterymanager) - [[en-US](https://developer.mozilla.org/en-US/docs/web/api/batterymanager)] @diego-go
- [x] 3. [/es/docs/web/api/batterymanager/charging](https://developer.mozilla.org/es/docs/web/api/batterymanager/charging) - [[en-US](https://developer.mozilla.org/en-US/docs/web/api/batterymanager/charging)] @Vallejoanderson
- [x] #3982
- [x] 5. [/es/docs/web/api/batterymanager/dischargingtime](https://developer.mozilla.org/es/docs/web/api/batterymanager/dischargingtime) - [[en-US](https://developer.mozilla.org/en-US/docs/web/api/batterymanager/dischargingtime)] @JuanVqz
- [x] 6. [/es/docs/web/api/batterymanager/level](https://developer.mozilla.org/es/docs/web/api/batterymanager/level) - [[en-US](https://developer.mozilla.org/en-US/docs/web/api/batterymanager/level)] @JuanVqz
- [x] 7. [/es/docs/web/api/batterymanager/onchargingchange](https://developer.mozilla.org/es/docs/web/api/batterymanager/onchargingchange) - [[en-US](https://developer.mozilla.org/en-US/docs/web/api/batterymanager/onchargingchange)] @Vallejoanderson
- [x] #4019 @JuanVqz 
- [x] 9. [/es/docs/web/api/customevent](https://developer.mozilla.org/es/docs/web/api/customevent) - [[en-US](https://developer.mozilla.org/en-US/docs/web/api/customevent)] @diego-go (in progress)
- [x] #4160
- [x] #3979 @sergiogval 
- [x] #4077 @Vallejoanderson
- [x] #3994 @sergiogval 
- [x] #4021
- [x] #4059 @Vallejoanderson
- [x] #3980 @sergiogval 
- [x] #4157
- [x] 18. [/es/docs/web/api/notification/body](https://developer.mozilla.org/es/docs/web/api/notification/body) - [[en-US](https://developer.mozilla.org/en-US/docs/web/api/notification/body)] @davbrito (#3989) 
- [x] #4003
- [x] #3995
- [x] #4023 @Vallejoanderson 
- [x] #4030 @Vallejoanderson
- [x] #4035 @Vallejoanderson  (In progress)
- [x] #4068 @Graywolf9 
- [x] #4057 @JuanVqz (In progress)

https://github.com/mdn/translated-content/issues/3898 es el issue principal y esté issue es 1/3

**Comment by davbrito** [comment]
Hola. Voy a tomar la 18. /es/docs/web/api/notification/body

**Comment by Vallejoanderson** [comment]
Voy con el 1.

**Comment by Vallejoanderson** [comment]
Voy con el 3. /es/docs/web/api/batterymanager/charging

**Comment by JuanVqz** [comment]
I'll pick number 4th.

**Comment by Vallejoanderson** [comment]
Voy con el 7.

**Comment by sergiogval** [comment]
Me asigné dos temas y les abrí un issue. Es realmente fácil usando la UI. Literal en dos clicks. Uno para el checkbox del contenido a traducir y otro para abrir el issue. Duda, estoy traduciendo un contenido, @JuanVqz, ¿cómo puedo ponerlo en ésta tabla? me gustaría integrarlo en éste control. 

- [ ] [DragEvents](https://github.com/mdn/translated-content/issues/3979)

- [ ] [geolocation_api](https://github.com/mdn/translated-content/issues/3980)

- [ ] [la que quiero integrar a la lista](https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Understanding_client-side_tools/Package_management)

Adicionalmente, me gustaría mencionar que en el html/head/title de ésta página de issues hay un bug pues muestra un llamado a un objeto ¿qué opinan? no me había tocado ver éste tipo de bugs antes.
![image](https://user-images.githubusercontent.com/67393791/152465676-e5ee59dd-af17-4fab-9558-647da37f6b9a.png)

**Comment by Vallejoanderson** [comment]
Hola @sergiogval `{{page}}` se esta colocando en el titulo para hacer referencia a que es un macro que ya no se esta usando y que esta siendo remplazado, te encontraras con el en las traducciones a realizar, en [este hilo](https://github.com/mdn/translated-content/pull/3961#discussion_r797835495) puedes ver una correccion hecha por @Graywolf9.

**Comment by JuanVqz** [comment]
> Me asigné dos temas y les abrí un issue. Es realmente fácil usando la UI. Literal en dos clicks. Uno para el checkbox del contenido a traducir y otro para abrir el issue. Duda, estoy traduciendo un contenido, @JuanVqz, ¿cómo puedo ponerlo en ésta tabla? me gustaría integrarlo en éste control. 

¿Que te parece editar la descripción del issue agregando tu nombre en el issue que elegiste y ahí mismo llevar el control de todos los puntos? ¿O por que quieres llevar el control en otra tabla? 


> Adicionalmente, me gustaría mencionar que en el html/head/title de ésta página de issues hay un bug pues muestra un llamado a un objeto ¿qué opinan? no me había tocado ver éste tipo de bugs antes.

Lo siento Sergio no captaba que title, con la explicación de Vallejo ya entendí, lo siento.

**Comment by sergiogval** [comment]
So, you guys are innovating here. Cool. Thanks for make this crystal clear to me.
 I personally believe this will mislead anyone that is concerned about security breaches and isn't aware of the agreement you have made. It instantly poped out as a bug in my mind. I'm glad  glad that is not the case.

**Comment by Vallejoanderson** [comment]
Voy con el 19. /es/docs/web/api/notification/dir. Lo he editado en el texto, no se si haya incoveniente con eso @JuanVqz, cualquier cosa me avisas ;)

**Comment by JuanVqz** [comment]
> Voy con el 19. /es/docs/web/api/notification/dir. Lo he editado en el texto, no se si haya incoveniente con eso @JuanVqz, cualquier cosa me avisas ;)

no, no hay inconveniente, para eso es.

de hecho, @mdn/yari-content-es el que haga merge de algún PR, por favor que venga a marcar el checkbox para darlo como terminado, por favor.

**Comment by Vallejoanderson** [comment]
Voy con el 21.

**Comment by Vallejoanderson** [comment]
Voy con el 22.
