### ISSUE TITLE
Tracking issue for french sidebars

### ISSUE THREAD

**Issue by cw118** [mdn/translated-content#5135]
The following sidebars may be missing translations/needing updates for the french locale:

- [x] [HTMLRef](https://github.com/mdn/yari/blob/main/kumascript/macros/HTMLRef.ejs) https://github.com/mdn/translated-content/pull/9665
- [x] [JSRef](https://github.com/mdn/yari/blob/main/kumascript/macros/JSRef.ejs) looks like it's built upon https://github.com/mdn/content/tree/main/files/jsondata which has been updated recently in https://github.com/mdn/translated-content/issues/8749 (done for `fr`)
- [x] [CSSRef](https://github.com/mdn/yari/blob/main/kumascript/macros/CSSRef.ejs) (https://github.com/mdn/yari/pull/6213, will need an update after mdn/yari#6053)
- [x] [AddonSidebar](https://github.com/mdn/yari/blob/main/kumascript/macros/AddonSidebar.ejs) (https://github.com/mdn/yari/pull/6213)
- [x] [AddonSidebarMain](https://github.com/mdn/yari/blob/main/kumascript/macros/AddonSidebarMain.ejs) (seems up-to-date, apart from a minor uppercase letter which may be lowered…)
- [x] [CanvasSidebar](https://github.com/mdn/yari/blob/main/kumascript/macros/CanvasSidebar.ejs) (https://github.com/mdn/yari/pull/6213)
- [x] [DefaultAPISidebar](https://github.com/mdn/yari/blob/main/kumascript/macros/DefaultAPISidebar.ejs) looks like it's built upon https://github.com/mdn/content/tree/main/files/jsondata which has been updated recently in https://github.com/mdn/translated-content/issues/8749 (done for `fr`)
- [x] [FirefoxSidebar](https://github.com/mdn/yari/blob/main/kumascript/macros/FirefoxSidebar.ejs) (done with mdn/yari#5680)
- [x] [GamesSidebar](https://github.com/mdn/yari/blob/main/kumascript/macros/GamesSidebar.ejs) (only a typo in https://github.com/mdn/yari/pull/6213)
- [x] [HTMLSidebar](https://github.com/mdn/yari/blob/main/kumascript/macros/HTMLSidebar.ejs) (https://github.com/mdn/yari/pull/6213)
- [x] [HTTPSidebar](https://github.com/mdn/yari/blob/main/kumascript/macros/HTTPSidebar.ejs) (https://github.com/mdn/yari/pull/6213)
- [x] [JsSidebar](https://github.com/mdn/yari/blob/main/kumascript/macros/JsSidebar.ejs) (https://github.com/mdn/yari/pull/6213)
- [x] [LearnSidebar](https://github.com/mdn/yari/blob/main/kumascript/macros/LearnSidebar.ejs) (https://github.com/mdn/yari/pull/7848)
- [x] [MDNSidebar](https://github.com/mdn/yari/blob/main/kumascript/macros/MDNSidebar.ejs) (https://github.com/mdn/yari/pull/6213)
- [x] [ServiceWorkerSidebar](https://github.com/mdn/yari/blob/main/kumascript/macros/ServiceWorkerSidebar.ejs) (https://github.com/mdn/yari/pull/6213)
- [x] ~[ToolsSidebar](https://github.com/mdn/yari/blob/main/kumascript/macros/ToolsSidebar.ejs) (Tools is no longer on MDN)~
- [x] [WebAssemblySidebar](https://github.com/mdn/yari/blob/main/kumascript/macros/WebAssemblySidebar.ejs) (https://github.com/mdn/yari/pull/6213)
- [x] [WebExtAPISidebar](https://github.com/mdn/yari/blob/main/kumascript/macros/WebExtAPISidebar.ejs) (seems generic enough, relies on https://github.com/mdn/content/blob/main/files/jsondata/L10n-Common.json)
- [x] [WebGLSidebar](https://github.com/mdn/yari/blob/main/kumascript/macros/WebGLSidebar.ejs) (https://github.com/mdn/yari/pull/6213)
- [x] [WebRTCSidebar](https://github.com/mdn/yari/blob/main/kumascript/macros/WebRTCSidebar.ejs) (https://github.com/mdn/yari/pull/6213)

**Comment by SphinxKnight** [comment]
see https://github.com/mdn/yari/issues/7394

**Comment by SphinxKnight** [comment]
Il serait temps de finir ça avant Noël 👀 💪 je m'y remets

**Comment by SphinxKnight** [comment]
let's close this one :)
