### ISSUE TITLE
[ko] Tracking issue for Korean sidebars

### ISSUE THREAD

**Issue by hochan222** [mdn/translated-content#5494]
https://github.com/mdn/yari/pull/5828 PR에서 언급된 LearnSidebar 에 대해 `ko-locale` 부분이 존재하지 않습니다. 

The following sidebars may be missing translations/needing updates/needing checks for the korean locale:

- [ ] [HTMLRef](https://github.com/mdn/yari/blob/main/kumascript/macros/HTMLRef.ejs)
- [ ] [JSRef](https://github.com/mdn/yari/blob/main/kumascript/macros/JSRef.ejs)
- [ ] [CSSRef](https://github.com/mdn/yari/blob/main/kumascript/macros/CSSRef.ejs)
- [ ] [AddonSidebar](https://github.com/mdn/yari/blob/main/kumascript/macros/AddonSidebar.ejs)
- [ ] [AddonSidebarMain](https://github.com/mdn/yari/blob/main/kumascript/macros/AddonSidebarMain.ejs)
- [ ] [CanvasSidebar](https://github.com/mdn/yari/blob/main/kumascript/macros/CanvasSidebar.ejs)
- [ ] [DefaultAPISidebar](https://github.com/mdn/yari/blob/main/kumascript/macros/DefaultAPISidebar.ejs)
- [ ] [FirefoxSidebar](https://github.com/mdn/yari/blob/main/kumascript/macros/FirefoxSidebar.ejs) 
- [ ] [GamesSidebar](https://github.com/mdn/yari/blob/main/kumascript/macros/GamesSidebar.ejs)
- [ ] [HTMLSidebar](https://github.com/mdn/yari/blob/main/kumascript/macros/HTMLSidebar.ejs)
- [ ] [HTTPSidebar](https://github.com/mdn/yari/blob/main/kumascript/macros/HTTPSidebar.ejs)
- [ ] [JsSidebar](https://github.com/mdn/yari/blob/main/kumascript/macros/JsSidebar.ejs)
- [ ] [MDNSidebar](https://github.com/mdn/yari/blob/main/kumascript/macros/MDNSidebar.ejs)
- [ ] [LearnSidebar](https://github.com/mdn/yari/blob/main/kumascript/macros/LearnSidebar.ejs) 
- [ ] [ServiceWorkerSidebar](https://github.com/mdn/yari/blob/main/kumascript/macros/ServiceWorkerSidebar.ejs)
- [ ] [ToolsSidebar](https://github.com/mdn/yari/blob/main/kumascript/macros/ToolsSidebar.ejs) 
- [ ] [WebAssemblySidebar](https://github.com/mdn/yari/blob/main/kumascript/macros/WebAssemblySidebar.ejs)
- [ ] [WebExtAPISidebar](https://github.com/mdn/yari/blob/main/kumascript/macros/WebExtAPISidebar.ejs)
- [ ] [WebGLSidebar](https://github.com/mdn/yari/blob/main/kumascript/macros/WebGLSidebar.ejs)
- [ ] [WebRTCSidebar](https://github.com/mdn/yari/blob/main/kumascript/macros/WebRTCSidebar.ejs)

**Comment by coding-Alice** [comment]
Yari > kumascript > macros 번역전 현황 (2022.11.17일 기준)

- [x] [AddonSidebar](https://github.com/mdn/yari/blob/main/kumascript/macros/AddonSidebar.ejs)
- [x] [AddonSidebarMain](https://github.com/mdn/yari/blob/main/kumascript/macros/AddonSidebarMain.ejs)
- [ ] [AvailableInWorkers](https://github.com/mdn/yari/blob/main/kumascript/macros/AvailableInWorkers.ejs)
- [ ] [bug](https://github.com/mdn/yari/blob/main/kumascript/macros/bug.ejs)
- [x] [CanvasSidebar](https://github.com/mdn/yari/blob/main/kumascript/macros/CanvasSidebar.ejs)
- [ ] [CompatGeckoDesktop](https://github.com/mdn/yari/blob/main/kumascript/macros/CompatGeckoDesktop.ejs)
- [ ] [CompatibilityTable](https://github.com/mdn/yari/blob/main/kumascript/macros/CompatibilityTable.ejs)
- [ ] [CompatUnknown](https://github.com/mdn/yari/blob/main/kumascript/macros/CompatUnknown.ejs)
- [ ] [CompatVersionUnknown](https://github.com/mdn/yari/blob/main/kumascript/macros/CompatVersionUnknown.ejs)
- [ ] [CSS_key_concepts](https://github.com/mdn/yari/blob/main/kumascript/macros/CSS_key_concepts.ejs)
- [ ] [CSSRef](https://github.com/mdn/yari/blob/main/kumascript/macros/CSSRef.ejs)
- [ ] [DeprecatedBadge](https://github.com/mdn/yari/blob/main/kumascript/macros/DeprecatedBadge.ejs)
- [x] [DeprecatedGeneric](https://github.com/mdn/yari/blob/main/kumascript/macros/DeprecatedGeneric.ejs)
- [ ] [DOMAttributeMethods](https://github.com/mdn/yari/blob/main/kumascript/macros/DOMAttributeMethods.ejs)
- [x] [EmbedGHLiveSample](https://github.com/mdn/yari/blob/main/kumascript/macros/EmbedGHLiveSample.ejs)
- [x] [EmbedInteractiveExample](https://github.com/mdn/yari/blob/main/kumascript/macros/EmbedInteractiveExample.ejs)
- [x] [ExperimentalBadge](https://github.com/mdn/yari/blob/main/kumascript/macros/ExperimentalBadge.ejs)
- [ ] [Firefox_for_developers](https://github.com/mdn/yari/blob/main/kumascript/macros/Firefox_for_developers.ejs)
- [ ] [FirefoxSidebar](https://github.com/mdn/yari/blob/main/kumascript/macros/FirefoxSidebar.ejs)
- [x] [GamesSidebar](https://github.com/mdn/yari/blob/main/kumascript/macros/GamesSidebar.ejs)
- [ ] [GlossaryList](https://github.com/mdn/yari/blob/main/kumascript/macros/GlossaryList.ejs)
- [ ] [HTMLRefTable](https://github.com/mdn/yari/blob/main/kumascript/macros/HTMLRefTable.ejs)
- [ ] [HTMLSidebar](https://github.com/mdn/yari/blob/main/kumascript/macros/HTMLSidebar.ejs)
- [x] [HTTP Sidebar](https://github.com/mdn/yari/blob/main/kumascript/macros/HTTPSidebar.ejs)
- [ ] [js_property_attributes](https://github.com/mdn/yari/blob/main/kumascript/macros/js_property_attributes.ejs)
- [ ] [jsOverrides](https://github.com/mdn/yari/blob/main/kumascript/macros/jsOverrides.ejs)
- [ ] [JsSidebar](https://github.com/mdn/yari/blob/main/kumascript/macros/JsSidebar.ejs)
- [ ] [LearnSidebar](https://github.com/mdn/yari/blob/main/kumascript/macros/LearnSidebar.ejs)
- [x] [ListSubpagesForSidebar](https://github.com/mdn/yari/blob/main/kumascript/macros/ListSubpagesForSidebar.ejs)
- [ ] [MathMLElement](https://github.com/mdn/yari/blob/main/kumascript/macros/MathMLElement.ejs)
- [ ] [MathMLRef](https://github.com/mdn/yari/blob/main/kumascript/macros/MathMLRef.ejs)
- [ ] [MDNSidebar](https://github.com/mdn/yari/blob/main/kumascript/macros/MDNSidebar.ejs)
- [ ] [no_tag_omission](https://github.com/mdn/yari/blob/main/kumascript/macros/no_tag_omission.ejs)
- [ ] [Non-standardGeneric](https://github.com/mdn/yari/blob/main/kumascript/macros/Non-standardGeneric.ejs)
- [ ] [NonStandardBadge](https://github.com/mdn/yari/blob/main/kumascript/macros/NonStandardBadge.ejs)
- [x] [NoteStart](https://github.com/mdn/yari/blob/main/kumascript/macros/NoteStart.ejs)
- [ ] [ObsoleteBadge](https://github.com/mdn/yari/blob/main/kumascript/macros/ObsoleteBadge.ejs)
- [ ] [ObsoleteGeneric](https://github.com/mdn/yari/blob/main/kumascript/macros/ObsoleteGeneric.ejs)
- [ ] [optionalGeneric](https://github.com/mdn/yari/blob/main/kumascript/macros/optionalGeneric.ejs)
- [x] [PreviousMenuNext](https://github.com/mdn/yari/blob/main/kumascript/macros/PreviousMenuNext.ejs)
- [x] [PreviousNext](https://github.com/mdn/yari/blob/main/kumascript/macros/PreviousNext.ejs)
- [ ] [property_prefix](https://github.com/mdn/yari/blob/main/kumascript/macros/property_prefix.ejs)
- [ ] [ReadOnlyInline](https://github.com/mdn/yari/blob/main/kumascript/macros/ReadOnlyInline.ejs)
- [ ] [SectionOnPage](https://github.com/mdn/yari/blob/main/kumascript/macros/SectionOnPage.ejs)
- [ ] [secureContextGeneric](https://github.com/mdn/yari/blob/main/kumascript/macros/secureContextGeneric.ejs)
- [ ] [SeeCompatTable](https://github.com/mdn/yari/blob/main/kumascript/macros/SeeCompatTable.ejs)
- [ ] [ServiceWorkerSidebar](https://github.com/mdn/yari/blob/main/kumascript/macros/ServiceWorkerSidebar.ejs)
- [ ] [spec](https://github.com/mdn/yari/blob/main/kumascript/macros/spec.ejs)
- [ ] [spec2](https://github.com/mdn/yari/blob/main/kumascript/macros/spec2.ejs)
- [ ] [SpecName](https://github.com/mdn/yari/blob/main/kumascript/macros/SpecName.ejs)
- [ ] [SVGAttr](https://github.com/mdn/yari/blob/main/kumascript/macros/SVGAttr.ejs)
- [ ] [SVGRef](https://github.com/mdn/yari/blob/main/kumascript/macros/SVGRef.ejs)
- [ ] [unimplementedGeneric](https://github.com/mdn/yari/blob/main/kumascript/macros/unimplementedGeneric.ejs)
- [ ] [WebAssemblySidebar](https://github.com/mdn/yari/blob/main/kumascript/macros/WebAssemblySidebar.ejs)
- [ ] [WebExtAllExamples](https://github.com/mdn/yari/blob/main/kumascript/macros/WebExtAllExamples.ejs)
- [ ] [WebExtExamples](https://github.com/mdn/yari/blob/main/kumascript/macros/WebExtExamples.ejs)
- [ ] [WebGLSidebar](https://github.com/mdn/yari/blob/main/kumascript/macros/WebGLSidebar.ejs)
- [ ] [WebkitBug](https://github.com/mdn/yari/blob/main/kumascript/macros/WebkitBug.ejs)
- [ ] [WebRTCSidebar](https://github.com/mdn/yari/blob/main/kumascript/macros/WebRTCSidebar.ejs)
- [ ] [xref_csscomputed](https://github.com/mdn/yari/blob/main/kumascript/macros/xref_csscomputed.ejs)
- [x] [xref_cssinherited](https://github.com/mdn/yari/blob/main/kumascript/macros/xref_cssinherited.ejs)
- [x] [xref_cssinitial](https://github.com/mdn/yari/blob/main/kumascript/macros/xref_cssinitial.ejs)
- [ ] [xref_cssvisual](https://github.com/mdn/yari/blob/main/kumascript/macros/xref_cssvisual.ejs)
- [x] [XsltRef](https://github.com/mdn/yari/blob/main/kumascript/macros/XsltRef.ejs)

**Comment by coding-Alice** [comment]
[PR](https://github.com/mdn/yari/pull/7971) 올려뒀습니다! 제가 이번에 한가지 큰 실수를 해버렸습니다.. 다른 분들 보니깐 하나씩 해서 올리던데... 그걸 모르고 한번에 많이 번역해서 한 커밋에 올렸습니다.. 다음부터는 한 파일당 한개씩 올리겠습니다!

**Comment by hochan222** [comment]
@coding-Alice 님 안녕하세요. yari에서는 오히려 좋은것같아요! 고생 넘넘 많으셨습니다!

혹시 시간 여유가 있으시다면 추후 기여자들을 위해 [한국 번역 지침](https://github.com/mdn/translated-content/tree/main/docs/ko)에 관련 지침 추가해주셔도 좋을것같습니다. 

새해 복 많이 받으세요 :)

**Comment by hochan222** [comment]
혹시 PR에서 표기한 현황하고 차이가 있는데 어느쪽이 더 최신일까요?

**Comment by coding-Alice** [comment]
PR에 올려둔게 최신입니다! 그 사이에.. 파일들이 몇개가 삭제되었더라구요. 삭제된 파일들은 현황 목록에서 제거했습니다!

**Comment by coding-Alice** [comment]
kanban 보드 확인 해보니 제가 올린 pr merger가 된다면.. 

- [Tracking issues for Korean Sidebar](https://github.com/mdn/translated-content/projects/2#card-81632419)
- #4707 

이렇게 두 issue들이 해결될 것 같습니다! 

아 그리고 [MDN 번역 콘텐츠에 대한 일반 지침](https://github.com/mdn/translated-content/projects/2#card-71760542) 링크 업데이트 부탁드립니다!

항상 감사합니다! ㅎㅎ

**Comment by hochan222** [comment]
업데이트 했습니다! 감사합니다 좋은 하루 보내세요 :)

**Comment by hochan222** [comment]
2024.01.26v

The following sidebars may be missing translations/needing updates/needing checks for the korean locale:

- [ ] [DOMAttributeMethods](https://github.com/mdn/yari/blob/main/kumascript/macros/DOMAttributeMethods.ejs)

**Comment by hochan222** [comment]
이슈 모두 해결되어 닫겠습니다. 모두 고생 많으셨습니다.

좋은 하루 보내세요 :)
