### ISSUE TITLE
Macro removal - Meta - deprecated macros and macro arguments

### ISSUE THREAD

**Issue by SphinxKnight** [mdn/translated-content#5603]
Hello @mdn/localization-team-leads  With https://github.com/mdn/yari/pull/6252, the macros which are only used (because of legacy/history) in mdn/translated-content are marked as deprecated.

Here is a breakdown of each of them and their corresponding counts in this repo (as of `e296c15`). I hope this will make it easier for each locale's team to split the work and replace/update the pages accordingly.

Don't hesitate to ping me here or on Matrix (or to edit this directly if you have the corresponding rights) to update this list :)
N.B.

- [ ] `bug` - 745 occurrences (replace w/ `[Firefox bug $1](https://bugzil.la/$1)`)
  - [x] `es` - https://github.com/mdn/translated-content/pull/12057
  - [x] `fr` - #13605
  - [x] `ja` - All done!
  - [x] `ko` - #12007 
  - [ ] `pt-br` - 68 occurrences #14100
  - [ ] `ru` - 96 occurrences
  - [x] `zh-cn` - 1 occurrence #11892 #13257
  - [x] `zh-tw` - 39 occurrences #11893 #13257
- [x] `CanvasSidebar` - see #10516
- [ ] Arguments to `Compat` - see #11594
- [ ] `CSSAnimatedProperties` - 3 occurrences / 3 files
  - [ ] 1 file for `ja`
  - [ ] 1 file for `fr`
  - [ ] 1 file for `ko`
- [x] `CSSTutorialTOC` - 15 occurrences / 15 files
  - [x] 5 files for `de` (inactive locale) #6556
  - [x] 2 files for `es` #6557
  - [x] 1 file for `ja` #5762 
  - [x] 1 file for `ko` #5605
  - [x] 2 files for `pt-br`
  - [x] 1 file for `ru` #7340
  - [x] 3 files for `zh-cn` (#5825)
- [x] `DeprecatedGeneric` - 3 occurrences
  - [x] 1 occurrence for `es` #11585
  - [x] 2 occurrences for `ko` #11588
- [x] `DOM0` - 97 occurrences / 97 files
  - [x] 2 files for `de` (inactive locale)
  - [x] 1 file for `es` #6385
  - [x] 24 files for `fr` #5668 
  - [x] 17 files for `ja` #5770 
  - [x] 1 file for `ko` #5605
  - [x] 25 files for `pl` (inactive locale)
  - [x] 2 files for `pt-br` #8000
  - [x] 1 file for `ru` #8132
  - [x] 24 files for `zh-cn` #6419
- [x] `DiscussionList` - 50 occurrences / 50 files
  - [x] 6 files for `de` (inactive locale)
  - [x] 9 file for `es` #9608
  - [x] 5 files for `fr` (#5652 #5653)
  - [x] 1 file for `ja` #5764 
  - [x] 3 files for `ko` #5605
  - [x] 8 files for `pl` (inactive locale)
  - [x] 7 files for `pt-br`
  - [x] 3 files for `ru`
  - [x] 4 files for `zh-cn` #6030
  - [x] 4 files for `zh-tw` #6030
- [x] `EditorGuideQuicklinks` - 4 occurrences / 3 files
  - [x] 1 file for `fr` #5664
  - [x] 2 files for `zh-tw` (#6006)
- [ ] Arguments to `EmbedLiveSample` - see #5716
- [ ] `event` - 331 occurrences
  - [ ] 78 occurrences for `ko`
  - [ ] 94 occurrences for `pt-br`
  - [ ] 159 occurrences for `ru`
- [x] `fx_minversion_note` - see #11187
- [x] `gecko` - see #11284
- [x] `geckoRelease` - 93 occurrences
  - [x] 39 occurrences for `pt-br` #11681
  - [x] 54 occurrences for `ru` #11684
- [x] `GlossaryList` - 14 occurrences / 8 files
  - [x] 1 file for `de` (inactive locale)
  - [x] #9593
  - [x] 1 file for `ja` #5472
  - [x] 1 file for `ko` #5605
  - [x] 1 file for `pl` (inactive locale)
  - [x] 1 file for `pt-br`
  - [x] 1 file for `ru`
- [x] `HTML5ArticleTOC` - 2 occurrences / 2 files
  - [x] 1 occurrence for `fr` #5666 
  - [x] 1 occurrence for `zh-tw` (#5656)
- [ ]  `HTMLAttrDef` - 184 occurrences
  - [x] es - 44 files - #13719
  - [x] fr - 37 files - #13620
  - [x] ja - 76 files - #13125 
  - [ ] ko - 67 files
  - [ ] pt-br 56 files
  - [ ] ru - 61 files
- [ ] `HTMLAttrXRef` - 121 occurrences
  - [x] es - 111 files - #13665
  - [x] fr  - 141 files - #13613
  - [x] ja - 344 files - #13127
  - [ ] ko - 121 occurrences - #13662
  - [x] pt-br - 92 files - #13657
  - [x] ru - 148 files - #13658
  - [x] zh-cn - 217 files #12468
  - [x] zh-tw - 40 files #12466
- [x] `HTMLRefTable` - 8 occurrences
  - [x] es - 1 occurrence #12015
  - [x] fr - 1 occurrence #12016
  - [x] ja - 1 occurrence #11993
  - [x] ko - 1 occurrence #12017
  - [x] pt-br - 1 occurrence #12018
  - [x] ru - 1 occurrence #12019
  - [x] zh-cn - 1 occurrence #12020
  - [x] zh-tw - 1 occurrence #12021
- [x] `HTMLVersionInline` - 34 occurrences
  - [x] 20 occurrences for `pt-br` #12741
  - [x] 14 occurrences for `ru` #12638
- [ ] `Interwiki` - see #7287
- [x] `jsOverrides` - 28 occurrences / 15 files
  - [x] 1 file for `de` (inactive locale)
  - [x] 3 files for `pl` (inactive locale)
  - [x] 5 files for `pt-br` (https://github.com/mdn/translated-content/pull/10297)
  - [x] 5 files for `ru` #13242
  - [x] 1 file for `zh-tw` #6052
- [x] `mediawiki.external` - 6 occurrences
  - [x] 2 occurrences for `pt-br` #12397
  - [x] 4 occurrences for `ru` #12396
- [x] `Note` - 128 occurrences / 108 files
  - [x] 12 files for `de` (inactive locale)
  - [x] 10 files for `es`
  - [x] 23 files for `fr` #5711 
  - [x] 12 files for `ja` #5773 
  - [x] 5 files for `ko`  #5605
  - [x] 5 files for `pl` (inactive locale)
  - [x] 8 files for `pt-br` #9132
  - [x] 11 files for `ru` #9691
  - [x] 16 files for `zh-cn` #6407
  - [x] 6 files for `zh-tw` #6407
- [x] `NoteEnd` - 13 occurrences / 13 files
  - [x] 2 files for `de` (inactive locale)
  - [x] 3 files for `es`
  - [x] 1 file for `ja` #5766
  - [x] 1 file for `ko` #5605
  - [x] 2 files for `pt-br` #9132
  - [x] 1 file for `ru`
  - [x] 2 files for `zh-cn` #6011
  - [x] 1 file for `zh-tw` #6011
- [x] `NoteStart` - 13 occurrences / 13 files
  - [x] 2 files for `de` (inactive locale)
  - [x] 3 files for `es`
  - [x] 1 file for `ja` #5766
  - [x] 1 file for `ko`  #5605
  - [x] 2 files for `pt-br` #9132
  - [x] 1 file for `ru`
  - [x] 2 files for `zh-cn` #6011
  - [x] 1 file for `zh-tw` #6011
- [x] `Obsolete_Header` - 257 occurrences / 232 files
  - [x] 12 files for `de` (inactive locale)
  - [x] #9596
  - [x] 54 files for `fr` #5610 / #5611
  - [x] #6008
  - [x] 10 files for `ko`  #5605
  - [x] 2 files for `pl` (inactive locale)
  - [x] 18 files for `pt-br` #11688
  - [x] 14 files for `ru` #11689
  - [x] 43 files for `zh-cn` #6828
  - [x] 5 files for `zh-tw` #6828
- [x] `Obsolete_Inline` - 1712 occurrences / 500 files
  - [x] 34 files for `de` (inactive locale)
  - [x] 41 files for `es` #9704
  - [x] 70 files for `fr` #5631 #5634
  - [x] #6009
  - [x] 40 files for `ko` #5727
  - [x] 21 files for `pl` (inactive locale)
  - [x] 50 files for `pt-br` #11688
  - [x] 65 files for `ru` #11689
  - [x] 87 files for `zh-cn` #6803
  - [x] 33 files for `zh-tw` #6803
- [x] `ObsoleteGeneric` - 124 occurrences / 39 files
  - [x] 8 files for `de` (inactive locale)
  - [x] #9595
  - [x] 4 files for `ja` #5790 
  - [x] 3 files for `ko`
  - [x] 6 files for `pt-br`
  - [x] 3 files for `ru` #11644
  - [x] 7 files for `zh-cn` #6690
  - [x] 2 files for `zh-tw` #6690
- [ ] `{{page}}` : see #5715
- [ ] `SectionOnPage` - see #11131
- [ ] `spec` - see #11594
- [ ] `spec2` - see #11594
- [ ] `SpecName` - see #11594
- [x] `TemplateLink` - 319 occurrences / 41 files
  - [x] 5 files for `es` #9610
  - [x] 4 files for `fr` #5624
  - [x] #6007
  - [x] 4 files for `ko` #5605
  - [x] 3 files for `pt-br` #10348
  - [x] 2 files for `ru` #10348
  - [x] 5 files for `zh-cn` (#5813)
  - [x] 2 files for `zh-tw` (#5813)
- [x] `ToolsSidebar` - 178 occurrences / 178 files
  - [x] 27 files for `de` (inactive locale) #6659
  - [x] #6121
  - [x] 1 file for `pl` (inactive locale) #6659
- [x] `gecko_callout_heading` - 5 occurrences / 5 files
  - [x] #6563
  - [x] 3 files for `fr` #5621
  - [x] 1 file for `zh-tw` #6396
- [x] `languages` - 736 occurrences / 736 files
  - [x] 66 files for `de` (inactive locale)
  - [x] #6562
  - [x] 18 files for `fr` (several PRs)
  - [x] 29 files for `ja` #5821 
  - [x] 48 files for `ko` #8096
  - [x] 409 files for `pl` (inactive locale)
  - [x] 23 files for `pt-br`
  - [x] 17 files for `ru`
  - [x] 1 file for `zh-tw` (#5656)
- [x] `nextPage` - 11 occurrences / 11 files
  - [x] 5 files for `de` (inactive locale)
  - [x] 1 file for `es`
  - [x] 1 file for `fr` #5377
  - [x] 1 file for `ja`
  - [x] 1 file for `ko` #5605
  - [x] 1 file for `pt-br` #9829
  - [x] 1 file for `zh-cn` #6051
- [x] `previousPage` - 13 occurrences / 13 files
  - [x] 5 files for `de` (inactive locale)
  - [x] 2 files for `es`
  - [x] 1 file for `fr` #5377
  - [x] 1 file for `ja`
  - [x] 1 file for `ko` #5605
  - [x] 1 file for `pt-br`
  - [x] 2 files for `zh-cn` (seems not exist now)
- [x] `web.link` - 601 occurrences / 58 files
  - [x] 1 file for `de` (inactive locale)
  - [x] 48 files for `es` #9077
  - [x] 1 file for `pt-br`
  - [x] 3 files for `ru`
  - [x] 2 files for `zh-cn` #6394
  - [x] 3 files for `zh-tw` #6394
- [x] `WebkitBug` - 14 occurrences (replace w/ `[WebKit bug $1](https://webkit.org/b/$1)`)
  - [x] `es` - 2 occurrences https://github.com/mdn/translated-content/pull/11976
  - [x] `fr` - 1 occurrence #12772
  - [x] `ja` - 4 occurrences
  - [x] `ko` - 1 occurrence #11882
  - [x] `pt-br` - 2 occurrences #12770
  - [x] `ru` - 1 occurrence #12834
  - [x] `zh-cn` - 2 occurrences #11892
  - [x] `zh-tw` - 1 occurrence #11893
- [x] `wiki.localize` - 13 occurrences / 13 files
  - [x] 5 files for `es` #6476
  - [x] 4 files for `fr` #5608
  - [x] 2 files for `ja` #5765
  - [x] 1 file for `ko` #5605
  - [x] 1 file for `zh-cn` (#5812)

**Comment by schalkneethling** [comment]
Thank you so much for putting this together @SphinxKnight 🎉 

> N.B. There is the issue of `de` and `pl` which are inactive.

As @caugner mentioned in another pull request:

> Removing usages of deprecated macros from frozen locales is absolutely appreciated. 👍
> Background: We still build all locales, including frozen ones, every night. This means we can only remove deprecated macros if they are no longer used in any locale, including frozen locales.
Note: The locales that we no longer "care" about are elsewhere, e.g. [retired-content](https://github.com/mdn/retired-content) and [retired-archived-content](https://github.com/mdn/retired-archived-content).

**Comment by SphinxKnight** [comment]
> > Removing usages of deprecated macros from frozen locales is absolutely appreciated. +1
> > Background: We still build all locales, including frozen ones, every night. This means we can only remove deprecated macros if they are no longer used in any locale, including frozen locales.

Thanks, I'll take care of that with "batch"-search/replace after `fr`

**Comment by alattalatta** [comment]
All macros listed here have been removed from `ko` docs.

**Comment by SphinxKnight** [comment]
`fr` is done :)

**Comment by SphinxKnight** [comment]
seems like `ja` is clear too!

**Comment by mfuji09** [comment]
`ja` is done except `{{page}}`. It will be also done soon.

**Comment by caugner** [comment]
@SphinxKnight FYI Here's a full list of currently deprecated macros (based on [this report](https://github.com/mdn/yari/pull/7087)), some of which are missing in the list above:

- CompatChrome
- CompatGeckoDesktop
- CompatGeckoMobile
- CompatibilityTable
- CompatNo
- CompatUnknown
- CompatVersionUnknown
- CSS_key_concepts: https://github.com/mdn/translated-content/issues/7343
- DiscussionList
- event
- gecko_minversion_header
- gecko_minversion_inline
- geckoRelease
- GlossaryList
- HTMLVersionInline
- IncludeSubnav
- Interwiki: https://github.com/mdn/translated-content/issues/7287
- jsOverrides
- languages
- Link
- mediawiki.external
- nextPage
- Note
- NoteEnd
- NoteStart
- Obsolete_Header
- Obsolete_Inline
- ObsoleteGeneric
- previousPage
- property_prefix
- spec
- spec2
- SpecName
- TemplateLink
- warning
- web.link
- XULAttr
- XULElem

**Comment by SphinxKnight** [comment]
@caugner I guess I'll deal with this after markdown conversion PRs and that a milestone + one issue per macro would be a better format to track this 😅
Thanks for your tool, I need to fiddle with it :)

**Comment by schalkneethling** [comment]
@SphinxKnight this removes the final instances of `property_prefix` - https://github.com/mdn/translated-content/pull/8612

**Comment by MrBrain295** [comment]
`nextPage` got finished in #9829.

**Comment by Graywolf9** [comment]
All macros listed here have been removed from`es` docs.

**Comment by MrBrain295** [comment]
`DiscussionList` is gone.

**Comment by queengooborg** [comment]
I updated this issue to include _all_ deprecated macros, as well as macro arguments (AKA `{{Compat}}` with arguments is deprecated).  I've updated the list accordingly and linked to existing issues where I could find them!

**Comment by MrBrain295** [comment]
{{bug}} and {{WebkitBug}} have been deprecated along with {{HTMLRefTable}}.

**Comment by hochan222** [comment]
About `bug - 745 occurrences (replace w/ [Firefox bug $1](https://bugzil.la/$1))`

`/{{\s*[bB]ug\("?(\d+)"?\)\s*}}/g` is enough for ko

**Comment by SphinxKnight** [comment]
Closed in favor of https://github.com/orgs/mdn/discussions/263 as an issue should have an end.
