### ISSUE TITLE
Macro removal - Meta - French part of #5603

### ISSUE THREAD

**Issue by SphinxKnight** [mdn/translated-content#5607]
This issue intends to track what's necessary for `fr` files in order to remove macros listed on #5603 (to avoid "flooding" this other issue with French-related stuff).
Here is the list of macros of interest:

- [x] `DOM0` - 24 files -#5668
- [x] `DiscussionList` - 5 files - #5652 #5653
- [x] `EditorGuideQuicklinks` - 1 file #5664
- [x] `HTML5ArticleTOC` - 1 file #5666
- [x] `HTMLVersionInline` -  15 files #5732
- [x] `Note` - 23 files #5711
- [x] `Obsolete_Header` - 54 files to be dealt with in "Cleanup orphaned" PRs, #5610 and #5611
- [x] `Obsolete_Inline` - 70 files #5631 and #5634
- [x] `TemplateLink` -  4 files #5624
- [x] `gecko_callout_heading` - 3 files #5621
- [x] `languages` - 18 files
  - [x] conflicting/learn - 2 files to be deleted in #5377
  - [x] conflicting/web/api - 4 files #5654
  - [x] conflicting/web/css - 5 files #5679 and #5755
  - [x] conflicting/web/guide - 2 files #5707
  - [x] conflicting/web/http/basics_of_http/mime_types/index.html #5706
  - [x] conflicting/web/javascript/reference/global_objects/object/tosource/index.html #5705
  - [x] conflicting/web/xpath/introduction_to_using_xpath_in_javascript/index.html #5700
  - [x] orphaned/web/api - 2 files, deleted in #5334 and #5327
- [x] `nextPage` - 1 file, to be deleted in #5377
- [x] `previousPage` - 1 file, to be deleted in #5377
- [x] `wiki.localize` - 4 files - #5608
