### ISSUE TITLE
AutoCorrect zh-CN TODO

### ISSUE THREAD

**Issue by huacnlee** [mdn/translated-content#5879]
## SVG
- [x] https://github.com/mdn/translated-content/pull/5875
- [x] https://github.com/mdn/translated-content/pull/5962
- [x] https://github.com/mdn/translated-content/pull/5963

## JavaScript

- [x] https://github.com/mdn/translated-content/pull/5876
- [x] https://github.com/mdn/translated-content/pull/5968
- [x] https://github.com/mdn/translated-content/pull/5969
- [x] https://github.com/mdn/translated-content/pull/5970
- [x] https://github.com/mdn/translated-content/pull/5971
- [x] https://github.com/mdn/translated-content/pull/5972
- [x] https://github.com/mdn/translated-content/pull/5973
- [x] https://github.com/mdn/translated-content/pull/5974
- [x] https://github.com/mdn/translated-content/pull/5975
- [x] https://github.com/mdn/translated-content/pull/5976
- [x] https://github.com/mdn/translated-content/pull/5977
- [x] https://github.com/mdn/translated-content/pull/5978
- [x] https://github.com/mdn/translated-content/pull/5979
- [x] https://github.com/mdn/translated-content/pull/5877
- [x] https://github.com/mdn/translated-content/pull/5878

## HTTP

- [x] https://github.com/mdn/translated-content/pull/5880
- [x] https://github.com/mdn/translated-content/pull/5881
- [x] https://github.com/mdn/translated-content/pull/5882

## API

- [x] https://github.com/mdn/translated-content/pull/5883
- [x] https://github.com/mdn/translated-content/pull/5884
- [x] https://github.com/mdn/translated-content/pull/5885
- [x] https://github.com/mdn/translated-content/pull/5886
- [x] https://github.com/mdn/translated-content/pull/5887
- [x] https://github.com/mdn/translated-content/pull/5888
- [x] https://github.com/mdn/translated-content/pull/5889
- [x] https://github.com/mdn/translated-content/pull/5890
- [x] https://github.com/mdn/translated-content/pull/5891
- [x] https://github.com/mdn/translated-content/pull/5892
- [x] https://github.com/mdn/translated-content/pull/5893
- [x] https://github.com/mdn/translated-content/pull/5894
- [x] https://github.com/mdn/translated-content/pull/5895
- [x] https://github.com/mdn/translated-content/pull/5896
- [x] https://github.com/mdn/translated-content/pull/5897
- [x] https://github.com/mdn/translated-content/pull/5898
- [x] https://github.com/mdn/translated-content/pull/5899
- [x] https://github.com/mdn/translated-content/pull/5900
- [x] https://github.com/mdn/translated-content/pull/5901
- [x] https://github.com/mdn/translated-content/pull/5902
- [x] https://github.com/mdn/translated-content/pull/5903
- [x] https://github.com/mdn/translated-content/pull/5904
- [x] https://github.com/mdn/translated-content/pull/5905
- [x] https://github.com/mdn/translated-content/pull/5906
- [x] https://github.com/mdn/translated-content/pull/5907
- [x] https://github.com/mdn/translated-content/pull/5908
- [x] https://github.com/mdn/translated-content/pull/5909
- [x] https://github.com/mdn/translated-content/pull/5910
- [x] https://github.com/mdn/translated-content/pull/5911
- [x] https://github.com/mdn/translated-content/pull/5912
- [x] https://github.com/mdn/translated-content/pull/5913
- [x] https://github.com/mdn/translated-content/pull/5914
- [x] https://github.com/mdn/translated-content/pull/5915
- [x] https://github.com/mdn/translated-content/pull/5916
- [x] https://github.com/mdn/translated-content/pull/5917
- [x] https://github.com/mdn/translated-content/pull/5918
- [x] https://github.com/mdn/translated-content/pull/5919
- [x] https://github.com/mdn/translated-content/pull/5920 
- [x] https://github.com/mdn/translated-content/pull/5921
- [x] https://github.com/mdn/translated-content/pull/5922
- [x] https://github.com/mdn/translated-content/pull/5923
- [x] https://github.com/mdn/translated-content/pull/5924
- [x] https://github.com/mdn/translated-content/pull/5925
- [x] https://github.com/mdn/translated-content/pull/5926
- [x] https://github.com/mdn/translated-content/pull/5927
- [x] https://github.com/mdn/translated-content/pull/5928
- [x] https://github.com/mdn/translated-content/pull/5929
- [x] https://github.com/mdn/translated-content/pull/5930
- [x] https://github.com/mdn/translated-content/pull/5931
- [x] https://github.com/mdn/translated-content/pull/5932
- [x] https://github.com/mdn/translated-content/pull/5933
- [x] https://github.com/mdn/translated-content/pull/5934
- [x] https://github.com/mdn/translated-content/pull/5935
- [x] https://github.com/mdn/translated-content/pull/5936
- [x] https://github.com/mdn/translated-content/pull/5937
- [x] https://github.com/mdn/translated-content/pull/5938
- [x] https://github.com/mdn/translated-content/pull/5939
- [x] https://github.com/mdn/translated-content/pull/5940
- [x] https://github.com/mdn/translated-content/pull/5941

## CSS

- [x] https://github.com/mdn/translated-content/pull/5942
- [x] https://github.com/mdn/translated-content/pull/5943
- [x] https://github.com/mdn/translated-content/pull/5944
- [x] https://github.com/mdn/translated-content/pull/5945
- [x] https://github.com/mdn/translated-content/pull/5946
- [x] https://github.com/mdn/translated-content/pull/5947
- [x] https://github.com/mdn/translated-content/pull/5948
- [x] https://github.com/mdn/translated-content/pull/5949
- [x] https://github.com/mdn/translated-content/pull/5950
- [x] https://github.com/mdn/translated-content/pull/5951
- [x] https://github.com/mdn/translated-content/pull/5952
- [x] https://github.com/mdn/translated-content/pull/5953
- [x] https://github.com/mdn/translated-content/pull/5954
- [x] https://github.com/mdn/translated-content/pull/5955
- [x] https://github.com/mdn/translated-content/pull/5956
- [x] https://github.com/mdn/translated-content/pull/5957

## Web

- [x] https://github.com/mdn/translated-content/pull/5958
- [x] https://github.com/mdn/translated-content/pull/5965
- [x] https://github.com/mdn/translated-content/pull/5966
- [x] https://github.com/mdn/translated-content/pull/5967
- [x] https://github.com/mdn/translated-content/pull/5959
- [x] https://github.com/mdn/translated-content/pull/5960
- [x] https://github.com/mdn/translated-content/pull/5961

**Comment by huacnlee** [comment]
Close #5726

**Comment by huacnlee** [comment]
- [ ] Enable CI checker: https://github.com/mdn/translated-content/pull/4191

**Comment by huacnlee** [comment]
Case need to ignore in AutoCorrect config:

https://github.com/mdn/translated-content/pull/5976/files/834a444eda053d8c615831ea1e9f021463a23603#diff-ca82117aa8f6215dfa888ef24f975676cee56c0dd866cf452806aff8e305edec

**Comment by irvin** [comment]
@huacnlee we just merge the last PR. Please do a manual review again to ensure there is no any doc to be corrected in /zh-cn folder atm.

**Comment by yin1999** [comment]
And please exclude the `conflicting` dir for not necessary.

**Comment by huacnlee** [comment]
😂 Em.....

I have updated for improve AutoCorrect rules after the early PR has merged. Now, there still have about 1000 files need to correct.

It all about for remove the invalid spaces near the commas or periods. Can we just make one PR to fix them?
