### ISSUE TITLE
Tracking markdown convertion for zh-{CN,TW}

### ISSUE THREAD

**Issue by yin1999** [mdn/translated-content#6173]
It's used to track the markdown convertion for zh-{CN, TW} documents. Before starting the conversion, we need to:

- [x] clean up `<a>` tag (at least remove `title` and `style`), see: #6065 for zh-TW
- [x] clean up `<p>`, `<dt>`, `<dd>`, see: #6035 #6088 #6127 #6168 (almost done)
- [x] replace `standard-table` with `{{Specifications}}` macros (optional, still working on it daily) #5782, #6873
- [x] remove all `<font>` and `<span>` tags~ (done in both zh-CN and zh-TW, see #5436)
- [x] clean up ~`h1-h5`~, ~`strong`~ tags #6515, #6879

To working on it, please see #2474 to set up the environment first.

**Comment by yin1999** [comment]
zh-TW:

- [ ] web/accessibility #6513

**Comment by awxiaoxian2020** [comment]
Hi, @yin1999 I want to write a guide in Simplified Chinese for this issue as the project is huge and complex. Do you think it is necessary to make a PR?

**Comment by yin1999** [comment]
zh-CN:

- [ ] glossary #6625

**Comment by awxiaoxian2020** [comment]
Could we only convert them and not care the content review for the time being?

**Comment by yin1999** [comment]
> Could we only convert them and not care the content review for the time being?

If you want, you can add a `continue;` here (locally): https://github.com/mdn/yari/blob/528d743ae2935d3dc5482585a28449ba5a2a0d30/markdown/cli.ts#L190-L196

Then you can just run `--mode replace` to convert non-error documents (section by section, and leave `mozilla` section for me)

> If there are too many unhandled errors, it's harder to resolve in .md files.

**Comment by awxiaoxian2020** [comment]
> > Could we only convert them and not care the content review for the time being?
> 
> If you want, you can add a `continue;` here (locally): https://github.com/mdn/yari/blob/528d743ae2935d3dc5482585a28449ba5a2a0d30/markdown/cli.ts#L190-L196
> 
> Then you can just run `--mode replace` to convert non-error documents (section by section, and leave `mozilla` section for me)
> 
> > If there are too many unhandled errors, it's harder to resolve in .md files.

格式问题我会处理的，我是说将文件转换成 md 文件而不关心翻译是否过时，是否准确等问题。等到全部转换完成（merge）后有时间再重新维护内容。格式问题我会处理的。
如果可以的话，我将发起一个 PR 去批量地处理文件。

**Comment by yin1999** [comment]
> 格式问题我会处理的，我是说将文件转换成 md 文件而不关心翻译是否过时，是否准确等问题。等到全部转换完成（merge）后有时间再重新维护内容。格式问题我会处理的。 如果可以的话，我将发起一个 PR 去批量地处理文件。

对于批量文件转换，不用关心是否过时

**Comment by awxiaoxian2020** [comment]
> > 格式问题我会处理的，我是说将文件转换成 md 文件而不关心翻译是否过时，是否准确等问题。等到全部转换完成（merge）后有时间再重新维护内容。格式问题我会处理的。 如果可以的话，我将发起一个 PR 去批量地处理文件。
> 
> 对于批量文件转换，不用关心是否过时

I‘ll work on it.

**Comment by queengooborg** [comment]
Hey all -- FYI, I've written a new conversion guide at https://github.com/mdn/markdown/blob/main/conversion-guide.md with updated instructions, as many of the special cases that had to be taken care of before conversion are now automatically handled!  Hope this helps with your locale's conversion!

**Comment by yin1999** [comment]
Hi @irvin, there are only conflicting documents left in html format. How should we deal with them?

/cc @queengooborg

**Comment by irvin** [comment]
hi @yin1999 feel free to removed them, thanks.
