### ISSUE TITLE
Macro - Meta - Remove transclusion {{EmbedLiveSample}} calls from `es`

### ISSUE THREAD

**Issue by JuanVqz** [mdn/translated-content#6509]
Hola contribuyentes de MDN en español. Estamos mejorando la macro `EmbedLiveSample` y tenemos que revisar los documentos en la lista para hacerlos coincidir con la versión en inglés.

Pueden haber diferentes formas de resolver los casos en esta lista, así que presta mucha atención y si tienes dudas pregunta en este mismo issue, gracias :rocket:  

Hice el primer punto como ejemplo y explicaré lo que hice en un comentario a continuación. 

- [x] #6749
- [x] #6786
- [x] #6787
- [x] #6788
- [x] #6789
- [ ] #6832
- [ ] #6833
- [x] #6792
- [x] #6794
- [ ] #6834
- [ ] #6835
- [ ] #6836
- [ ] #6837
- [ ] #6838
- [ ] #6839
- [ ] #6840
- [ ] web/css/flex-basis/index.html
- [ ] web/css/flex-direction/index.html
- [ ] web/css/flex-grow/index.html
- [ ] web/css/flex-shrink/index.html
- [ ] web/css/font-variant-alternates/index.html
- [ ] web/css/order/index.html
- [x] #6883
- [ ] web/css/text-overflow/index.html
- [ ] web/html/element/input/index.html
- [x] #6862
- [ ] web/html/global_attributes/itemref/index.html
- [x] web/html/global_attributes/itemscope/index.html #8205
- [ ] web/html/microdata/index.html
- [ ] web/javascript/guide/regular_expressions/index.html

Otras referencias: https://github.com/mdn/translated-content/issues/5717

Related to #5716

To-do
- Update content with English versión
- Convert to `md`
Con los dos anteriores automáticamente queda el siguiente
- Reformatear la macro `EmbedLiveSample`

Example
From
`{{ EmbedLiveSample('Rect_code', '700', '300', '', 'Games/Techniques/2D_collision_detection') }}`
To (in some cases needs to write the code
`{{ EmbedLiveSample('', '700', '300', '') }}`

**Comment by Graywolf9** [comment]
Hola! Corrí el comando provisto en https://github.com/mdn/content/issues/15872

`rg "EmbedLiveSample *\([^,]*,[^,]*,[^,]*,[^,]*, *'[^'][^']*'" -i`

Y conseguí el número de archivos detectados en https://github.com/mdn/translated-content/issues/5716 

Revisé con los tuyos y las diferencias solo eran por que había más de una macro en algunos archivos.

Acomodo y creo algunos issue con la línea de cada uno.

Muchas gracias por la colaboración!

![Captura de Pantalla 2022-07-08 a la(s) 11 14 42](https://user-images.githubusercontent.com/13079269/178031431-003db7d9-6c74-46b0-a663-7b0a743cfc91.png)
