### ISSUE TITLE
Removal of `{{Interwiki}}` macro

### ISSUE THREAD

**Issue by SphinxKnight** [mdn/translated-content#7287]
Per https://github.com/mdn/mdn-community/discussions/165
Opening an issue in order to track this more easily with labels.

- [x]  @mdn/yari-content-es : ~188~ 185 files https://github.com/mdn/translated-content/pull/9818 and https://github.com/mdn/translated-content/pull/9819
- [x]  @mdn/yari-content-fr : 265 files https://github.com/mdn/translated-content/pull/7288, https://github.com/mdn/translated-content/pull/7288
- [x] @mdn/yari-content-ja : ~334~ 324 files #8735 
- [x] @mdn/yari-content-ko : 122 files https://github.com/mdn/translated-content/pull/7426
- [ ] @mdn/yari-content-pt-br : 104 files #13922
- [x] @mdn/yari-content-ru : 137 files #11511
- [x] @mdn/yari-content-zh : 
  - [x] `zh-CN` : 193 files https://github.com/mdn/translated-content/pull/7306
  - [x] `zh-TW` : 116 files https://github.com/mdn/translated-content/pull/7307

**Comment by yin1999** [comment]
all `{{interwiki}}` macros are removed from l10n-zh

**Comment by cw118** [comment]
Taken care of in #7288 for fr

**Comment by hochan222** [comment]
Taken care of in https://github.com/mdn/translated-content/pull/7426 for ko.

**Comment by mfuji09** [comment]
'ja' has been completed.

**Comment by Graywolf9** [comment]
`es` done in #9818 and #9819

**Comment by sashasushko** [comment]
Salut 👋 I created PR for `ru` locale, but I need a little bit of help with CI checks 🙄 Can someone tell me what's the problem with "Build changed content" job, please?

**Comment by yin1999** [comment]
> Salut 👋 I created PR for `ru` locale, but I need a little bit of help with CI checks 🙄 Can someone tell me what's the problem with "Build changed content" job, please? 

Related to mdn/content#23605, please resolve #10493 first, and then merge main branch into your PR.

**Comment by sashasushko** [comment]
Done for `ru` locale
