### ISSUE TITLE
ZH-CN: broken external links

### ISSUE THREAD

**Issue by OnkarRuikar** [mdn/translated-content#7320]
All external broken links in `mdn/content` have been fixed: https://github.com/mdn/content/pull/19085

While working on the PRs I've found following broken links in `zh-cn` locale:
**_redirects.txt**
- [ ] https://firefox-source-docs.mozilla.org/devtools-user/performance/call_tree/index.html
- [ ] https://firefox-source-docs.mozilla.org/devtools-user/performance//...
- [ ] https://firefox-source-docs.mozilla.org/devtools-user/performance/frame_rate/index.html

** others **
- [x] https://github.com/mdn/panner-node
- [ ] https://mail.mozilla.org/listinfo/dev-addons
- [x] https://mdn.github.io/webaudio-examples/spacialization/
- [x] https://mdn.mozillademos.org/ (tracking in #6366)
- [ ] https://dxr.mozilla.org/mozilla-central/source/netwerk/protocol/about/public/nsIAboutModule.idl
- [x] http://docs.activestate.com/komodo/8.5/
- [x] http://mxr.mozilla.org/chromium/source/src/third_party/WebKit/Source/web/WebInputEventFactoryMac.mm #9212
- [x] http://mxr.mozilla.org/mozilla-central/source/dom/interfaces/css/nsIDOMCSSImportRule.idl #9212
- [x] https://amazing.site
- [x] https://cipherli.st/ #9212
- [x] https://developer.android.com/guide/practices/ui_guidelines/icon_design.html #9212
- [x] https://developer.android.com/sdk/index.html #9212
- [x] https://discuss.atom.io/categories
- [x] https://faculty.cascadia.edu/cma/HIST148/cmscrib.pdf #9212
- [x] http://docs.activestate.com/komodo/8.5/
- [x] https://mdn-samples.mozilla.org/ #9230
- [x] https://mdn-samples.mozilla.org/s/webrtc-simple-datachannel #7437
- [x] modern.ie #7437
- [x] https://opendevicelab.com/ #7437
- [x] www.aha-soft.com/free-icons/free-retina-icon-set #7437
- [x] www.ucweb.com/ucbrowser #7437
- [x] www.weba11y.com/blog/2016/04/22/screen-reader-support-for-new-html5-section-elements #7437
- [x] http://webglstats.com #7437
- [x] http://weblogs.mozillazine.org/roc/archives/2010/08/mozrequestanima.html #7437

In the process we've removed all `Source`[[ref](https://github.com/mdn/content/pull/18872)] and `Interwiki` macros.
***
**Tips:**
- To find files for the links without using IDE use GitHub Code search feature, e.g.
 [`https://github.com/mdn/translated-content/search?q=modern.ie`](https://github.com/mdn/translated-content/search?q=modern.ie)
- For links that are only part of the discussion put them in code fences(e.g. `www.example.com`) to avoid creating actual hyper links for them on the site. [[ref](https://github.com/mdn/content/pull/18917)]
- To find the URL replacements we'll have to look at the same file on `mdn/content`.

**Comment by yin1999** [comment]
Thanks for raising this, I'll work on it :)

**Comment by yin1999** [comment]
Hi @OnkarRuikar, I'm not sure about the broken links in `_redirects.txt`. Seems to exist in `mdn/content`.

![image](https://user-images.githubusercontent.com/15844309/199655447-51e8e47c-2275-499a-8ade-b7a1318a306f.png)

**Comment by OnkarRuikar** [comment]
> Hi @OnkarRuikar, I'm not sure about the broken links in `_redirects.txt`. Seems to exist in `mdn/content`.

These remained in `_redirects.txt` but it aren't used in the content. Looks like we need to remove them manually from the file.

This shouldn't matter as the final link redirected to is broken.
[en-US](https://developer.mozilla.org/en-US/docs/Web/Performance#other_documentation)
VS
[zh-CN](https://developer.mozilla.org/zh-CN/docs/Web/Performance#%E5%85%B6%E4%BB%96%E6%96%87%E6%A1%A3)

**Comment by yin1999** [comment]
> These remained in `_redirects.txt` but aren't used in the content. Looks like we need to remove them manually from the file.
>
> This shouldn't matter as the final link redirected to is broken.

Thanks for the reply :)
