### ISSUE TITLE
Macro removal - meta - `{{css_key_concepts}}`

### ISSUE THREAD

**Issue by SphinxKnight** [mdn/translated-content#7343]
Hello all, I went with deprecating `{{css_key_concepts}}` on https://github.com/mdn/yari/pull/6819 after it has been removed from mdn/content in https://github.com/mdn/content/pull/19105
For coordination on mdn/translated-content, here is the current list of calls:

- [x] @mdn/yari-content-es 13 files
- [x] @mdn/yari-content-fr 2 files - https://github.com/mdn/translated-content/pull/7334
- [x] @mdn/yari-content-ja 21 files - #7448
- [x] @mdn/yari-content-ko 15 files - https://github.com/mdn/translated-content/pull/7404, https://github.com/mdn/translated-content/pull/7428
- [x] @mdn/yari-content-pt-br 17 files #9284 
- [x] @mdn/yari-content-ru 18 files #7617
- [x]  @mdn/yari-content-zh 18 files for `zh-CN` and 4 files for `zh-TW` #7353
- [x] `de` 8 files - https://github.com/mdn/translated-content/pull/7352

The macro should be replaced by the content it generates. However,  I've seen a gap between the English content in the macro and the localized version (for fr).

I'll provide the existing generated content for each locale in Markdown in the following comments to help replace this one.

**Comment by SphinxKnight** [comment]
- `es` : not localized in the macro (another good reason to get rid of it), you can check https://github.com/mdn/content/blob/main/files/en-us/web/css/cascade/index.md?plain=1#L380-L397
- `ja`
 ```markdown
  - CSS の主要概念:
    - [CSS 構文](/ja/docs/Web/CSS/Syntax)
    - [アット規則](/ja/docs/Web/CSS/At-rule)
    - [コメント](/ja/docs/Web/CSS/Comments)
    - [詳細度](/ja/docs/Web/CSS/Specificity)
    - [継承](/ja/docs/Web/CSS/inheritance)
    - [ボックス](/ja/docs/Web/CSS/CSS_Box_Model/Introduction_to_the_CSS_box_model)
    - [レイアウトモード](/ja/docs/Web/CSS/Layout_mode)
    - [視覚整形モデル](/ja/docs/Web/CSS/Visual_formatting_model)
    - [マージンの相殺](/ja/docs/Web/CSS/CSS_Box_Model/Mastering_margin_collapsing)
    - 値
      - [初期値](/ja/docs/Web/CSS/initial_value)
      - [計算値](/ja/docs/Web/CSS/computed_value)
      - [解決値](/ja/docs/Web/CSS/resolved_value)
      - [指定値](/ja/docs/Web/CSS/specified_value)
      - [使用値](/ja/docs/Web/CSS/used_value)
      - [実効値](/ja/docs/Web/CSS/actual_value)
    - [値の定義構文](/ja/docs/Web/CSS/Value_definition_syntax)
    - [一括指定プロパティ](/ja/docs/Web/CSS/Shorthand_properties)
    - [置換要素](/ja/docs/Web/CSS/Replaced_element)
  ```

**Comment by SphinxKnight** [comment]
- `ru`
 ```markdown
  - Ключевые концепции CSS:
    - [Синтаксис CSS](/ru/docs/Web/CSS/Syntax)
    - [@-правила](/ru/docs/Web/CSS/At-rule)
    - [комментарии](/ru/docs/Web/CSS/Comments)
    - [специфичность](/ru/docs/Web/CSS/Specificity)
    - [наследование](/ru/docs/Web/CSS/inheritance)
    - [блочная модель](/ru/docs/Web/CSS/CSS_Box_Model/Introduction_to_the_CSS_box_model)
    - [режимы компоновки](/ru/docs/Web/CSS/Layout_mode)
    - [модели визуального форматирования](/ru/docs/Web/CSS/Visual_formatting_model)
    - [схлопывание отступов](/ru/docs/Web/CSS/CSS_Box_Model/Mastering_margin_collapsing)
    - значения
      - [начальные](/ru/docs/Web/CSS/initial_value)
      - [вычисленные](/ru/docs/Web/CSS/computed_value)
      - [решённые](/ru/docs/Web/CSS/resolved_value)
      - [указанные](/ru/docs/Web/CSS/specified_value)
      - [используемые](/ru/docs/Web/CSS/used_value)
      - [действительные](/ru/docs/Web/CSS/actual_value)
    - [Синтаксис определения значений](/ru/docs/Web/CSS/Value_definition_syntax)
    - [сокращённые свойства](/ru/docs/Web/CSS/Shorthand_properties)
    - [замещаемые элементы](/ru/docs/Web/CSS/Replaced_element)
  ```

**Comment by SphinxKnight** [comment]
- `zh-CN`
 ```markdown
  - CSS Key Concepts:
    - [CSS 语法](/zh-CN/docs/Web/CSS/Syntax)
    - [@规则](/zh-CN/docs/Web/CSS/At-rule)
    - [注释](/zh-CN/docs/Web/CSS/Comments)
    - [优先级](/zh-CN/docs/Web/CSS/Specificity)
    - [继承](/zh-CN/docs/Web/CSS/inheritance)
    - [盒模型](/zh-CN/docs/Web/CSS/CSS_Box_Model/Introduction_to_the_CSS_box_model)
    - [布局模式](/zh-CN/docs/Web/CSS/Layout_mode)
    - [视觉格式化模型](/zh-CN/docs/Web/CSS/Visual_formatting_model)
    - [外边距合并](/zh-CN/docs/Web/CSS/CSS_Box_Model/Mastering_margin_collapsing)
    - <I'm unsure for this one>
      - [初始](/zh-CN/docs/Web/CSS/initial_value)
      - [计算](/zh-CN/docs/Web/CSS/computed_value)
      - [解析](/zh-CN/docs/Web/CSS/resolved_value)
      - [指定](/zh-CN/docs/Web/CSS/specified_value)
      - [使用](/zh-CN/docs/Web/CSS/used_value)
      - [实际](/zh-CN/docs/Web/CSS/actual_value)
    - [Definition of 值语法](/zh-CN/docs/Web/CSS/Value_definition_syntax)
    - [简写属性](/zh-CN/docs/Web/CSS/Shorthand_properties)
    - [可替换元素](/zh-CN/docs/Web/CSS/Replaced_element)
  ```

**Comment by sashasushko** [comment]
Here is PR for `ru` - https://github.com/mdn/translated-content/pull/7617

**Comment by mfuji09** [comment]
'ja' removed.

**Comment by Graywolf9** [comment]
`es` done in #9607

**Comment by sashasushko** [comment]
@SphinxKnight done for RU - https://github.com/mdn/translated-content/pull/9937

**Comment by cw118** [comment]
It looks like all `{{css_key_concepts}}` have been removed 🎉
