### ISSUE TITLE
Meta - partially translated files

### ISSUE THREAD

**Issue by queengooborg** [mdn/translated-content#7459]
This issue is an overview issue documenting various documents containing only partial translations.  It is most likely that localization for these documents began during the wiki era of MDN, and thus it is highly likely these documents are very outdated.  Each document should be reviewed carefully and compared with the current English content, and then updated accordingly (or removed for later rewriting, if the document is too outdated).

- [x] es
  - [x] /games/tutorials/2d_breakout_game_phaser https://github.com/mdn/translated-content/pull/9640
  - [x] /glossary/doctype https://github.com/mdn/translated-content/pull/9921
  - [x] /glossary/grid_lines https://github.com/mdn/translated-content/pull/10084
  - [x] /glossary/mvc https://github.com/mdn/translated-content/pull/10127
  - [x] /glossary/php https://github.com/mdn/translated-content/pull/12111
  - [x] /glossary/webvtt https://github.com/mdn/translated-content/pull/12112
  - [x] /mdn/writing_guidelines/howto/write_a_new_entry_in_the_glossary https://github.com/mdn/translated-content/pull/12113
  - [x] /mdn/tools/kumascript https://github.com/mdn/translated-content/pull/12115

If you find additional documents with partial translations that are not listed, please write a comment and I'll add them (or fellow peers with write access, feel free to edit the issue directly)!  I will progressively update this list as I find more documents.

_Contributors: please do not close this issue yet once the list is completed, as there may be more entries.  SphinxKnight or I are planning to write a script to automatically detect documents containing too much English._

**Comment by queengooborg** [comment]
Notice: partial translations will soon be tracked through flaws per https://github.com/mdn/yari/pull/8254!

**Comment by queengooborg** [comment]
Closing this issue as it is no longer needed.
