### ISSUE TITLE
Chore - convert all HTML files to Markdown

### ISSUE THREAD

**Issue by queengooborg** [mdn/translated-content#7486]
This issue is an overview issue for the Markdown conversion project.  Throughout the localized content, there are still ~~20,919~~ 6,813 files that have yet to be converted from HTML to Markdown.  This applies to all locales and should be considered a high priority task.

Instructions:

Please carefully read the [conversion guide](https://github.com/mdn/markdown/blob/main/conversion-guide.md) in the `mdn/markdown` repository.  The script that you will need is also contained within this repository.

Reviewers: remember to **rebase merge** instead of **squash merge** to retain Git history for converted files!

Locales:
- [x] es - ~~2366~~ ~~2047~~ 1723 files remain https://github.com/mdn/translated-content/issues/8635
- [x] fr
- [x] ja - ~~3806~~ 0 files remain #7782
- [x] ko - ~~2126~~ ~~403~~ ~~329~~ 0 files remain https://github.com/mdn/translated-content/issues/2894
- [x] pt-br - ~~2071~~ ~~1201~~ 503 files remain https://github.com/mdn/translated-content/issues/7950
- [x] ru - ~~2861~~ 2389 files remain https://github.com/mdn/translated-content/issues/7580
- [x] zh - ~~4968~~ 0 files remain  #6173

**Comment by SphinxKnight** [comment]
Thanks a lot @queengooborg
I hope https://github.com/mdn/translated-content/discussions/2474 may also be useful.

**Comment by queengooborg** [comment]
Thanks for linking that guide, @SphinxKnight, this is really amazing!

Do you mind if I update the guide text, including pointing translators to my fork of mdn/markdown, and update a few descriptions of special cases that don't need to be handled any longer?  I know that sounds like a little bit of self-advertising (since it's my own fork and all), but the upstream script contains a critical issue that causes loss of information (and my updates _do_ handle a lot of the special cases previously unhandled) and I want to discourage the upstream script's use until the issues have been resolved (AKA my PR is merged)!

**Comment by SphinxKnight** [comment]
> Do you mind if I update the guide text, including pointing translators to my fork of mdn/markdown, and update a few descriptions of special cases that don't need to be handled any longer?

Please do if you can edit it :)
And if you can't directly, let me know your version over a pastebin or Matrix and I'll apply it

**Comment by queengooborg** [comment]
Good news: my changes were now merged upstream and I have write access to the upstream repository now, so I'll be able to update the script much easier!

**Comment by hochan222** [comment]
> 3. Run `yarn h2m <folder> --locale <locale> --mode replace`

It seems that md is missing somehow, is that correct..? Or are there any other recent changes?

`yarn md h2m <folder> --locale <locale> --mode replace`

**Comment by queengooborg** [comment]
That's correct, yes!  Because "h2m" is the only command in the repository, I removed the "md" part of the command for a little more simplicity!

**Comment by hochan222** [comment]
If so, the code merge hasn't been done yet. Thanks for the reply :)

> package.json for yari
>
> "md": "ts-node markdown/cli.ts",

**Comment by queengooborg** [comment]
Ah, you should actually be using https://github.com/mdn/markdown, not Yari -- the code has been moved out of Yari a long time ago (I thought it was actually removed from Yari), and the version in Yari is not getting any updates!

**Comment by queengooborg** [comment]
Just wanted to say: great job, everyone!  Since the creation of this issue, we are almost halfway finished with converting all the localized files to Markdown!

**Comment by queengooborg** [comment]
In regards to the commits that have been (self-)merged to perform Markdown conversion on the "non-problematic" files, I'd like to clarify a couple of points for everyone:

"Non-problematic" means an HTML file that could be converted to Markdown with the conversion script, where no problems were reported (unhandleable elements, invalid conversions, etc.).  That is, these are the HTML files that did not need any tweaks before conversion, so the script could handle them all.

I recently self-merged a number of PRs that perform these conversions.  I realize that self-merging was probably a mistake for active locales, as merge conflicts have occurred and for some locales the HTML conversion was used as a to-do list.  I apologize for the disruption of everyone's workflows as a result of this project.  Markdown conversion has been a high priority for the MDN team, and now that the English locale has been fully converted, all that's left is the translated files.  I've self-merged these conversion PRs to expedite the process, so that everyone working on each locale can focus on continuing translations, rather than meta updates like this one!

I'll be working on cleaning up any Markdown conversion-related issues, as I know there were some instances of bad HTML markup creating bad Markdown markup.

**Comment by mfuji09** [comment]
@queengooborg 
How do you think a lot of PRs waiting for review were wasted due to your self-merging "non-problematic" files without prior notice to translation communities?

Will it happen again?

**Comment by queengooborg** [comment]
Any big change is going to cause a stir when it comes to pull requests, regardless of how long a notice is given prior.  I'd like to point out that more than half of the translation communities have been aware of this conversion project, and many are even actively working on it.  I'd also like to point out that reviews would not be "wasted"; yes, the PR author would have to rebase and re-perform changes, but nothing is lost to the ages.

**Comment by hochan222** [comment]
In my opinion, even if that is the case, I think **we should at least seek the consent of the locale reviewers when editing a locale documents.** They are ultimately responsible for the documentation of the locale.

There are many other reasons, but two come to mind right now.

There will be a locale policy they set, and I think it is an **important value and trust to actually solve the inconvenience of other contributors.**

**Also, the markdown converter is still incomplete.** This goes beyond grammar and can also be a language problem. So, if many files are merged without a locale reviewer, it can be unsettling.

So, if locale reviewers are active, wouldn't it be better to avoid (self-)merged?

**Comment by queengooborg** [comment]
> They are ultimately responsible for the documentation of the locale.

Well...yes, but also no.  Generally speaking, the files within a locale are the responsibility of that team, yes, however there are also decisions that are/must be made by the higher-ups (such as the English content writers, Yari engineers, and most importantly, MDN admins).  Macro removal and Markdown conversion are examples of such decisions.

> Also, the markdown converter is still incomplete.

Can you describe what is still incomplete about the conversion script?

**Comment by hochan222** [comment]
> there are also decisions that are/must be made by the higher-ups (such as the English content writers, Yari engineers, and most importantly, MDN admins).

I agree. I think that thought was my mistake. 

> Can you describe what is still incomplete about the conversion script?

It's much better than before, so I'm converting almost all cases and converting them comfortably. However, some exceptions still make merging large units unsafe. 

In the case of the table, problems are still appearing. This indicates that we have to deal with it manually.

Table related tags in `Mozilla/Add-ons/WebExtensions/manifest.json`, `Mozilla/Add-ons/WebExtensions/manifest.json/page_action` are converted to markdown when using the markdown converter, but they are broken.

In particular, `Mozilla/Add-ons/WebExtensions/manifest.json/page_action` seems to be fine at first glance unless you examine the page closely. In reality, the table is broken and the output is divided into several paragraphs. In some cases, we can see that there is a space for a single word.

<img width="786" alt="image" src="https://user-images.githubusercontent.com/22424891/184494921-ca0c58bd-1219-4d84-a26d-04c91abd3a8e.png">

Or it could be this case. https://github.com/mdn/markdown/issues/51 

It seems that these errors cannot be registered as error cases.

I agree that all files should be converted to markdown in no time. **I had no other intentions, and my thoughts were started because there could be mistakes that anyone did not think of.**

**Comment by yin1999** [comment]
It seems that the markdown converter will also convert some unconvertable table (e.g. a table without headers)

**Comment by mfuji09** [comment]
@queengooborg 
I don't think the higher-up maintainers' decisions is incorrect, and I (and we) will respect it. I (and we) won't avoid it.
However, doing it without any notices, explanations, discussions or agreements makes a disaster for us.
If you discussed us before doing it, we (as least I) would co-operate to do gladly.

>  I'd also like to point out that reviews would not be "wasted"; yes, the PR author would have to rebase and re-perform changes, but nothing is lost to the ages.

You easily say "it would not be wasted", but our works are increased much more because we made these PRs without knowing the converting. Isn't it "wasted"? Unlike paid workers,
We are volunteers and therefore work within a limited time frame.

I hope if you respect other translators' works.

**Comment by mfuji09** [comment]
'ja' locale is done.

**Comment by SphinxKnight** [comment]
see https://hacks.mozilla.org/2022/09/the-100-percent-markdown-expedition/ and https://github.com/mdn/mdn-community/discussions/227 from @schalkneethling

**Comment by hochan222** [comment]
`ko locale` is done :)

**Comment by SphinxKnight** [comment]
`pt-BR` is done apart from `conflicting` and `orphaned` folders :) Thanks @josielrocha and @nathipg for the reviews 🙇

**Comment by Mahadeb73** [comment]
Government of India

**Comment by Graywolf9** [comment]
`es` locale is done!

**Comment by SphinxKnight** [comment]
and `ru` is done as well thanks to @sashasushko :)

Only HTML files remaining are oprhaned/conflicting for `ru` and `pt-BR`
