### ISSUE TITLE
Meta - Tracking issue for Markdown conversion `es`

### ISSUE THREAD

**Issue by SphinxKnight** [mdn/translated-content#8635]
This issue intends to track ongoing work to convert every HTML document into Markdown for the Spanish-speaking section.

- [x] Conflicting as of 31st Aug. 2022: https://github.com/mdn/translated-content/pull/8038
- [x] Games
- [x] Glossary
  - [x] #7477
- [x] Learn
  - [x] #8886
  - [x] #7727
  - <details>
      <summary>Closed PRs</summary>
      <ul>
        <li>#7478</li>
        <li>#7704</li>
        <li>#7723</li>
        <li>#7724</li>
        <li>#7725</li>
      </ul>
    </details>
- [x] MDN (https://github.com/mdn/translated-content/pull/7456)
- [x] Mozilla
  - #8037
  - #8911
  - <details>
      <summary>Closed PRs</summary>
      <ul>
        <li>#8214</li>
      </ul>
    </details> 
- [x] Web
  - [x] Accessibility
    - #8926
  - [x] API
    - [x] #8561
    - [x] #8670
    - [x] #8910
    - [x] #9301
    - [x] #9307
    - [x] #9309
    - [x] #9310
    - [x] #9423
    - [x] #9504
    - [x] #9513
    - [x] #9552
  - [x] CSS
    - [x] #9351
    - [x] #9409
    - [x] #9421
    - [x] #9534
    - <details>
        <summary>Closed PRs</summary>
        <ul>
          <li>#8235</li>
        </ul>
      </details> 
  - [x] Events
    - [x] #8926
  - [x] EXSLT
    - [x] #8159
  - [x] Guide
    - [x] #8926
  - [x] HTML
    - [x] #9225
    - <details>
        <summary>Closed PRs</summary>
        <ul>
          <li>#8205</li>
          <li>#8206</li>
          <li>#8208</li>
          <li>#8209</li>
        </ul>
      </details>
  - [x] HTTP
    - [x] #8201
    - [x] #8202
    - [x] #8203
    - [x] #8984
  - [x] JavaScript
    - [x] #8161
    - [x] #8162
    - [x] #8164
    - [x] #8165
    - [x] #8166
    - [x] #8167
    - [x] #8168
    - [x] #8169
    - [x] #8171
    - [x] #8199
    - [x] #8200
    - [x] #8984
    - <details>
      <summary>Closed PRs</summary>
      <ul>
        <li>#8160</li>
      </ul>
    </details>
  - [x] Manifest, MathML, Media, Performance, Progressive Web Apps, Security
    - [x] #8926
  - [x] SVG
    - [x] #8157
    - [x] #8926
  - [x] Tutorials, Web Components, XML
    - [x] #8926 
  - [x] XPath
    - [x] #8155
    - [x] #8926
  - [x] XSLT
    - [x] #8154
    - [x] #8926
- [x] WebAssembly
    - [x] #8911
    - Cleanup: TBD
    - Replace: TBD
- [x] Other PRs
  - <details>
      <summary>Closed PRs</summary>
      <ul>
        <li>#7618</li>
        <li>#7619</li>
        <li>#8039</li>
      </ul>
    </details>

## See also

- https://github.com/mdn/translated-content/issues/7486 for the general issue
- https://docs.google.com/spreadsheets/d/1Mk3bQoHXozN2rUWn9rxVHA5MiO0whDLuj71KKC0iMSg/edit#gid=1017304837 for the Google Spreadsheet

**Comment by Graywolf9** [comment]
I think this is finally done!

```
translated-content/files/es on  main
❯ find . -iname "*.html"

translated-content/files/es on  main
❯
```

**Comment by nschonni** [comment]
Probably a few of the other old issues that could get closed too https://github.com/mdn/translated-content/issues?q=is%3Aopen+label%3Amarkdown-conversion+label%3Al10n-es
