### ISSUE TITLE
Update JSRef / jsxref calls in pages touched by https://github.com/mdn/content/pull/20603 and #8643

### ISSUE THREAD

**Issue by SphinxKnight** [mdn/translated-content#8657]

**Comment by tristantheb** [comment]
Searched with `jsxref\(["']web`

## TODO:

- [x] `Web/JavaScript/Reference/Global_Objects`
- [x] `WebAssembly`
- [x] `WebAssembly/Guides/Exported_functions`
- [x] `WebAssembly/Guides/Loading_and_running`
- [x] `WebAssembly/Guides/Using_the_JavaScript_API`
- [x] `WebAssembly/Reference/JavaScript_interface`
- [x] `WebAssembly/Reference/JavaScript_interface/Instance/exports`
- [x] `WebAssembly/Reference/JavaScript_interface/Memory`
- [x] `WebAssembly/Reference/JavaScript_interface/Memory/buffer`
- [x] `WebAssembly/Reference/JavaScript_interface/Table`
- [x] `WebAssembly/Reference/JavaScript_interface/Table/get`
- [x] `WebAssembly/Reference/JavaScript_interface/Table/grow`
- [x] `WebAssembly/Reference/JavaScript_interface/Table/length`
- [x] `WebAssembly/Reference/JavaScript_interface/Table/set`
