### ISSUE TITLE
Missing translations upstream in files/jsondata/L10n-*.json

### ISSUE THREAD

**Issue by nschonni** [mdn/translated-content#8749]
## What page(s) did you find the problem on?

This appears to be one of the metadata files migrated from Yari. Some of the keys are missing for some of the languages:
- [x] https://github.com/mdn/content/blob/main/files/jsondata/L10n-Common.json
  - [x] #10078
  - [x] fr (already OK)
  - [x] ja
  - [x] ko https://github.com/mdn/content/pull/24525
  - [x] pt-br (https://github.com/mdn/content/pull/22590)
  - [x] ru
  - [x] zh-cn
  - [x] zh-tw mdn/content#22510
- [x] https://github.com/mdn/content/blob/main/files/jsondata/L10n-CSS.json
  - [x] es
  - [x] fr (no missing key but a typofix in https://github.com/mdn/content/pull/21548)
  - [x] ja
  - [x] ko https://github.com/mdn/content/pull/24525
  - [x] pt-br
  - [x] ru
  - [x] zh-cn
  - [x] zh-tw mdn/content#23405
- [x] https://github.com/mdn/content/blob/main/files/jsondata/L10n-JavaScript.json
  - [x] es
  - [x] fr (already OK)
  - [x] ja
  - [x] ko https://github.com/mdn/content/pull/24525
  - [x] pt-br
  - [x] ru
  - [x] zh-cn
  - [x] zh-tw mdn/content#23405
- [x] https://github.com/mdn/content/blob/main/files/jsondata/L10n-SVG.json
  - [x] es
  - [x] fr https://github.com/mdn/content/pull/21548
  - [x] ja
  - [x] ko https://github.com/mdn/content/pull/24525
  - [x] pt-br (https://github.com/mdn/content/pull/22590)
  - [x] ru
  - [x] zh-cn
  - [x] zh-tw mdn/content#23431 mdn/content#24094

**Comment by yin1999** [comment]
Done for `zh-CN`.

**Comment by nschonni** [comment]
I wasn't sure if sub-checkmarks for languages would be helpful.
@yin1999 does `zn-TW` need separate keys for these files? I wasn't sure if they had some sort of cross l10n fallback.

**Comment by yin1999** [comment]
> I wasn't sure if sub-checkmarks for languages would be helpful. @yin1999 does `zh-TW` need separate keys for these files? I wasn't sure if they had some sort of cross l10n fallback.

I think there is no fallback on this. And adding zh-TW translation may be a better choise than using fallback (for there is still some difference between them).

@irvin Do you have the time to add zh-TW translation for those items?

**Comment by nschonni** [comment]
OK, I just added sub-bullets to track each locale. It would probably make sense to sort the keys in the end

**Comment by mfuji09** [comment]
Done for `ja`.

**Comment by Graywolf9** [comment]
With https://github.com/mdn/translated-content/issues/10078 is done for `es` 

thank you so much @JuanVqz and everyone!

**Comment by leon-win** [comment]
Done for `ru` :sunglasses:
